[workspace]
resolver = "3"
members = ["crates/document-core"]

[workspace.dependencies]
axum = "0.8.9"
tokio = { version = "1.53.1", features = ["full"] }
tower = "0.5.3"

tracing = { version = "0.1.44" }
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json"] }
tracing-log = { version = "0.2.0" }

uuid = { version = "1.24.0", features = ["v4"] }
thiserror = { version = "2.0.20" }
