// DiagnosticsService — the gRPC contract for RFC-003's analyzer engine
// and ROADMAP.md's fact dependency graph (v2.3.0, docs/planning/RELEASES.md).
// See docs/api/diagnostics.md, which this file matches field-for-field.
//
// diagnostics-service is stateless — no database of its own. It reads
// document-service's PageService/GraphService as a gRPC client and
// computes fresh per request (internal/analyzers, internal/facts), the
// same "no persisted incremental cache" scope cut those packages'
// own doc comments state plainly. This is what makes RFC-003 §5's
// degradation story real: kill this service's pod and editing is
// unaffected, because nothing here is on that path.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.0
// source: diagnostics.proto

package diagnosticsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzePageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzePageRequest) Reset() {
	*x = AnalyzePageRequest{}
	mi := &file_diagnostics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzePageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzePageRequest) ProtoMessage() {}

func (x *AnalyzePageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diagnostics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzePageRequest.ProtoReflect.Descriptor instead.
func (*AnalyzePageRequest) Descriptor() ([]byte, []int) {
	return file_diagnostics_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzePageRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

type AnalyzePageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Diagnostics   []*Diagnostic          `protobuf:"bytes,1,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzePageResponse) Reset() {
	*x = AnalyzePageResponse{}
	mi := &file_diagnostics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzePageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzePageResponse) ProtoMessage() {}

func (x *AnalyzePageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diagnostics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzePageResponse.ProtoReflect.Descriptor instead.
func (*AnalyzePageResponse) Descriptor() ([]byte, []int) {
	return file_diagnostics_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzePageResponse) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type Diagnostic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Analyzer      string                 `protobuf:"bytes,1,opt,name=analyzer,proto3" json:"analyzer,omitempty"` // one of RFC-003 §2's nine analyzer names, verbatim
	Severity      string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"` // "hint" | "warning" | "info" — never anything higher (RFC-003 §2)
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	BlockId       *string                `protobuf:"bytes,4,opt,name=block_id,json=blockId,proto3,oneof" json:"block_id,omitempty"` // absent for a page-level diagnostic (DuplicateTitle, OrphanPage, LinkCycle)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Diagnostic) Reset() {
	*x = Diagnostic{}
	mi := &file_diagnostics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnostic) ProtoMessage() {}

func (x *Diagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_diagnostics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnostic.ProtoReflect.Descriptor instead.
func (*Diagnostic) Descriptor() ([]byte, []int) {
	return file_diagnostics_proto_rawDescGZIP(), []int{2}
}

func (x *Diagnostic) GetAnalyzer() string {
	if x != nil {
		return x.Analyzer
	}
	return ""
}

func (x *Diagnostic) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Diagnostic) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Diagnostic) GetBlockId() string {
	if x != nil && x.BlockId != nil {
		return *x.BlockId
	}
	return ""
}

type AnalyzeFactsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeFactsRequest) Reset() {
	*x = AnalyzeFactsRequest{}
	mi := &file_diagnostics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeFactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeFactsRequest) ProtoMessage() {}

func (x *AnalyzeFactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diagnostics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeFactsRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeFactsRequest) Descriptor() ([]byte, []int) {
	return file_diagnostics_proto_rawDescGZIP(), []int{3}
}

type AnalyzeFactsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Definitions   []*Definition          `protobuf:"bytes,1,rep,name=definitions,proto3" json:"definitions,omitempty"`
	Duplicates    []*DuplicateGroup      `protobuf:"bytes,2,rep,name=duplicates,proto3" json:"duplicates,omitempty"`
	Cycle         []string               `protobuf:"bytes,3,rep,name=cycle,proto3" json:"cycle,omitempty"` // one example cycle of fact names, closed (first == last); empty if acyclic
	References    []*Reference           `protobuf:"bytes,4,rep,name=references,proto3" json:"references,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeFactsResponse) Reset() {
	*x = AnalyzeFactsResponse{}
	mi := &file_diagnostics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeFactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeFactsResponse) ProtoMessage() {}

func (x *AnalyzeFactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diagnostics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeFactsResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeFactsResponse) Descriptor() ([]byte, []int) {
	return file_diagnostics_proto_rawDescGZIP(), []int{4}
}

func (x *AnalyzeFactsResponse) GetDefinitions() []*Definition {
	if x != nil {
		return x.Definitions
	}
	return nil
}

func (x *AnalyzeFactsResponse) GetDuplicates() []*DuplicateGroup {
	if x != nil {
		return x.Duplicates
	}
	return nil
}

func (x *AnalyzeFactsResponse) GetCycle() []string {
	if x != nil {
		return x.Cycle
	}
	return nil
}

func (x *AnalyzeFactsResponse) GetReferences() []*Reference {
	if x != nil {
		return x.References
	}
	return nil
}

type Definition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	PageId        string                 `protobuf:"bytes,3,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	BlockId       string                 `protobuf:"bytes,4,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Definition) Reset() {
	*x = Definition{}
	mi := &file_diagnostics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Definition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Definition) ProtoMessage() {}

func (x *Definition) ProtoReflect() protoreflect.Message {
	mi := &file_diagnostics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Definition.ProtoReflect.Descriptor instead.
func (*Definition) Descriptor() ([]byte, []int) {
	return file_diagnostics_proto_rawDescGZIP(), []int{5}
}

func (x *Definition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Definition) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Definition) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *Definition) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

type DuplicateGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Definitions   []*Definition          `protobuf:"bytes,2,rep,name=definitions,proto3" json:"definitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DuplicateGroup) Reset() {
	*x = DuplicateGroup{}
	mi := &file_diagnostics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DuplicateGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DuplicateGroup) ProtoMessage() {}

func (x *DuplicateGroup) ProtoReflect() protoreflect.Message {
	mi := &file_diagnostics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DuplicateGroup.ProtoReflect.Descriptor instead.
func (*DuplicateGroup) Descriptor() ([]byte, []int) {
	return file_diagnostics_proto_rawDescGZIP(), []int{6}
}

func (x *DuplicateGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DuplicateGroup) GetDefinitions() []*Definition {
	if x != nil {
		return x.Definitions
	}
	return nil
}

type Reference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PageId        string                 `protobuf:"bytes,2,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	BlockId       string                 `protobuf:"bytes,3,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reference) Reset() {
	*x = Reference{}
	mi := &file_diagnostics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reference) ProtoMessage() {}

func (x *Reference) ProtoReflect() protoreflect.Message {
	mi := &file_diagnostics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reference.ProtoReflect.Descriptor instead.
func (*Reference) Descriptor() ([]byte, []int) {
	return file_diagnostics_proto_rawDescGZIP(), []int{7}
}

func (x *Reference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Reference) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *Reference) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

type StaleReferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FactName      string                 `protobuf:"bytes,1,opt,name=fact_name,json=factName,proto3" json:"fact_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StaleReferencesRequest) Reset() {
	*x = StaleReferencesRequest{}
	mi := &file_diagnostics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaleReferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaleReferencesRequest) ProtoMessage() {}

func (x *StaleReferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diagnostics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaleReferencesRequest.ProtoReflect.Descriptor instead.
func (*StaleReferencesRequest) Descriptor() ([]byte, []int) {
	return file_diagnostics_proto_rawDescGZIP(), []int{8}
}

func (x *StaleReferencesRequest) GetFactName() string {
	if x != nil {
		return x.FactName
	}
	return ""
}

type StaleReferencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	References    []*Reference           `protobuf:"bytes,1,rep,name=references,proto3" json:"references,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StaleReferencesResponse) Reset() {
	*x = StaleReferencesResponse{}
	mi := &file_diagnostics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaleReferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaleReferencesResponse) ProtoMessage() {}

func (x *StaleReferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diagnostics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaleReferencesResponse.ProtoReflect.Descriptor instead.
func (*StaleReferencesResponse) Descriptor() ([]byte, []int) {
	return file_diagnostics_proto_rawDescGZIP(), []int{9}
}

func (x *StaleReferencesResponse) GetReferences() []*Reference {
	if x != nil {
		return x.References
	}
	return nil
}

var File_diagnostics_proto protoreflect.FileDescriptor

const file_diagnostics_proto_rawDesc = "" +
	"\n" +
	"\x11diagnostics.proto\x12\x17marginal.diagnostics.v1\"-\n" +
	"\x12AnalyzePageRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\"\\\n" +
	"\x13AnalyzePageResponse\x12E\n" +
	"\vdiagnostics\x18\x01 \x03(\v2#.marginal.diagnostics.v1.DiagnosticR\vdiagnostics\"\x8b\x01\n" +
	"\n" +
	"Diagnostic\x12\x1a\n" +
	"\banalyzer\x18\x01 \x01(\tR\banalyzer\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1e\n" +
	"\bblock_id\x18\x04 \x01(\tH\x00R\ablockId\x88\x01\x01B\v\n" +
	"\t_block_id\"\x15\n" +
	"\x13AnalyzeFactsRequest\"\x80\x02\n" +
	"\x14AnalyzeFactsResponse\x12E\n" +
	"\vdefinitions\x18\x01 \x03(\v2#.marginal.diagnostics.v1.DefinitionR\vdefinitions\x12G\n" +
	"\n" +
	"duplicates\x18\x02 \x03(\v2'.marginal.diagnostics.v1.DuplicateGroupR\n" +
	"duplicates\x12\x14\n" +
	"\x05cycle\x18\x03 \x03(\tR\x05cycle\x12B\n" +
	"\n" +
	"references\x18\x04 \x03(\v2\".marginal.diagnostics.v1.ReferenceR\n" +
	"references\"j\n" +
	"\n" +
	"Definition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x17\n" +
	"\apage_id\x18\x03 \x01(\tR\x06pageId\x12\x19\n" +
	"\bblock_id\x18\x04 \x01(\tR\ablockId\"k\n" +
	"\x0eDuplicateGroup\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12E\n" +
	"\vdefinitions\x18\x02 \x03(\v2#.marginal.diagnostics.v1.DefinitionR\vdefinitions\"S\n" +
	"\tReference\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\apage_id\x18\x02 \x01(\tR\x06pageId\x12\x19\n" +
	"\bblock_id\x18\x03 \x01(\tR\ablockId\"5\n" +
	"\x16StaleReferencesRequest\x12\x1b\n" +
	"\tfact_name\x18\x01 \x01(\tR\bfactName\"]\n" +
	"\x17StaleReferencesResponse\x12B\n" +
	"\n" +
	"references\x18\x01 \x03(\v2\".marginal.diagnostics.v1.ReferenceR\n" +
	"references2\xe1\x02\n" +
	"\x12DiagnosticsService\x12h\n" +
	"\vAnalyzePage\x12+.marginal.diagnostics.v1.AnalyzePageRequest\x1a,.marginal.diagnostics.v1.AnalyzePageResponse\x12k\n" +
	"\fAnalyzeFacts\x12,.marginal.diagnostics.v1.AnalyzeFactsRequest\x1a-.marginal.diagnostics.v1.AnalyzeFactsResponse\x12t\n" +
	"\x0fStaleReferences\x12/.marginal.diagnostics.v1.StaleReferencesRequest\x1a0.marginal.diagnostics.v1.StaleReferencesResponseB5Z3marginal/diagnostics-service/genproto/diagnosticsv1b\x06proto3"

var (
	file_diagnostics_proto_rawDescOnce sync.Once
	file_diagnostics_proto_rawDescData []byte
)

func file_diagnostics_proto_rawDescGZIP() []byte {
	file_diagnostics_proto_rawDescOnce.Do(func() {
		file_diagnostics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_diagnostics_proto_rawDesc), len(file_diagnostics_proto_rawDesc)))
	})
	return file_diagnostics_proto_rawDescData
}

var file_diagnostics_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_diagnostics_proto_goTypes = []any{
	(*AnalyzePageRequest)(nil),      // 0: marginal.diagnostics.v1.AnalyzePageRequest
	(*AnalyzePageResponse)(nil),     // 1: marginal.diagnostics.v1.AnalyzePageResponse
	(*Diagnostic)(nil),              // 2: marginal.diagnostics.v1.Diagnostic
	(*AnalyzeFactsRequest)(nil),     // 3: marginal.diagnostics.v1.AnalyzeFactsRequest
	(*AnalyzeFactsResponse)(nil),    // 4: marginal.diagnostics.v1.AnalyzeFactsResponse
	(*Definition)(nil),              // 5: marginal.diagnostics.v1.Definition
	(*DuplicateGroup)(nil),          // 6: marginal.diagnostics.v1.DuplicateGroup
	(*Reference)(nil),               // 7: marginal.diagnostics.v1.Reference
	(*StaleReferencesRequest)(nil),  // 8: marginal.diagnostics.v1.StaleReferencesRequest
	(*StaleReferencesResponse)(nil), // 9: marginal.diagnostics.v1.StaleReferencesResponse
}
var file_diagnostics_proto_depIdxs = []int32{
	2, // 0: marginal.diagnostics.v1.AnalyzePageResponse.diagnostics:type_name -> marginal.diagnostics.v1.Diagnostic
	5, // 1: marginal.diagnostics.v1.AnalyzeFactsResponse.definitions:type_name -> marginal.diagnostics.v1.Definition
	6, // 2: marginal.diagnostics.v1.AnalyzeFactsResponse.duplicates:type_name -> marginal.diagnostics.v1.DuplicateGroup
	7, // 3: marginal.diagnostics.v1.AnalyzeFactsResponse.references:type_name -> marginal.diagnostics.v1.Reference
	5, // 4: marginal.diagnostics.v1.DuplicateGroup.definitions:type_name -> marginal.diagnostics.v1.Definition
	7, // 5: marginal.diagnostics.v1.StaleReferencesResponse.references:type_name -> marginal.diagnostics.v1.Reference
	0, // 6: marginal.diagnostics.v1.DiagnosticsService.AnalyzePage:input_type -> marginal.diagnostics.v1.AnalyzePageRequest
	3, // 7: marginal.diagnostics.v1.DiagnosticsService.AnalyzeFacts:input_type -> marginal.diagnostics.v1.AnalyzeFactsRequest
	8, // 8: marginal.diagnostics.v1.DiagnosticsService.StaleReferences:input_type -> marginal.diagnostics.v1.StaleReferencesRequest
	1, // 9: marginal.diagnostics.v1.DiagnosticsService.AnalyzePage:output_type -> marginal.diagnostics.v1.AnalyzePageResponse
	4, // 10: marginal.diagnostics.v1.DiagnosticsService.AnalyzeFacts:output_type -> marginal.diagnostics.v1.AnalyzeFactsResponse
	9, // 11: marginal.diagnostics.v1.DiagnosticsService.StaleReferences:output_type -> marginal.diagnostics.v1.StaleReferencesResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_diagnostics_proto_init() }
func file_diagnostics_proto_init() {
	if File_diagnostics_proto != nil {
		return
	}
	file_diagnostics_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_diagnostics_proto_rawDesc), len(file_diagnostics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_diagnostics_proto_goTypes,
		DependencyIndexes: file_diagnostics_proto_depIdxs,
		MessageInfos:      file_diagnostics_proto_msgTypes,
	}.Build()
	File_diagnostics_proto = out.File
	file_diagnostics_proto_goTypes = nil
	file_diagnostics_proto_depIdxs = nil
}
