// DiscoverService — the gRPC contract for § 09 DISCOVER, "what is near this
// page by MEANING", as opposed to near by citation (GraphService) or near in
// the drawn layout (§ 07's SPACE lens). See docs/api/discover.md.
//
// Read-only and computed fresh per request, like GraphService: there is no
// persisted index yet, and internal/discover's own doc comment says exactly
// what would replace the per-request rebuild and when.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.0
// source: discover.proto

package documentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DiscoverService_Near_FullMethodName = "/marginal.document.v1.DiscoverService/Near"
)

// DiscoverServiceClient is the client API for DiscoverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiscoverServiceClient interface {
	// Near returns the k pages closest to source_page_id in term space, with
	// the three signals kept separate, plus the index statistics that make the
	// answer checkable rather than merely fast.
	Near(ctx context.Context, in *NearRequest, opts ...grpc.CallOption) (*NearResponse, error)
}

type discoverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiscoverServiceClient(cc grpc.ClientConnInterface) DiscoverServiceClient {
	return &discoverServiceClient{cc}
}

func (c *discoverServiceClient) Near(ctx context.Context, in *NearRequest, opts ...grpc.CallOption) (*NearResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NearResponse)
	err := c.cc.Invoke(ctx, DiscoverService_Near_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscoverServiceServer is the server API for DiscoverService service.
// All implementations must embed UnimplementedDiscoverServiceServer
// for forward compatibility.
type DiscoverServiceServer interface {
	// Near returns the k pages closest to source_page_id in term space, with
	// the three signals kept separate, plus the index statistics that make the
	// answer checkable rather than merely fast.
	Near(context.Context, *NearRequest) (*NearResponse, error)
	mustEmbedUnimplementedDiscoverServiceServer()
}

// UnimplementedDiscoverServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiscoverServiceServer struct{}

func (UnimplementedDiscoverServiceServer) Near(context.Context, *NearRequest) (*NearResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Near not implemented")
}
func (UnimplementedDiscoverServiceServer) mustEmbedUnimplementedDiscoverServiceServer() {}
func (UnimplementedDiscoverServiceServer) testEmbeddedByValue()                         {}

// UnsafeDiscoverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiscoverServiceServer will
// result in compilation errors.
type UnsafeDiscoverServiceServer interface {
	mustEmbedUnimplementedDiscoverServiceServer()
}

func RegisterDiscoverServiceServer(s grpc.ServiceRegistrar, srv DiscoverServiceServer) {
	// If the following call panics, it indicates UnimplementedDiscoverServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DiscoverService_ServiceDesc, srv)
}

func _DiscoverService_Near_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NearRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoverServiceServer).Near(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoverService_Near_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoverServiceServer).Near(ctx, req.(*NearRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DiscoverService_ServiceDesc is the grpc.ServiceDesc for DiscoverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiscoverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "marginal.document.v1.DiscoverService",
	HandlerType: (*DiscoverServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Near",
			Handler:    _DiscoverService_Near_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "discover.proto",
}
