// PageService — the gRPC contract for page metadata (create/get/list/
// rename/reparent/delete). See docs/api/pages.md, which this file matches
// field-for-field — that doc is the source of truth for semantics; this
// file is its wire encoding.
//
// This is deliberately NOT where block content changes go — those are
// documentcore Ops (services/document-service/internal/documentcore),
// applied through a separate surface once one exists. PageService only
// owns the page row: title, tree position, lifecycle.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.0
// source: document.proto

package documentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LifecycleState int32

const (
	LifecycleState_LIFECYCLE_STATE_UNSPECIFIED LifecycleState = 0
	LifecycleState_LIFECYCLE_STATE_ACTIVE      LifecycleState = 1
	LifecycleState_LIFECYCLE_STATE_DELETING    LifecycleState = 2
	LifecycleState_LIFECYCLE_STATE_DELETED     LifecycleState = 3
)

// Enum value maps for LifecycleState.
var (
	LifecycleState_name = map[int32]string{
		0: "LIFECYCLE_STATE_UNSPECIFIED",
		1: "LIFECYCLE_STATE_ACTIVE",
		2: "LIFECYCLE_STATE_DELETING",
		3: "LIFECYCLE_STATE_DELETED",
	}
	LifecycleState_value = map[string]int32{
		"LIFECYCLE_STATE_UNSPECIFIED": 0,
		"LIFECYCLE_STATE_ACTIVE":      1,
		"LIFECYCLE_STATE_DELETING":    2,
		"LIFECYCLE_STATE_DELETED":     3,
	}
)

func (x LifecycleState) Enum() *LifecycleState {
	p := new(LifecycleState)
	*p = x
	return p
}

func (x LifecycleState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LifecycleState) Descriptor() protoreflect.EnumDescriptor {
	return file_document_proto_enumTypes[0].Descriptor()
}

func (LifecycleState) Type() protoreflect.EnumType {
	return &file_document_proto_enumTypes[0]
}

func (x LifecycleState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LifecycleState.Descriptor instead.
func (LifecycleState) EnumDescriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{0}
}

type Membership int32

const (
	Membership_MEMBERSHIP_UNSPECIFIED Membership = 0
	Membership_MEMBERSHIP_NONE        Membership = 1
	Membership_MEMBERSHIP_MEMBER      Membership = 2
	Membership_MEMBERSHIP_LEADER      Membership = 3
)

// Enum value maps for Membership.
var (
	Membership_name = map[int32]string{
		0: "MEMBERSHIP_UNSPECIFIED",
		1: "MEMBERSHIP_NONE",
		2: "MEMBERSHIP_MEMBER",
		3: "MEMBERSHIP_LEADER",
	}
	Membership_value = map[string]int32{
		"MEMBERSHIP_UNSPECIFIED": 0,
		"MEMBERSHIP_NONE":        1,
		"MEMBERSHIP_MEMBER":      2,
		"MEMBERSHIP_LEADER":      3,
	}
)

func (x Membership) Enum() *Membership {
	p := new(Membership)
	*p = x
	return p
}

func (x Membership) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Membership) Descriptor() protoreflect.EnumDescriptor {
	return file_document_proto_enumTypes[1].Descriptor()
}

func (Membership) Type() protoreflect.EnumType {
	return &file_document_proto_enumTypes[1]
}

func (x Membership) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Membership.Descriptor instead.
func (Membership) EnumDescriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{1}
}

type Page struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUIDv7
	CreatedBy      string                 `protobuf:"bytes,2,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Title          string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	ParentId       *string                `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	Path           string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`                      // materialised LTREE ancestry
	SortKey        string                 `protobuf:"bytes,6,opt,name=sort_key,json=sortKey,proto3" json:"sort_key,omitempty"` // opaque, lexicographic
	LifecycleState LifecycleState         `protobuf:"varint,7,opt,name=lifecycle_state,json=lifecycleState,proto3,enum=marginal.document.v1.LifecycleState" json:"lifecycle_state,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	// v2.7.0. One owned topic (absent = untopiced, a real state the UI
	// reports rather than a gap), and any number of free-form tags.
	Topic *Topic   `protobuf:"bytes,11,opt,name=topic,proto3,oneof" json:"topic,omitempty"`
	Tags  []string `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty"`
	// v2.8.0. How much document the page holds, over the docs.blocks
	// projection. Carried on Page because a reading estimate is drawn wherever
	// a page title is — the rail, the dashboard, the reader, search — and four
	// client-side word counts over four differently-shaped payloads is four
	// numbers that disagree. Both are 0 when the projection has no rows for
	// the page yet, which an empty page and a lagging projection share.
	BlockCount    int32 `protobuf:"varint,13,opt,name=block_count,json=blockCount,proto3" json:"block_count,omitempty"`
	WordCount     int32 `protobuf:"varint,14,opt,name=word_count,json=wordCount,proto3" json:"word_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_document_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{0}
}

func (x *Page) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Page) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Page) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Page) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

func (x *Page) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Page) GetSortKey() string {
	if x != nil {
		return x.SortKey
	}
	return ""
}

func (x *Page) GetLifecycleState() LifecycleState {
	if x != nil {
		return x.LifecycleState
	}
	return LifecycleState_LIFECYCLE_STATE_UNSPECIFIED
}

func (x *Page) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Page) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Page) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Page) GetTopic() *Topic {
	if x != nil {
		return x.Topic
	}
	return nil
}

func (x *Page) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Page) GetBlockCount() int32 {
	if x != nil {
		return x.BlockCount
	}
	return 0
}

func (x *Page) GetWordCount() int32 {
	if x != nil {
		return x.WordCount
	}
	return 0
}

// A topic is singular per page and carries a colour KEY, never a hex value
// — the palette lives in the design system (DESIGN_GUIDELINES.md §3.4).
type Topic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ColorKey      string                 `protobuf:"bytes,3,opt,name=color_key,json=colorKey,proto3" json:"color_key,omitempty"`     // protocol|storage|interface|operations|research
	PageCount     int32                  `protobuf:"varint,4,opt,name=page_count,json=pageCount,proto3" json:"page_count,omitempty"` // live pages only; 0 unless returned by ListTopics
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topic) Reset() {
	*x = Topic{}
	mi := &file_document_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topic) ProtoMessage() {}

func (x *Topic) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topic.ProtoReflect.Descriptor instead.
func (*Topic) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{1}
}

func (x *Topic) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Topic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Topic) GetColorKey() string {
	if x != nil {
		return x.ColorKey
	}
	return ""
}

func (x *Topic) GetPageCount() int32 {
	if x != nil {
		return x.PageCount
	}
	return 0
}

type GetPageSeriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPageSeriesRequest) Reset() {
	*x = GetPageSeriesRequest{}
	mi := &file_document_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPageSeriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPageSeriesRequest) ProtoMessage() {}

func (x *GetPageSeriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPageSeriesRequest.ProtoReflect.Descriptor instead.
func (*GetPageSeriesRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{2}
}

func (x *GetPageSeriesRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

// SeriesPart is one entry, in the parent's own sort order.
type SeriesPart struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	PageId string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	Title  string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// 1-based, as printed ("Part 3 of 19"). 0 is never a valid part number,
	// which makes an unset field visibly wrong rather than plausibly first.
	Number        int32    `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	WordCount     int32    `protobuf:"varint,4,opt,name=word_count,json=wordCount,proto3" json:"word_count,omitempty"`
	Topic         *Topic   `protobuf:"bytes,5,opt,name=topic,proto3,oneof" json:"topic,omitempty"`
	Tags          []string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeriesPart) Reset() {
	*x = SeriesPart{}
	mi := &file_document_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeriesPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeriesPart) ProtoMessage() {}

func (x *SeriesPart) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeriesPart.ProtoReflect.Descriptor instead.
func (*SeriesPart) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{3}
}

func (x *SeriesPart) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *SeriesPart) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SeriesPart) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *SeriesPart) GetWordCount() int32 {
	if x != nil {
		return x.WordCount
	}
	return 0
}

func (x *SeriesPart) GetTopic() *Topic {
	if x != nil {
		return x.Topic
	}
	return nil
}

func (x *SeriesPart) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type PageSeries struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The three states, kept apart because they need different words on screen:
	//
	//	MEMBER  — this page is a part; `parts` are its siblings, `number` is it.
	//	LEADER  — this page IS the series page; `parts` are its children.
	//	NONE    — neither. A page with no parent and no children.
	Membership   Membership    `protobuf:"varint,1,opt,name=membership,proto3,enum=marginal.document.v1.Membership" json:"membership,omitempty"`
	SeriesPageId string        `protobuf:"bytes,2,opt,name=series_page_id,json=seriesPageId,proto3" json:"series_page_id,omitempty"`
	SeriesTitle  string        `protobuf:"bytes,3,opt,name=series_title,json=seriesTitle,proto3" json:"series_title,omitempty"`
	Parts        []*SeriesPart `protobuf:"bytes,4,rep,name=parts,proto3" json:"parts,omitempty"`
	// 1-based position of the requested page within `parts`. 0 when LEADER or
	// NONE — the page is not itself a part.
	Number        int32 `protobuf:"varint,5,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageSeries) Reset() {
	*x = PageSeries{}
	mi := &file_document_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageSeries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageSeries) ProtoMessage() {}

func (x *PageSeries) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageSeries.ProtoReflect.Descriptor instead.
func (*PageSeries) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{4}
}

func (x *PageSeries) GetMembership() Membership {
	if x != nil {
		return x.Membership
	}
	return Membership_MEMBERSHIP_UNSPECIFIED
}

func (x *PageSeries) GetSeriesPageId() string {
	if x != nil {
		return x.SeriesPageId
	}
	return ""
}

func (x *PageSeries) GetSeriesTitle() string {
	if x != nil {
		return x.SeriesTitle
	}
	return ""
}

func (x *PageSeries) GetParts() []*SeriesPart {
	if x != nil {
		return x.Parts
	}
	return nil
}

func (x *PageSeries) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type ListSeriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSeriesRequest) Reset() {
	*x = ListSeriesRequest{}
	mi := &file_document_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSeriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSeriesRequest) ProtoMessage() {}

func (x *ListSeriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSeriesRequest.ProtoReflect.Descriptor instead.
func (*ListSeriesRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{5}
}

type SeriesSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeriesPageId  string                 `protobuf:"bytes,1,opt,name=series_page_id,json=seriesPageId,proto3" json:"series_page_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Topic         *Topic                 `protobuf:"bytes,3,opt,name=topic,proto3,oneof" json:"topic,omitempty"`
	PartCount     int32                  `protobuf:"varint,4,opt,name=part_count,json=partCount,proto3" json:"part_count,omitempty"`
	WordCount     int32                  `protobuf:"varint,5,opt,name=word_count,json=wordCount,proto3" json:"word_count,omitempty"` // the whole series, parts plus the series page
	Parts         []*SeriesPart          `protobuf:"bytes,6,rep,name=parts,proto3" json:"parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeriesSummary) Reset() {
	*x = SeriesSummary{}
	mi := &file_document_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeriesSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeriesSummary) ProtoMessage() {}

func (x *SeriesSummary) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeriesSummary.ProtoReflect.Descriptor instead.
func (*SeriesSummary) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{6}
}

func (x *SeriesSummary) GetSeriesPageId() string {
	if x != nil {
		return x.SeriesPageId
	}
	return ""
}

func (x *SeriesSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SeriesSummary) GetTopic() *Topic {
	if x != nil {
		return x.Topic
	}
	return nil
}

func (x *SeriesSummary) GetPartCount() int32 {
	if x != nil {
		return x.PartCount
	}
	return 0
}

func (x *SeriesSummary) GetWordCount() int32 {
	if x != nil {
		return x.WordCount
	}
	return 0
}

func (x *SeriesSummary) GetParts() []*SeriesPart {
	if x != nil {
		return x.Parts
	}
	return nil
}

type ListSeriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Series        []*SeriesSummary       `protobuf:"bytes,1,rep,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSeriesResponse) Reset() {
	*x = ListSeriesResponse{}
	mi := &file_document_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSeriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSeriesResponse) ProtoMessage() {}

func (x *ListSeriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSeriesResponse.ProtoReflect.Descriptor instead.
func (*ListSeriesResponse) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{7}
}

func (x *ListSeriesResponse) GetSeries() []*SeriesSummary {
	if x != nil {
		return x.Series
	}
	return nil
}

type CreatePageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	ParentId      *string                `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	After         *string                `protobuf:"bytes,3,opt,name=after,proto3,oneof" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePageRequest) Reset() {
	*x = CreatePageRequest{}
	mi := &file_document_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePageRequest) ProtoMessage() {}

func (x *CreatePageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePageRequest.ProtoReflect.Descriptor instead.
func (*CreatePageRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{8}
}

func (x *CreatePageRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePageRequest) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

func (x *CreatePageRequest) GetAfter() string {
	if x != nil && x.After != nil {
		return *x.After
	}
	return ""
}

type GetPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPageRequest) Reset() {
	*x = GetPageRequest{}
	mi := &file_document_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPageRequest) ProtoMessage() {}

func (x *GetPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPageRequest.ProtoReflect.Descriptor instead.
func (*GetPageRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{9}
}

func (x *GetPageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListPagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentId      *string                `protobuf:"bytes,1,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	After         *string                `protobuf:"bytes,2,opt,name=after,proto3,oneof" json:"after,omitempty"`
	Limit         *int32                 `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPagesRequest) Reset() {
	*x = ListPagesRequest{}
	mi := &file_document_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPagesRequest) ProtoMessage() {}

func (x *ListPagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPagesRequest.ProtoReflect.Descriptor instead.
func (*ListPagesRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{10}
}

func (x *ListPagesRequest) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

func (x *ListPagesRequest) GetAfter() string {
	if x != nil && x.After != nil {
		return *x.After
	}
	return ""
}

func (x *ListPagesRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type ListPagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pages         []*Page                `protobuf:"bytes,1,rep,name=pages,proto3" json:"pages,omitempty"`
	NextCursor    *string                `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3,oneof" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPagesResponse) Reset() {
	*x = ListPagesResponse{}
	mi := &file_document_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPagesResponse) ProtoMessage() {}

func (x *ListPagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPagesResponse.ProtoReflect.Descriptor instead.
func (*ListPagesResponse) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{11}
}

func (x *ListPagesResponse) GetPages() []*Page {
	if x != nil {
		return x.Pages
	}
	return nil
}

func (x *ListPagesResponse) GetNextCursor() string {
	if x != nil && x.NextCursor != nil {
		return *x.NextCursor
	}
	return ""
}

type RenamePageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenamePageRequest) Reset() {
	*x = RenamePageRequest{}
	mi := &file_document_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenamePageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenamePageRequest) ProtoMessage() {}

func (x *RenamePageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenamePageRequest.ProtoReflect.Descriptor instead.
func (*RenamePageRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{12}
}

func (x *RenamePageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RenamePageRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type ReparentPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId      *string                `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	After         *string                `protobuf:"bytes,3,opt,name=after,proto3,oneof" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReparentPageRequest) Reset() {
	*x = ReparentPageRequest{}
	mi := &file_document_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReparentPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReparentPageRequest) ProtoMessage() {}

func (x *ReparentPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReparentPageRequest.ProtoReflect.Descriptor instead.
func (*ReparentPageRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{13}
}

func (x *ReparentPageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReparentPageRequest) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

func (x *ReparentPageRequest) GetAfter() string {
	if x != nil && x.After != nil {
		return *x.After
	}
	return ""
}

type DeletePageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePageRequest) Reset() {
	*x = DeletePageRequest{}
	mi := &file_document_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePageRequest) ProtoMessage() {}

func (x *DeletePageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePageRequest.ProtoReflect.Descriptor instead.
func (*DeletePageRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{14}
}

func (x *DeletePageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListBacklinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBacklinksRequest) Reset() {
	*x = ListBacklinksRequest{}
	mi := &file_document_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBacklinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBacklinksRequest) ProtoMessage() {}

func (x *ListBacklinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBacklinksRequest.ProtoReflect.Descriptor instead.
func (*ListBacklinksRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{15}
}

func (x *ListBacklinksRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

type ListBacklinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Backlinks     []*Backlink            `protobuf:"bytes,1,rep,name=backlinks,proto3" json:"backlinks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBacklinksResponse) Reset() {
	*x = ListBacklinksResponse{}
	mi := &file_document_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBacklinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBacklinksResponse) ProtoMessage() {}

func (x *ListBacklinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBacklinksResponse.ProtoReflect.Descriptor instead.
func (*ListBacklinksResponse) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{16}
}

func (x *ListBacklinksResponse) GetBacklinks() []*Backlink {
	if x != nil {
		return x.Backlinks
	}
	return nil
}

type Backlink struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FromPage        string                 `protobuf:"bytes,1,opt,name=from_page,json=fromPage,proto3" json:"from_page,omitempty"`
	FromPageTitle   string                 `protobuf:"bytes,2,opt,name=from_page_title,json=fromPageTitle,proto3" json:"from_page_title,omitempty"`
	FromPageDeleted bool                   `protobuf:"varint,3,opt,name=from_page_deleted,json=fromPageDeleted,proto3" json:"from_page_deleted,omitempty"` // linking page's own lifecycle — a backlink from a since-deleted page is still worth showing as such
	TargetTitle     string                 `protobuf:"bytes,4,opt,name=target_title,json=targetTitle,proto3" json:"target_title,omitempty"`                // the literal text written, e.g. "Backlink Target" — may differ in case from this page's own title
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Backlink) Reset() {
	*x = Backlink{}
	mi := &file_document_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Backlink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backlink) ProtoMessage() {}

func (x *Backlink) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backlink.ProtoReflect.Descriptor instead.
func (*Backlink) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{17}
}

func (x *Backlink) GetFromPage() string {
	if x != nil {
		return x.FromPage
	}
	return ""
}

func (x *Backlink) GetFromPageTitle() string {
	if x != nil {
		return x.FromPageTitle
	}
	return ""
}

func (x *Backlink) GetFromPageDeleted() bool {
	if x != nil {
		return x.FromPageDeleted
	}
	return false
}

func (x *Backlink) GetTargetTitle() string {
	if x != nil {
		return x.TargetTitle
	}
	return ""
}

type ListBlocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlocksRequest) Reset() {
	*x = ListBlocksRequest{}
	mi := &file_document_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlocksRequest) ProtoMessage() {}

func (x *ListBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlocksRequest.ProtoReflect.Descriptor instead.
func (*ListBlocksRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{18}
}

func (x *ListBlocksRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

type ListBlocksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*Block               `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlocksResponse) Reset() {
	*x = ListBlocksResponse{}
	mi := &file_document_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlocksResponse) ProtoMessage() {}

func (x *ListBlocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlocksResponse.ProtoReflect.Descriptor instead.
func (*ListBlocksResponse) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{19}
}

func (x *ListBlocksResponse) GetBlocks() []*Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId      *string                `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	KindJson      string                 `protobuf:"bytes,3,opt,name=kind_json,json=kindJson,proto3" json:"kind_json,omitempty"`          // documentcore.BlockKind's own tagged-object JSON
	ContentJson   string                 `protobuf:"bytes,4,opt,name=content_json,json=contentJson,proto3" json:"content_json,omitempty"` // documentcore.Content's own JSON ({text, marks})
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_document_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{20}
}

func (x *Block) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Block) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

func (x *Block) GetKindJson() string {
	if x != nil {
		return x.KindJson
	}
	return ""
}

func (x *Block) GetContentJson() string {
	if x != nil {
		return x.ContentJson
	}
	return ""
}

type PreviewDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewDeleteRequest) Reset() {
	*x = PreviewDeleteRequest{}
	mi := &file_document_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewDeleteRequest) ProtoMessage() {}

func (x *PreviewDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewDeleteRequest.ProtoReflect.Descriptor instead.
func (*PreviewDeleteRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{21}
}

func (x *PreviewDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PreviewDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Descendants   []*Page                `protobuf:"bytes,1,rep,name=descendants,proto3" json:"descendants,omitempty"` // the LTREE subtree this delete cascades to
	Referrers     []*Page                `protobuf:"bytes,2,rep,name=referrers,proto3" json:"referrers,omitempty"`     // pages whose [[links]] would dangle
	BlockCount    int32                  `protobuf:"varint,3,opt,name=block_count,json=blockCount,proto3" json:"block_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewDeleteResponse) Reset() {
	*x = PreviewDeleteResponse{}
	mi := &file_document_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewDeleteResponse) ProtoMessage() {}

func (x *PreviewDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewDeleteResponse.ProtoReflect.Descriptor instead.
func (*PreviewDeleteResponse) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{22}
}

func (x *PreviewDeleteResponse) GetDescendants() []*Page {
	if x != nil {
		return x.Descendants
	}
	return nil
}

func (x *PreviewDeleteResponse) GetReferrers() []*Page {
	if x != nil {
		return x.Referrers
	}
	return nil
}

func (x *PreviewDeleteResponse) GetBlockCount() int32 {
	if x != nil {
		return x.BlockCount
	}
	return 0
}

type ListTrashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTrashRequest) Reset() {
	*x = ListTrashRequest{}
	mi := &file_document_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTrashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrashRequest) ProtoMessage() {}

func (x *ListTrashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrashRequest.ProtoReflect.Descriptor instead.
func (*ListTrashRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{23}
}

func (x *ListTrashRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTrashRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListTrashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*TrashEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTrashResponse) Reset() {
	*x = ListTrashResponse{}
	mi := &file_document_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTrashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrashResponse) ProtoMessage() {}

func (x *ListTrashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrashResponse.ProtoReflect.Descriptor instead.
func (*ListTrashResponse) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{24}
}

func (x *ListTrashResponse) GetEntries() []*TrashEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListTrashResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type TrashEntry struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Page    *Page                  `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	PurgeAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=purge_at,json=purgeAt,proto3" json:"purge_at,omitempty"` // derived: deleted_at + window
	// Present only while the saga runs. A finished saga has no progress to
	// report, so absence here is how a caller tells 'deleting' from 'deleted'
	// without re-reading lifecycle_state.
	Progress      *SagaProgress `protobuf:"bytes,3,opt,name=progress,proto3,oneof" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrashEntry) Reset() {
	*x = TrashEntry{}
	mi := &file_document_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrashEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrashEntry) ProtoMessage() {}

func (x *TrashEntry) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrashEntry.ProtoReflect.Descriptor instead.
func (*TrashEntry) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{25}
}

func (x *TrashEntry) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *TrashEntry) GetPurgeAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PurgeAt
	}
	return nil
}

func (x *TrashEntry) GetProgress() *SagaProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

type SagaProgress struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	StepsDone []string               `protobuf:"bytes,1,rep,name=steps_done,json=stepsDone,proto3" json:"steps_done,omitempty"` // in completion order
	StepsLeft []string               `protobuf:"bytes,2,rep,name=steps_left,json=stepsLeft,proto3" json:"steps_left,omitempty"`
	Attempts  int32                  `protobuf:"varint,3,opt,name=attempts,proto3" json:"attempts,omitempty"` // > 1 means it resumed after a crash
	LastError *string                `protobuf:"bytes,4,opt,name=last_error,json=lastError,proto3,oneof" json:"last_error,omitempty"`
	// Steps with no backing store at this repo's scope (embeddings, blobs).
	// Sent so the UI can render them as "no store yet" rather than as work
	// performed or silently drop them.
	NotApplicable []string `protobuf:"bytes,5,rep,name=not_applicable,json=notApplicable,proto3" json:"not_applicable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SagaProgress) Reset() {
	*x = SagaProgress{}
	mi := &file_document_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SagaProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SagaProgress) ProtoMessage() {}

func (x *SagaProgress) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SagaProgress.ProtoReflect.Descriptor instead.
func (*SagaProgress) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{26}
}

func (x *SagaProgress) GetStepsDone() []string {
	if x != nil {
		return x.StepsDone
	}
	return nil
}

func (x *SagaProgress) GetStepsLeft() []string {
	if x != nil {
		return x.StepsLeft
	}
	return nil
}

func (x *SagaProgress) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *SagaProgress) GetLastError() string {
	if x != nil && x.LastError != nil {
		return *x.LastError
	}
	return ""
}

func (x *SagaProgress) GetNotApplicable() []string {
	if x != nil {
		return x.NotApplicable
	}
	return nil
}

type RestorePageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestorePageRequest) Reset() {
	*x = RestorePageRequest{}
	mi := &file_document_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestorePageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestorePageRequest) ProtoMessage() {}

func (x *RestorePageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestorePageRequest.ProtoReflect.Descriptor instead.
func (*RestorePageRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{27}
}

func (x *RestorePageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListTopicsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopicsRequest) Reset() {
	*x = ListTopicsRequest{}
	mi := &file_document_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopicsRequest) ProtoMessage() {}

func (x *ListTopicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopicsRequest.ProtoReflect.Descriptor instead.
func (*ListTopicsRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{28}
}

type ListTopicsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Topics         []*Topic               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	UntopicedPages int32                  `protobuf:"varint,2,opt,name=untopiced_pages,json=untopicedPages,proto3" json:"untopiced_pages,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListTopicsResponse) Reset() {
	*x = ListTopicsResponse{}
	mi := &file_document_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopicsResponse) ProtoMessage() {}

func (x *ListTopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopicsResponse.ProtoReflect.Descriptor instead.
func (*ListTopicsResponse) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{29}
}

func (x *ListTopicsResponse) GetTopics() []*Topic {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *ListTopicsResponse) GetUntopicedPages() int32 {
	if x != nil {
		return x.UntopicedPages
	}
	return 0
}

// topic_id absent clears the assignment back to untopiced.
type SetPageTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	TopicId       *string                `protobuf:"bytes,2,opt,name=topic_id,json=topicId,proto3,oneof" json:"topic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPageTopicRequest) Reset() {
	*x = SetPageTopicRequest{}
	mi := &file_document_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPageTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPageTopicRequest) ProtoMessage() {}

func (x *SetPageTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPageTopicRequest.ProtoReflect.Descriptor instead.
func (*SetPageTopicRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{30}
}

func (x *SetPageTopicRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *SetPageTopicRequest) GetTopicId() string {
	if x != nil && x.TopicId != nil {
		return *x.TopicId
	}
	return ""
}

type AddPageTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPageTagRequest) Reset() {
	*x = AddPageTagRequest{}
	mi := &file_document_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPageTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPageTagRequest) ProtoMessage() {}

func (x *AddPageTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPageTagRequest.ProtoReflect.Descriptor instead.
func (*AddPageTagRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{31}
}

func (x *AddPageTagRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *AddPageTagRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type RemovePageTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePageTagRequest) Reset() {
	*x = RemovePageTagRequest{}
	mi := &file_document_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePageTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePageTagRequest) ProtoMessage() {}

func (x *RemovePageTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePageTagRequest.ProtoReflect.Descriptor instead.
func (*RemovePageTagRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{32}
}

func (x *RemovePageTagRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *RemovePageTagRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type ListTagFacetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagFacetsRequest) Reset() {
	*x = ListTagFacetsRequest{}
	mi := &file_document_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagFacetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagFacetsRequest) ProtoMessage() {}

func (x *ListTagFacetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagFacetsRequest.ProtoReflect.Descriptor instead.
func (*ListTagFacetsRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{33}
}

func (x *ListTagFacetsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListTagFacetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Facets        []*TagFacet            `protobuf:"bytes,1,rep,name=facets,proto3" json:"facets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagFacetsResponse) Reset() {
	*x = ListTagFacetsResponse{}
	mi := &file_document_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagFacetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagFacetsResponse) ProtoMessage() {}

func (x *ListTagFacetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagFacetsResponse.ProtoReflect.Descriptor instead.
func (*ListTagFacetsResponse) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{34}
}

func (x *ListTagFacetsResponse) GetFacets() []*TagFacet {
	if x != nil {
		return x.Facets
	}
	return nil
}

type TagFacet struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Tag       string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	PageCount int32                  `protobuf:"varint,2,opt,name=page_count,json=pageCount,proto3" json:"page_count,omitempty"`
	// Distinct topics the tag's pages span. ui-mockups § 10b: "a tag that
	// lives in three topics is doing real work — it names a technique, not a
	// subject."
	TopicsSpanned int32 `protobuf:"varint,3,opt,name=topics_spanned,json=topicsSpanned,proto3" json:"topics_spanned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagFacet) Reset() {
	*x = TagFacet{}
	mi := &file_document_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagFacet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagFacet) ProtoMessage() {}

func (x *TagFacet) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagFacet.ProtoReflect.Descriptor instead.
func (*TagFacet) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{35}
}

func (x *TagFacet) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *TagFacet) GetPageCount() int32 {
	if x != nil {
		return x.PageCount
	}
	return 0
}

func (x *TagFacet) GetTopicsSpanned() int32 {
	if x != nil {
		return x.TopicsSpanned
	}
	return 0
}

type SaveReadingPositionRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	PageId string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	// Absent means "this page, but no particular block" — a page opened and
	// scrolled but never clicked into. Still worth resuming to.
	BlockId       *string `protobuf:"bytes,2,opt,name=block_id,json=blockId,proto3,oneof" json:"block_id,omitempty"`
	CaretStart    int32   `protobuf:"varint,3,opt,name=caret_start,json=caretStart,proto3" json:"caret_start,omitempty"`
	CaretEnd      int32   `protobuf:"varint,4,opt,name=caret_end,json=caretEnd,proto3" json:"caret_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveReadingPositionRequest) Reset() {
	*x = SaveReadingPositionRequest{}
	mi := &file_document_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveReadingPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveReadingPositionRequest) ProtoMessage() {}

func (x *SaveReadingPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveReadingPositionRequest.ProtoReflect.Descriptor instead.
func (*SaveReadingPositionRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{36}
}

func (x *SaveReadingPositionRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *SaveReadingPositionRequest) GetBlockId() string {
	if x != nil && x.BlockId != nil {
		return *x.BlockId
	}
	return ""
}

func (x *SaveReadingPositionRequest) GetCaretStart() int32 {
	if x != nil {
		return x.CaretStart
	}
	return 0
}

func (x *SaveReadingPositionRequest) GetCaretEnd() int32 {
	if x != nil {
		return x.CaretEnd
	}
	return 0
}

type ListReadingPositionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReadingPositionsRequest) Reset() {
	*x = ListReadingPositionsRequest{}
	mi := &file_document_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReadingPositionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReadingPositionsRequest) ProtoMessage() {}

func (x *ListReadingPositionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReadingPositionsRequest.ProtoReflect.Descriptor instead.
func (*ListReadingPositionsRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{37}
}

func (x *ListReadingPositionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListReadingPositionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []*ReadingPosition     `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReadingPositionsResponse) Reset() {
	*x = ListReadingPositionsResponse{}
	mi := &file_document_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReadingPositionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReadingPositionsResponse) ProtoMessage() {}

func (x *ListReadingPositionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReadingPositionsResponse.ProtoReflect.Descriptor instead.
func (*ListReadingPositionsResponse) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{38}
}

func (x *ListReadingPositionsResponse) GetPositions() []*ReadingPosition {
	if x != nil {
		return x.Positions
	}
	return nil
}

type ReadingPosition struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	PageId     string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	PageTitle  string                 `protobuf:"bytes,2,opt,name=page_title,json=pageTitle,proto3" json:"page_title,omitempty"`
	BlockId    *string                `protobuf:"bytes,3,opt,name=block_id,json=blockId,proto3,oneof" json:"block_id,omitempty"`
	CaretStart int32                  `protobuf:"varint,4,opt,name=caret_start,json=caretStart,proto3" json:"caret_start,omitempty"`
	CaretEnd   int32                  `protobuf:"varint,5,opt,name=caret_end,json=caretEnd,proto3" json:"caret_end,omitempty"`
	UpdatedAt  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// The page's topic, so the resume card can draw its chip without a second
	// round trip per card.
	Topic         *Topic `protobuf:"bytes,7,opt,name=topic,proto3,oneof" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadingPosition) Reset() {
	*x = ReadingPosition{}
	mi := &file_document_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadingPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadingPosition) ProtoMessage() {}

func (x *ReadingPosition) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadingPosition.ProtoReflect.Descriptor instead.
func (*ReadingPosition) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{39}
}

func (x *ReadingPosition) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *ReadingPosition) GetPageTitle() string {
	if x != nil {
		return x.PageTitle
	}
	return ""
}

func (x *ReadingPosition) GetBlockId() string {
	if x != nil && x.BlockId != nil {
		return *x.BlockId
	}
	return ""
}

func (x *ReadingPosition) GetCaretStart() int32 {
	if x != nil {
		return x.CaretStart
	}
	return 0
}

func (x *ReadingPosition) GetCaretEnd() int32 {
	if x != nil {
		return x.CaretEnd
	}
	return 0
}

func (x *ReadingPosition) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ReadingPosition) GetTopic() *Topic {
	if x != nil {
		return x.Topic
	}
	return nil
}

var File_document_proto protoreflect.FileDescriptor

const file_document_proto_rawDesc = "" +
	"\n" +
	"\x0edocument.proto\x12\x14marginal.document.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xd4\x04\n" +
	"\x04Page\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_by\x18\x02 \x01(\tR\tcreatedBy\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\tparent_id\x18\x04 \x01(\tH\x00R\bparentId\x88\x01\x01\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12\x19\n" +
	"\bsort_key\x18\x06 \x01(\tR\asortKey\x12M\n" +
	"\x0flifecycle_state\x18\a \x01(\x0e2$.marginal.document.v1.LifecycleStateR\x0elifecycleState\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12>\n" +
	"\n" +
	"deleted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampH\x01R\tdeletedAt\x88\x01\x01\x126\n" +
	"\x05topic\x18\v \x01(\v2\x1b.marginal.document.v1.TopicH\x02R\x05topic\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\f \x03(\tR\x04tags\x12\x1f\n" +
	"\vblock_count\x18\r \x01(\x05R\n" +
	"blockCount\x12\x1d\n" +
	"\n" +
	"word_count\x18\x0e \x01(\x05R\twordCountB\f\n" +
	"\n" +
	"_parent_idB\r\n" +
	"\v_deleted_atB\b\n" +
	"\x06_topic\"g\n" +
	"\x05Topic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tcolor_key\x18\x03 \x01(\tR\bcolorKey\x12\x1d\n" +
	"\n" +
	"page_count\x18\x04 \x01(\x05R\tpageCount\"/\n" +
	"\x14GetPageSeriesRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\"\xc8\x01\n" +
	"\n" +
	"SeriesPart\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06number\x18\x03 \x01(\x05R\x06number\x12\x1d\n" +
	"\n" +
	"word_count\x18\x04 \x01(\x05R\twordCount\x126\n" +
	"\x05topic\x18\x05 \x01(\v2\x1b.marginal.document.v1.TopicH\x00R\x05topic\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tagsB\b\n" +
	"\x06_topic\"\xe7\x01\n" +
	"\n" +
	"PageSeries\x12@\n" +
	"\n" +
	"membership\x18\x01 \x01(\x0e2 .marginal.document.v1.MembershipR\n" +
	"membership\x12$\n" +
	"\x0eseries_page_id\x18\x02 \x01(\tR\fseriesPageId\x12!\n" +
	"\fseries_title\x18\x03 \x01(\tR\vseriesTitle\x126\n" +
	"\x05parts\x18\x04 \x03(\v2 .marginal.document.v1.SeriesPartR\x05parts\x12\x16\n" +
	"\x06number\x18\x05 \x01(\x05R\x06number\"\x13\n" +
	"\x11ListSeriesRequest\"\x83\x02\n" +
	"\rSeriesSummary\x12$\n" +
	"\x0eseries_page_id\x18\x01 \x01(\tR\fseriesPageId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x126\n" +
	"\x05topic\x18\x03 \x01(\v2\x1b.marginal.document.v1.TopicH\x00R\x05topic\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"part_count\x18\x04 \x01(\x05R\tpartCount\x12\x1d\n" +
	"\n" +
	"word_count\x18\x05 \x01(\x05R\twordCount\x126\n" +
	"\x05parts\x18\x06 \x03(\v2 .marginal.document.v1.SeriesPartR\x05partsB\b\n" +
	"\x06_topic\"Q\n" +
	"\x12ListSeriesResponse\x12;\n" +
	"\x06series\x18\x01 \x03(\v2#.marginal.document.v1.SeriesSummaryR\x06series\"~\n" +
	"\x11CreatePageRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\tparent_id\x18\x02 \x01(\tH\x00R\bparentId\x88\x01\x01\x12\x19\n" +
	"\x05after\x18\x03 \x01(\tH\x01R\x05after\x88\x01\x01B\f\n" +
	"\n" +
	"_parent_idB\b\n" +
	"\x06_after\" \n" +
	"\x0eGetPageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x8c\x01\n" +
	"\x10ListPagesRequest\x12 \n" +
	"\tparent_id\x18\x01 \x01(\tH\x00R\bparentId\x88\x01\x01\x12\x19\n" +
	"\x05after\x18\x02 \x01(\tH\x01R\x05after\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x03 \x01(\x05H\x02R\x05limit\x88\x01\x01B\f\n" +
	"\n" +
	"_parent_idB\b\n" +
	"\x06_afterB\b\n" +
	"\x06_limit\"{\n" +
	"\x11ListPagesResponse\x120\n" +
	"\x05pages\x18\x01 \x03(\v2\x1a.marginal.document.v1.PageR\x05pages\x12$\n" +
	"\vnext_cursor\x18\x02 \x01(\tH\x00R\n" +
	"nextCursor\x88\x01\x01B\x0e\n" +
	"\f_next_cursor\"9\n" +
	"\x11RenamePageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"z\n" +
	"\x13ReparentPageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\tparent_id\x18\x02 \x01(\tH\x00R\bparentId\x88\x01\x01\x12\x19\n" +
	"\x05after\x18\x03 \x01(\tH\x01R\x05after\x88\x01\x01B\f\n" +
	"\n" +
	"_parent_idB\b\n" +
	"\x06_after\"#\n" +
	"\x11DeletePageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"/\n" +
	"\x14ListBacklinksRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\"U\n" +
	"\x15ListBacklinksResponse\x12<\n" +
	"\tbacklinks\x18\x01 \x03(\v2\x1e.marginal.document.v1.BacklinkR\tbacklinks\"\x9e\x01\n" +
	"\bBacklink\x12\x1b\n" +
	"\tfrom_page\x18\x01 \x01(\tR\bfromPage\x12&\n" +
	"\x0ffrom_page_title\x18\x02 \x01(\tR\rfromPageTitle\x12*\n" +
	"\x11from_page_deleted\x18\x03 \x01(\bR\x0ffromPageDeleted\x12!\n" +
	"\ftarget_title\x18\x04 \x01(\tR\vtargetTitle\",\n" +
	"\x11ListBlocksRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\"I\n" +
	"\x12ListBlocksResponse\x123\n" +
	"\x06blocks\x18\x01 \x03(\v2\x1b.marginal.document.v1.BlockR\x06blocks\"\x87\x01\n" +
	"\x05Block\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\tparent_id\x18\x02 \x01(\tH\x00R\bparentId\x88\x01\x01\x12\x1b\n" +
	"\tkind_json\x18\x03 \x01(\tR\bkindJson\x12!\n" +
	"\fcontent_json\x18\x04 \x01(\tR\vcontentJsonB\f\n" +
	"\n" +
	"_parent_id\"&\n" +
	"\x14PreviewDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xb0\x01\n" +
	"\x15PreviewDeleteResponse\x12<\n" +
	"\vdescendants\x18\x01 \x03(\v2\x1a.marginal.document.v1.PageR\vdescendants\x128\n" +
	"\treferrers\x18\x02 \x03(\v2\x1a.marginal.document.v1.PageR\treferrers\x12\x1f\n" +
	"\vblock_count\x18\x03 \x01(\x05R\n" +
	"blockCount\"@\n" +
	"\x10ListTrashRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"e\n" +
	"\x11ListTrashResponse\x12:\n" +
	"\aentries\x18\x01 \x03(\v2 .marginal.document.v1.TrashEntryR\aentries\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xc5\x01\n" +
	"\n" +
	"TrashEntry\x12.\n" +
	"\x04page\x18\x01 \x01(\v2\x1a.marginal.document.v1.PageR\x04page\x125\n" +
	"\bpurge_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\apurgeAt\x12C\n" +
	"\bprogress\x18\x03 \x01(\v2\".marginal.document.v1.SagaProgressH\x00R\bprogress\x88\x01\x01B\v\n" +
	"\t_progress\"\xc2\x01\n" +
	"\fSagaProgress\x12\x1d\n" +
	"\n" +
	"steps_done\x18\x01 \x03(\tR\tstepsDone\x12\x1d\n" +
	"\n" +
	"steps_left\x18\x02 \x03(\tR\tstepsLeft\x12\x1a\n" +
	"\battempts\x18\x03 \x01(\x05R\battempts\x12\"\n" +
	"\n" +
	"last_error\x18\x04 \x01(\tH\x00R\tlastError\x88\x01\x01\x12%\n" +
	"\x0enot_applicable\x18\x05 \x03(\tR\rnotApplicableB\r\n" +
	"\v_last_error\"$\n" +
	"\x12RestorePageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x13\n" +
	"\x11ListTopicsRequest\"r\n" +
	"\x12ListTopicsResponse\x123\n" +
	"\x06topics\x18\x01 \x03(\v2\x1b.marginal.document.v1.TopicR\x06topics\x12'\n" +
	"\x0funtopiced_pages\x18\x02 \x01(\x05R\x0euntopicedPages\"[\n" +
	"\x13SetPageTopicRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12\x1e\n" +
	"\btopic_id\x18\x02 \x01(\tH\x00R\atopicId\x88\x01\x01B\v\n" +
	"\t_topic_id\">\n" +
	"\x11AddPageTagRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\"A\n" +
	"\x14RemovePageTagRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\",\n" +
	"\x14ListTagFacetsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"O\n" +
	"\x15ListTagFacetsResponse\x126\n" +
	"\x06facets\x18\x01 \x03(\v2\x1e.marginal.document.v1.TagFacetR\x06facets\"b\n" +
	"\bTagFacet\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x1d\n" +
	"\n" +
	"page_count\x18\x02 \x01(\x05R\tpageCount\x12%\n" +
	"\x0etopics_spanned\x18\x03 \x01(\x05R\rtopicsSpanned\"\xa0\x01\n" +
	"\x1aSaveReadingPositionRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12\x1e\n" +
	"\bblock_id\x18\x02 \x01(\tH\x00R\ablockId\x88\x01\x01\x12\x1f\n" +
	"\vcaret_start\x18\x03 \x01(\x05R\n" +
	"caretStart\x12\x1b\n" +
	"\tcaret_end\x18\x04 \x01(\x05R\bcaretEndB\v\n" +
	"\t_block_id\"3\n" +
	"\x1bListReadingPositionsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"c\n" +
	"\x1cListReadingPositionsResponse\x12C\n" +
	"\tpositions\x18\x01 \x03(\v2%.marginal.document.v1.ReadingPositionR\tpositions\"\xb1\x02\n" +
	"\x0fReadingPosition\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12\x1d\n" +
	"\n" +
	"page_title\x18\x02 \x01(\tR\tpageTitle\x12\x1e\n" +
	"\bblock_id\x18\x03 \x01(\tH\x00R\ablockId\x88\x01\x01\x12\x1f\n" +
	"\vcaret_start\x18\x04 \x01(\x05R\n" +
	"caretStart\x12\x1b\n" +
	"\tcaret_end\x18\x05 \x01(\x05R\bcaretEnd\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x126\n" +
	"\x05topic\x18\a \x01(\v2\x1b.marginal.document.v1.TopicH\x01R\x05topic\x88\x01\x01B\v\n" +
	"\t_block_idB\b\n" +
	"\x06_topic*\x88\x01\n" +
	"\x0eLifecycleState\x12\x1f\n" +
	"\x1bLIFECYCLE_STATE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16LIFECYCLE_STATE_ACTIVE\x10\x01\x12\x1c\n" +
	"\x18LIFECYCLE_STATE_DELETING\x10\x02\x12\x1b\n" +
	"\x17LIFECYCLE_STATE_DELETED\x10\x03*k\n" +
	"\n" +
	"Membership\x12\x1a\n" +
	"\x16MEMBERSHIP_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fMEMBERSHIP_NONE\x10\x01\x12\x15\n" +
	"\x11MEMBERSHIP_MEMBER\x10\x02\x12\x15\n" +
	"\x11MEMBERSHIP_LEADER\x10\x032\xda\x0e\n" +
	"\vPageService\x12Q\n" +
	"\n" +
	"CreatePage\x12'.marginal.document.v1.CreatePageRequest\x1a\x1a.marginal.document.v1.Page\x12K\n" +
	"\aGetPage\x12$.marginal.document.v1.GetPageRequest\x1a\x1a.marginal.document.v1.Page\x12\\\n" +
	"\tListPages\x12&.marginal.document.v1.ListPagesRequest\x1a'.marginal.document.v1.ListPagesResponse\x12Q\n" +
	"\n" +
	"RenamePage\x12'.marginal.document.v1.RenamePageRequest\x1a\x1a.marginal.document.v1.Page\x12U\n" +
	"\fReparentPage\x12).marginal.document.v1.ReparentPageRequest\x1a\x1a.marginal.document.v1.Page\x12M\n" +
	"\n" +
	"DeletePage\x12'.marginal.document.v1.DeletePageRequest\x1a\x16.google.protobuf.Empty\x12h\n" +
	"\rListBacklinks\x12*.marginal.document.v1.ListBacklinksRequest\x1a+.marginal.document.v1.ListBacklinksResponse\x12_\n" +
	"\n" +
	"ListBlocks\x12'.marginal.document.v1.ListBlocksRequest\x1a(.marginal.document.v1.ListBlocksResponse\x12h\n" +
	"\rPreviewDelete\x12*.marginal.document.v1.PreviewDeleteRequest\x1a+.marginal.document.v1.PreviewDeleteResponse\x12\\\n" +
	"\tListTrash\x12&.marginal.document.v1.ListTrashRequest\x1a'.marginal.document.v1.ListTrashResponse\x12S\n" +
	"\vRestorePage\x12(.marginal.document.v1.RestorePageRequest\x1a\x1a.marginal.document.v1.Page\x12_\n" +
	"\n" +
	"ListTopics\x12'.marginal.document.v1.ListTopicsRequest\x1a(.marginal.document.v1.ListTopicsResponse\x12U\n" +
	"\fSetPageTopic\x12).marginal.document.v1.SetPageTopicRequest\x1a\x1a.marginal.document.v1.Page\x12Q\n" +
	"\n" +
	"AddPageTag\x12'.marginal.document.v1.AddPageTagRequest\x1a\x1a.marginal.document.v1.Page\x12W\n" +
	"\rRemovePageTag\x12*.marginal.document.v1.RemovePageTagRequest\x1a\x1a.marginal.document.v1.Page\x12h\n" +
	"\rListTagFacets\x12*.marginal.document.v1.ListTagFacetsRequest\x1a+.marginal.document.v1.ListTagFacetsResponse\x12_\n" +
	"\x13SaveReadingPosition\x120.marginal.document.v1.SaveReadingPositionRequest\x1a\x16.google.protobuf.Empty\x12}\n" +
	"\x14ListReadingPositions\x121.marginal.document.v1.ListReadingPositionsRequest\x1a2.marginal.document.v1.ListReadingPositionsResponse\x12]\n" +
	"\rGetPageSeries\x12*.marginal.document.v1.GetPageSeriesRequest\x1a .marginal.document.v1.PageSeries\x12_\n" +
	"\n" +
	"ListSeries\x12'.marginal.document.v1.ListSeriesRequest\x1a(.marginal.document.v1.ListSeriesResponseB/Z-marginal/document-service/genproto/documentv1b\x06proto3"

var (
	file_document_proto_rawDescOnce sync.Once
	file_document_proto_rawDescData []byte
)

func file_document_proto_rawDescGZIP() []byte {
	file_document_proto_rawDescOnce.Do(func() {
		file_document_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_document_proto_rawDesc), len(file_document_proto_rawDesc)))
	})
	return file_document_proto_rawDescData
}

var file_document_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_document_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_document_proto_goTypes = []any{
	(LifecycleState)(0),                  // 0: marginal.document.v1.LifecycleState
	(Membership)(0),                      // 1: marginal.document.v1.Membership
	(*Page)(nil),                         // 2: marginal.document.v1.Page
	(*Topic)(nil),                        // 3: marginal.document.v1.Topic
	(*GetPageSeriesRequest)(nil),         // 4: marginal.document.v1.GetPageSeriesRequest
	(*SeriesPart)(nil),                   // 5: marginal.document.v1.SeriesPart
	(*PageSeries)(nil),                   // 6: marginal.document.v1.PageSeries
	(*ListSeriesRequest)(nil),            // 7: marginal.document.v1.ListSeriesRequest
	(*SeriesSummary)(nil),                // 8: marginal.document.v1.SeriesSummary
	(*ListSeriesResponse)(nil),           // 9: marginal.document.v1.ListSeriesResponse
	(*CreatePageRequest)(nil),            // 10: marginal.document.v1.CreatePageRequest
	(*GetPageRequest)(nil),               // 11: marginal.document.v1.GetPageRequest
	(*ListPagesRequest)(nil),             // 12: marginal.document.v1.ListPagesRequest
	(*ListPagesResponse)(nil),            // 13: marginal.document.v1.ListPagesResponse
	(*RenamePageRequest)(nil),            // 14: marginal.document.v1.RenamePageRequest
	(*ReparentPageRequest)(nil),          // 15: marginal.document.v1.ReparentPageRequest
	(*DeletePageRequest)(nil),            // 16: marginal.document.v1.DeletePageRequest
	(*ListBacklinksRequest)(nil),         // 17: marginal.document.v1.ListBacklinksRequest
	(*ListBacklinksResponse)(nil),        // 18: marginal.document.v1.ListBacklinksResponse
	(*Backlink)(nil),                     // 19: marginal.document.v1.Backlink
	(*ListBlocksRequest)(nil),            // 20: marginal.document.v1.ListBlocksRequest
	(*ListBlocksResponse)(nil),           // 21: marginal.document.v1.ListBlocksResponse
	(*Block)(nil),                        // 22: marginal.document.v1.Block
	(*PreviewDeleteRequest)(nil),         // 23: marginal.document.v1.PreviewDeleteRequest
	(*PreviewDeleteResponse)(nil),        // 24: marginal.document.v1.PreviewDeleteResponse
	(*ListTrashRequest)(nil),             // 25: marginal.document.v1.ListTrashRequest
	(*ListTrashResponse)(nil),            // 26: marginal.document.v1.ListTrashResponse
	(*TrashEntry)(nil),                   // 27: marginal.document.v1.TrashEntry
	(*SagaProgress)(nil),                 // 28: marginal.document.v1.SagaProgress
	(*RestorePageRequest)(nil),           // 29: marginal.document.v1.RestorePageRequest
	(*ListTopicsRequest)(nil),            // 30: marginal.document.v1.ListTopicsRequest
	(*ListTopicsResponse)(nil),           // 31: marginal.document.v1.ListTopicsResponse
	(*SetPageTopicRequest)(nil),          // 32: marginal.document.v1.SetPageTopicRequest
	(*AddPageTagRequest)(nil),            // 33: marginal.document.v1.AddPageTagRequest
	(*RemovePageTagRequest)(nil),         // 34: marginal.document.v1.RemovePageTagRequest
	(*ListTagFacetsRequest)(nil),         // 35: marginal.document.v1.ListTagFacetsRequest
	(*ListTagFacetsResponse)(nil),        // 36: marginal.document.v1.ListTagFacetsResponse
	(*TagFacet)(nil),                     // 37: marginal.document.v1.TagFacet
	(*SaveReadingPositionRequest)(nil),   // 38: marginal.document.v1.SaveReadingPositionRequest
	(*ListReadingPositionsRequest)(nil),  // 39: marginal.document.v1.ListReadingPositionsRequest
	(*ListReadingPositionsResponse)(nil), // 40: marginal.document.v1.ListReadingPositionsResponse
	(*ReadingPosition)(nil),              // 41: marginal.document.v1.ReadingPosition
	(*timestamppb.Timestamp)(nil),        // 42: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                // 43: google.protobuf.Empty
}
var file_document_proto_depIdxs = []int32{
	0,  // 0: marginal.document.v1.Page.lifecycle_state:type_name -> marginal.document.v1.LifecycleState
	42, // 1: marginal.document.v1.Page.created_at:type_name -> google.protobuf.Timestamp
	42, // 2: marginal.document.v1.Page.updated_at:type_name -> google.protobuf.Timestamp
	42, // 3: marginal.document.v1.Page.deleted_at:type_name -> google.protobuf.Timestamp
	3,  // 4: marginal.document.v1.Page.topic:type_name -> marginal.document.v1.Topic
	3,  // 5: marginal.document.v1.SeriesPart.topic:type_name -> marginal.document.v1.Topic
	1,  // 6: marginal.document.v1.PageSeries.membership:type_name -> marginal.document.v1.Membership
	5,  // 7: marginal.document.v1.PageSeries.parts:type_name -> marginal.document.v1.SeriesPart
	3,  // 8: marginal.document.v1.SeriesSummary.topic:type_name -> marginal.document.v1.Topic
	5,  // 9: marginal.document.v1.SeriesSummary.parts:type_name -> marginal.document.v1.SeriesPart
	8,  // 10: marginal.document.v1.ListSeriesResponse.series:type_name -> marginal.document.v1.SeriesSummary
	2,  // 11: marginal.document.v1.ListPagesResponse.pages:type_name -> marginal.document.v1.Page
	19, // 12: marginal.document.v1.ListBacklinksResponse.backlinks:type_name -> marginal.document.v1.Backlink
	22, // 13: marginal.document.v1.ListBlocksResponse.blocks:type_name -> marginal.document.v1.Block
	2,  // 14: marginal.document.v1.PreviewDeleteResponse.descendants:type_name -> marginal.document.v1.Page
	2,  // 15: marginal.document.v1.PreviewDeleteResponse.referrers:type_name -> marginal.document.v1.Page
	27, // 16: marginal.document.v1.ListTrashResponse.entries:type_name -> marginal.document.v1.TrashEntry
	2,  // 17: marginal.document.v1.TrashEntry.page:type_name -> marginal.document.v1.Page
	42, // 18: marginal.document.v1.TrashEntry.purge_at:type_name -> google.protobuf.Timestamp
	28, // 19: marginal.document.v1.TrashEntry.progress:type_name -> marginal.document.v1.SagaProgress
	3,  // 20: marginal.document.v1.ListTopicsResponse.topics:type_name -> marginal.document.v1.Topic
	37, // 21: marginal.document.v1.ListTagFacetsResponse.facets:type_name -> marginal.document.v1.TagFacet
	41, // 22: marginal.document.v1.ListReadingPositionsResponse.positions:type_name -> marginal.document.v1.ReadingPosition
	42, // 23: marginal.document.v1.ReadingPosition.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 24: marginal.document.v1.ReadingPosition.topic:type_name -> marginal.document.v1.Topic
	10, // 25: marginal.document.v1.PageService.CreatePage:input_type -> marginal.document.v1.CreatePageRequest
	11, // 26: marginal.document.v1.PageService.GetPage:input_type -> marginal.document.v1.GetPageRequest
	12, // 27: marginal.document.v1.PageService.ListPages:input_type -> marginal.document.v1.ListPagesRequest
	14, // 28: marginal.document.v1.PageService.RenamePage:input_type -> marginal.document.v1.RenamePageRequest
	15, // 29: marginal.document.v1.PageService.ReparentPage:input_type -> marginal.document.v1.ReparentPageRequest
	16, // 30: marginal.document.v1.PageService.DeletePage:input_type -> marginal.document.v1.DeletePageRequest
	17, // 31: marginal.document.v1.PageService.ListBacklinks:input_type -> marginal.document.v1.ListBacklinksRequest
	20, // 32: marginal.document.v1.PageService.ListBlocks:input_type -> marginal.document.v1.ListBlocksRequest
	23, // 33: marginal.document.v1.PageService.PreviewDelete:input_type -> marginal.document.v1.PreviewDeleteRequest
	25, // 34: marginal.document.v1.PageService.ListTrash:input_type -> marginal.document.v1.ListTrashRequest
	29, // 35: marginal.document.v1.PageService.RestorePage:input_type -> marginal.document.v1.RestorePageRequest
	30, // 36: marginal.document.v1.PageService.ListTopics:input_type -> marginal.document.v1.ListTopicsRequest
	32, // 37: marginal.document.v1.PageService.SetPageTopic:input_type -> marginal.document.v1.SetPageTopicRequest
	33, // 38: marginal.document.v1.PageService.AddPageTag:input_type -> marginal.document.v1.AddPageTagRequest
	34, // 39: marginal.document.v1.PageService.RemovePageTag:input_type -> marginal.document.v1.RemovePageTagRequest
	35, // 40: marginal.document.v1.PageService.ListTagFacets:input_type -> marginal.document.v1.ListTagFacetsRequest
	38, // 41: marginal.document.v1.PageService.SaveReadingPosition:input_type -> marginal.document.v1.SaveReadingPositionRequest
	39, // 42: marginal.document.v1.PageService.ListReadingPositions:input_type -> marginal.document.v1.ListReadingPositionsRequest
	4,  // 43: marginal.document.v1.PageService.GetPageSeries:input_type -> marginal.document.v1.GetPageSeriesRequest
	7,  // 44: marginal.document.v1.PageService.ListSeries:input_type -> marginal.document.v1.ListSeriesRequest
	2,  // 45: marginal.document.v1.PageService.CreatePage:output_type -> marginal.document.v1.Page
	2,  // 46: marginal.document.v1.PageService.GetPage:output_type -> marginal.document.v1.Page
	13, // 47: marginal.document.v1.PageService.ListPages:output_type -> marginal.document.v1.ListPagesResponse
	2,  // 48: marginal.document.v1.PageService.RenamePage:output_type -> marginal.document.v1.Page
	2,  // 49: marginal.document.v1.PageService.ReparentPage:output_type -> marginal.document.v1.Page
	43, // 50: marginal.document.v1.PageService.DeletePage:output_type -> google.protobuf.Empty
	18, // 51: marginal.document.v1.PageService.ListBacklinks:output_type -> marginal.document.v1.ListBacklinksResponse
	21, // 52: marginal.document.v1.PageService.ListBlocks:output_type -> marginal.document.v1.ListBlocksResponse
	24, // 53: marginal.document.v1.PageService.PreviewDelete:output_type -> marginal.document.v1.PreviewDeleteResponse
	26, // 54: marginal.document.v1.PageService.ListTrash:output_type -> marginal.document.v1.ListTrashResponse
	2,  // 55: marginal.document.v1.PageService.RestorePage:output_type -> marginal.document.v1.Page
	31, // 56: marginal.document.v1.PageService.ListTopics:output_type -> marginal.document.v1.ListTopicsResponse
	2,  // 57: marginal.document.v1.PageService.SetPageTopic:output_type -> marginal.document.v1.Page
	2,  // 58: marginal.document.v1.PageService.AddPageTag:output_type -> marginal.document.v1.Page
	2,  // 59: marginal.document.v1.PageService.RemovePageTag:output_type -> marginal.document.v1.Page
	36, // 60: marginal.document.v1.PageService.ListTagFacets:output_type -> marginal.document.v1.ListTagFacetsResponse
	43, // 61: marginal.document.v1.PageService.SaveReadingPosition:output_type -> google.protobuf.Empty
	40, // 62: marginal.document.v1.PageService.ListReadingPositions:output_type -> marginal.document.v1.ListReadingPositionsResponse
	6,  // 63: marginal.document.v1.PageService.GetPageSeries:output_type -> marginal.document.v1.PageSeries
	9,  // 64: marginal.document.v1.PageService.ListSeries:output_type -> marginal.document.v1.ListSeriesResponse
	45, // [45:65] is the sub-list for method output_type
	25, // [25:45] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_document_proto_init() }
func file_document_proto_init() {
	if File_document_proto != nil {
		return
	}
	file_document_proto_msgTypes[0].OneofWrappers = []any{}
	file_document_proto_msgTypes[3].OneofWrappers = []any{}
	file_document_proto_msgTypes[6].OneofWrappers = []any{}
	file_document_proto_msgTypes[8].OneofWrappers = []any{}
	file_document_proto_msgTypes[10].OneofWrappers = []any{}
	file_document_proto_msgTypes[11].OneofWrappers = []any{}
	file_document_proto_msgTypes[13].OneofWrappers = []any{}
	file_document_proto_msgTypes[20].OneofWrappers = []any{}
	file_document_proto_msgTypes[25].OneofWrappers = []any{}
	file_document_proto_msgTypes[26].OneofWrappers = []any{}
	file_document_proto_msgTypes[30].OneofWrappers = []any{}
	file_document_proto_msgTypes[36].OneofWrappers = []any{}
	file_document_proto_msgTypes[39].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_document_proto_rawDesc), len(file_document_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_document_proto_goTypes,
		DependencyIndexes: file_document_proto_depIdxs,
		EnumInfos:         file_document_proto_enumTypes,
		MessageInfos:      file_document_proto_msgTypes,
	}.Build()
	File_document_proto = out.File
	file_document_proto_goTypes = nil
	file_document_proto_depIdxs = nil
}
