// PageService — the gRPC contract for page metadata (create/get/list/
// rename/reparent/delete). See docs/api/pages.md, which this file matches
// field-for-field — that doc is the source of truth for semantics; this
// file is its wire encoding.
//
// This is deliberately NOT where block content changes go — those are
// documentcore Ops (services/document-service/internal/documentcore),
// applied through a separate surface once one exists. PageService only
// owns the page row: title, tree position, lifecycle.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.0
// source: document.proto

package documentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LifecycleState int32

const (
	LifecycleState_LIFECYCLE_STATE_UNSPECIFIED LifecycleState = 0
	LifecycleState_LIFECYCLE_STATE_ACTIVE      LifecycleState = 1
	LifecycleState_LIFECYCLE_STATE_DELETING    LifecycleState = 2
	LifecycleState_LIFECYCLE_STATE_DELETED     LifecycleState = 3
)

// Enum value maps for LifecycleState.
var (
	LifecycleState_name = map[int32]string{
		0: "LIFECYCLE_STATE_UNSPECIFIED",
		1: "LIFECYCLE_STATE_ACTIVE",
		2: "LIFECYCLE_STATE_DELETING",
		3: "LIFECYCLE_STATE_DELETED",
	}
	LifecycleState_value = map[string]int32{
		"LIFECYCLE_STATE_UNSPECIFIED": 0,
		"LIFECYCLE_STATE_ACTIVE":      1,
		"LIFECYCLE_STATE_DELETING":    2,
		"LIFECYCLE_STATE_DELETED":     3,
	}
)

func (x LifecycleState) Enum() *LifecycleState {
	p := new(LifecycleState)
	*p = x
	return p
}

func (x LifecycleState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LifecycleState) Descriptor() protoreflect.EnumDescriptor {
	return file_document_proto_enumTypes[0].Descriptor()
}

func (LifecycleState) Type() protoreflect.EnumType {
	return &file_document_proto_enumTypes[0]
}

func (x LifecycleState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LifecycleState.Descriptor instead.
func (LifecycleState) EnumDescriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{0}
}

type Page struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUIDv7
	CreatedBy      string                 `protobuf:"bytes,2,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Title          string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	ParentId       *string                `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	Path           string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`                      // materialised LTREE ancestry
	SortKey        string                 `protobuf:"bytes,6,opt,name=sort_key,json=sortKey,proto3" json:"sort_key,omitempty"` // opaque, lexicographic
	LifecycleState LifecycleState         `protobuf:"varint,7,opt,name=lifecycle_state,json=lifecycleState,proto3,enum=marginal.document.v1.LifecycleState" json:"lifecycle_state,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_document_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{0}
}

func (x *Page) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Page) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Page) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Page) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

func (x *Page) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Page) GetSortKey() string {
	if x != nil {
		return x.SortKey
	}
	return ""
}

func (x *Page) GetLifecycleState() LifecycleState {
	if x != nil {
		return x.LifecycleState
	}
	return LifecycleState_LIFECYCLE_STATE_UNSPECIFIED
}

func (x *Page) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Page) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Page) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type CreatePageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	ParentId      *string                `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	After         *string                `protobuf:"bytes,3,opt,name=after,proto3,oneof" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePageRequest) Reset() {
	*x = CreatePageRequest{}
	mi := &file_document_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePageRequest) ProtoMessage() {}

func (x *CreatePageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePageRequest.ProtoReflect.Descriptor instead.
func (*CreatePageRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePageRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePageRequest) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

func (x *CreatePageRequest) GetAfter() string {
	if x != nil && x.After != nil {
		return *x.After
	}
	return ""
}

type GetPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPageRequest) Reset() {
	*x = GetPageRequest{}
	mi := &file_document_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPageRequest) ProtoMessage() {}

func (x *GetPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPageRequest.ProtoReflect.Descriptor instead.
func (*GetPageRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{2}
}

func (x *GetPageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListPagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentId      *string                `protobuf:"bytes,1,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	After         *string                `protobuf:"bytes,2,opt,name=after,proto3,oneof" json:"after,omitempty"`
	Limit         *int32                 `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPagesRequest) Reset() {
	*x = ListPagesRequest{}
	mi := &file_document_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPagesRequest) ProtoMessage() {}

func (x *ListPagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPagesRequest.ProtoReflect.Descriptor instead.
func (*ListPagesRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{3}
}

func (x *ListPagesRequest) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

func (x *ListPagesRequest) GetAfter() string {
	if x != nil && x.After != nil {
		return *x.After
	}
	return ""
}

func (x *ListPagesRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type ListPagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pages         []*Page                `protobuf:"bytes,1,rep,name=pages,proto3" json:"pages,omitempty"`
	NextCursor    *string                `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3,oneof" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPagesResponse) Reset() {
	*x = ListPagesResponse{}
	mi := &file_document_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPagesResponse) ProtoMessage() {}

func (x *ListPagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPagesResponse.ProtoReflect.Descriptor instead.
func (*ListPagesResponse) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{4}
}

func (x *ListPagesResponse) GetPages() []*Page {
	if x != nil {
		return x.Pages
	}
	return nil
}

func (x *ListPagesResponse) GetNextCursor() string {
	if x != nil && x.NextCursor != nil {
		return *x.NextCursor
	}
	return ""
}

type RenamePageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenamePageRequest) Reset() {
	*x = RenamePageRequest{}
	mi := &file_document_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenamePageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenamePageRequest) ProtoMessage() {}

func (x *RenamePageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenamePageRequest.ProtoReflect.Descriptor instead.
func (*RenamePageRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{5}
}

func (x *RenamePageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RenamePageRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type ReparentPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId      *string                `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	After         *string                `protobuf:"bytes,3,opt,name=after,proto3,oneof" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReparentPageRequest) Reset() {
	*x = ReparentPageRequest{}
	mi := &file_document_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReparentPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReparentPageRequest) ProtoMessage() {}

func (x *ReparentPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReparentPageRequest.ProtoReflect.Descriptor instead.
func (*ReparentPageRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{6}
}

func (x *ReparentPageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReparentPageRequest) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

func (x *ReparentPageRequest) GetAfter() string {
	if x != nil && x.After != nil {
		return *x.After
	}
	return ""
}

type DeletePageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePageRequest) Reset() {
	*x = DeletePageRequest{}
	mi := &file_document_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePageRequest) ProtoMessage() {}

func (x *DeletePageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePageRequest.ProtoReflect.Descriptor instead.
func (*DeletePageRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_document_proto protoreflect.FileDescriptor

const file_document_proto_rawDesc = "" +
	"\n" +
	"\x0edocument.proto\x12\x14marginal.document.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xbe\x03\n" +
	"\x04Page\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_by\x18\x02 \x01(\tR\tcreatedBy\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\tparent_id\x18\x04 \x01(\tH\x00R\bparentId\x88\x01\x01\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12\x19\n" +
	"\bsort_key\x18\x06 \x01(\tR\asortKey\x12M\n" +
	"\x0flifecycle_state\x18\a \x01(\x0e2$.marginal.document.v1.LifecycleStateR\x0elifecycleState\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12>\n" +
	"\n" +
	"deleted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampH\x01R\tdeletedAt\x88\x01\x01B\f\n" +
	"\n" +
	"_parent_idB\r\n" +
	"\v_deleted_at\"~\n" +
	"\x11CreatePageRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\tparent_id\x18\x02 \x01(\tH\x00R\bparentId\x88\x01\x01\x12\x19\n" +
	"\x05after\x18\x03 \x01(\tH\x01R\x05after\x88\x01\x01B\f\n" +
	"\n" +
	"_parent_idB\b\n" +
	"\x06_after\" \n" +
	"\x0eGetPageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x8c\x01\n" +
	"\x10ListPagesRequest\x12 \n" +
	"\tparent_id\x18\x01 \x01(\tH\x00R\bparentId\x88\x01\x01\x12\x19\n" +
	"\x05after\x18\x02 \x01(\tH\x01R\x05after\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x03 \x01(\x05H\x02R\x05limit\x88\x01\x01B\f\n" +
	"\n" +
	"_parent_idB\b\n" +
	"\x06_afterB\b\n" +
	"\x06_limit\"{\n" +
	"\x11ListPagesResponse\x120\n" +
	"\x05pages\x18\x01 \x03(\v2\x1a.marginal.document.v1.PageR\x05pages\x12$\n" +
	"\vnext_cursor\x18\x02 \x01(\tH\x00R\n" +
	"nextCursor\x88\x01\x01B\x0e\n" +
	"\f_next_cursor\"9\n" +
	"\x11RenamePageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"z\n" +
	"\x13ReparentPageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\tparent_id\x18\x02 \x01(\tH\x00R\bparentId\x88\x01\x01\x12\x19\n" +
	"\x05after\x18\x03 \x01(\tH\x01R\x05after\x88\x01\x01B\f\n" +
	"\n" +
	"_parent_idB\b\n" +
	"\x06_after\"#\n" +
	"\x11DeletePageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id*\x88\x01\n" +
	"\x0eLifecycleState\x12\x1f\n" +
	"\x1bLIFECYCLE_STATE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16LIFECYCLE_STATE_ACTIVE\x10\x01\x12\x1c\n" +
	"\x18LIFECYCLE_STATE_DELETING\x10\x02\x12\x1b\n" +
	"\x17LIFECYCLE_STATE_DELETED\x10\x032\x84\x04\n" +
	"\vPageService\x12Q\n" +
	"\n" +
	"CreatePage\x12'.marginal.document.v1.CreatePageRequest\x1a\x1a.marginal.document.v1.Page\x12K\n" +
	"\aGetPage\x12$.marginal.document.v1.GetPageRequest\x1a\x1a.marginal.document.v1.Page\x12\\\n" +
	"\tListPages\x12&.marginal.document.v1.ListPagesRequest\x1a'.marginal.document.v1.ListPagesResponse\x12Q\n" +
	"\n" +
	"RenamePage\x12'.marginal.document.v1.RenamePageRequest\x1a\x1a.marginal.document.v1.Page\x12U\n" +
	"\fReparentPage\x12).marginal.document.v1.ReparentPageRequest\x1a\x1a.marginal.document.v1.Page\x12M\n" +
	"\n" +
	"DeletePage\x12'.marginal.document.v1.DeletePageRequest\x1a\x16.google.protobuf.EmptyB8Z6marginal/document-service/internal/genproto/documentv1b\x06proto3"

var (
	file_document_proto_rawDescOnce sync.Once
	file_document_proto_rawDescData []byte
)

func file_document_proto_rawDescGZIP() []byte {
	file_document_proto_rawDescOnce.Do(func() {
		file_document_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_document_proto_rawDesc), len(file_document_proto_rawDesc)))
	})
	return file_document_proto_rawDescData
}

var file_document_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_document_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_document_proto_goTypes = []any{
	(LifecycleState)(0),           // 0: marginal.document.v1.LifecycleState
	(*Page)(nil),                  // 1: marginal.document.v1.Page
	(*CreatePageRequest)(nil),     // 2: marginal.document.v1.CreatePageRequest
	(*GetPageRequest)(nil),        // 3: marginal.document.v1.GetPageRequest
	(*ListPagesRequest)(nil),      // 4: marginal.document.v1.ListPagesRequest
	(*ListPagesResponse)(nil),     // 5: marginal.document.v1.ListPagesResponse
	(*RenamePageRequest)(nil),     // 6: marginal.document.v1.RenamePageRequest
	(*ReparentPageRequest)(nil),   // 7: marginal.document.v1.ReparentPageRequest
	(*DeletePageRequest)(nil),     // 8: marginal.document.v1.DeletePageRequest
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 10: google.protobuf.Empty
}
var file_document_proto_depIdxs = []int32{
	0,  // 0: marginal.document.v1.Page.lifecycle_state:type_name -> marginal.document.v1.LifecycleState
	9,  // 1: marginal.document.v1.Page.created_at:type_name -> google.protobuf.Timestamp
	9,  // 2: marginal.document.v1.Page.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 3: marginal.document.v1.Page.deleted_at:type_name -> google.protobuf.Timestamp
	1,  // 4: marginal.document.v1.ListPagesResponse.pages:type_name -> marginal.document.v1.Page
	2,  // 5: marginal.document.v1.PageService.CreatePage:input_type -> marginal.document.v1.CreatePageRequest
	3,  // 6: marginal.document.v1.PageService.GetPage:input_type -> marginal.document.v1.GetPageRequest
	4,  // 7: marginal.document.v1.PageService.ListPages:input_type -> marginal.document.v1.ListPagesRequest
	6,  // 8: marginal.document.v1.PageService.RenamePage:input_type -> marginal.document.v1.RenamePageRequest
	7,  // 9: marginal.document.v1.PageService.ReparentPage:input_type -> marginal.document.v1.ReparentPageRequest
	8,  // 10: marginal.document.v1.PageService.DeletePage:input_type -> marginal.document.v1.DeletePageRequest
	1,  // 11: marginal.document.v1.PageService.CreatePage:output_type -> marginal.document.v1.Page
	1,  // 12: marginal.document.v1.PageService.GetPage:output_type -> marginal.document.v1.Page
	5,  // 13: marginal.document.v1.PageService.ListPages:output_type -> marginal.document.v1.ListPagesResponse
	1,  // 14: marginal.document.v1.PageService.RenamePage:output_type -> marginal.document.v1.Page
	1,  // 15: marginal.document.v1.PageService.ReparentPage:output_type -> marginal.document.v1.Page
	10, // 16: marginal.document.v1.PageService.DeletePage:output_type -> google.protobuf.Empty
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_document_proto_init() }
func file_document_proto_init() {
	if File_document_proto != nil {
		return
	}
	file_document_proto_msgTypes[0].OneofWrappers = []any{}
	file_document_proto_msgTypes[1].OneofWrappers = []any{}
	file_document_proto_msgTypes[3].OneofWrappers = []any{}
	file_document_proto_msgTypes[4].OneofWrappers = []any{}
	file_document_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_document_proto_rawDesc), len(file_document_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_document_proto_goTypes,
		DependencyIndexes: file_document_proto_depIdxs,
		EnumInfos:         file_document_proto_enumTypes,
		MessageInfos:      file_document_proto_msgTypes,
	}.Build()
	File_document_proto = out.File
	file_document_proto_goTypes = nil
	file_document_proto_depIdxs = nil
}
