// PageService — the gRPC contract for page metadata (create/get/list/
// rename/reparent/delete). See docs/api/pages.md, which this file matches
// field-for-field — that doc is the source of truth for semantics; this
// file is its wire encoding.
//
// This is deliberately NOT where block content changes go — those are
// documentcore Ops (services/document-service/internal/documentcore),
// applied through a separate surface once one exists. PageService only
// owns the page row: title, tree position, lifecycle.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.0
// source: document.proto

package documentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PageService_CreatePage_FullMethodName           = "/marginal.document.v1.PageService/CreatePage"
	PageService_GetPage_FullMethodName              = "/marginal.document.v1.PageService/GetPage"
	PageService_ListPages_FullMethodName            = "/marginal.document.v1.PageService/ListPages"
	PageService_RenamePage_FullMethodName           = "/marginal.document.v1.PageService/RenamePage"
	PageService_ReparentPage_FullMethodName         = "/marginal.document.v1.PageService/ReparentPage"
	PageService_DeletePage_FullMethodName           = "/marginal.document.v1.PageService/DeletePage"
	PageService_ListBacklinks_FullMethodName        = "/marginal.document.v1.PageService/ListBacklinks"
	PageService_ListBlocks_FullMethodName           = "/marginal.document.v1.PageService/ListBlocks"
	PageService_PreviewDelete_FullMethodName        = "/marginal.document.v1.PageService/PreviewDelete"
	PageService_ListTrash_FullMethodName            = "/marginal.document.v1.PageService/ListTrash"
	PageService_RestorePage_FullMethodName          = "/marginal.document.v1.PageService/RestorePage"
	PageService_ListTopics_FullMethodName           = "/marginal.document.v1.PageService/ListTopics"
	PageService_SetPageTopic_FullMethodName         = "/marginal.document.v1.PageService/SetPageTopic"
	PageService_AddPageTag_FullMethodName           = "/marginal.document.v1.PageService/AddPageTag"
	PageService_RemovePageTag_FullMethodName        = "/marginal.document.v1.PageService/RemovePageTag"
	PageService_ListTagFacets_FullMethodName        = "/marginal.document.v1.PageService/ListTagFacets"
	PageService_SaveReadingPosition_FullMethodName  = "/marginal.document.v1.PageService/SaveReadingPosition"
	PageService_ListReadingPositions_FullMethodName = "/marginal.document.v1.PageService/ListReadingPositions"
)

// PageServiceClient is the client API for PageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PageServiceClient interface {
	CreatePage(ctx context.Context, in *CreatePageRequest, opts ...grpc.CallOption) (*Page, error)
	GetPage(ctx context.Context, in *GetPageRequest, opts ...grpc.CallOption) (*Page, error)
	ListPages(ctx context.Context, in *ListPagesRequest, opts ...grpc.CallOption) (*ListPagesResponse, error)
	RenamePage(ctx context.Context, in *RenamePageRequest, opts ...grpc.CallOption) (*Page, error)
	ReparentPage(ctx context.Context, in *ReparentPageRequest, opts ...grpc.CallOption) (*Page, error)
	DeletePage(ctx context.Context, in *DeletePageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ListBacklinks reads docs.page_links (internal/blockproj's projection
	// of collab.ops_flushed, not a page property PageService itself owns) —
	// it lives on this service purely because that table is in this
	// service's own database, not because it's page metadata like the rest
	// of this RPC set.
	ListBacklinks(ctx context.Context, in *ListBacklinksRequest, opts ...grpc.CallOption) (*ListBacklinksResponse, error)
	// ListBlocks reads docs.blocks (blockproj's own projection) — same
	// reasoning as ListBacklinks: this is diagnostics-service's read path
	// onto a page's actual prose (v2.3.0), not page metadata. kind_json/
	// content_json are documentcore.BlockKind/Content's own JSON shapes,
	// passed through verbatim rather than re-modelled as proto messages —
	// the caller already imports marginal/documentcore and can unmarshal
	// them directly, and this table's payload columns are already JSONB.
	ListBlocks(ctx context.Context, in *ListBlocksRequest, opts ...grpc.CallOption) (*ListBlocksResponse, error)
	// v2.6.0 — the delete saga, made observable and reversible.
	PreviewDelete(ctx context.Context, in *PreviewDeleteRequest, opts ...grpc.CallOption) (*PreviewDeleteResponse, error)
	ListTrash(ctx context.Context, in *ListTrashRequest, opts ...grpc.CallOption) (*ListTrashResponse, error)
	RestorePage(ctx context.Context, in *RestorePageRequest, opts ...grpc.CallOption) (*Page, error)
	// v2.7.0 — classification.
	ListTopics(ctx context.Context, in *ListTopicsRequest, opts ...grpc.CallOption) (*ListTopicsResponse, error)
	SetPageTopic(ctx context.Context, in *SetPageTopicRequest, opts ...grpc.CallOption) (*Page, error)
	AddPageTag(ctx context.Context, in *AddPageTagRequest, opts ...grpc.CallOption) (*Page, error)
	RemovePageTag(ctx context.Context, in *RemovePageTagRequest, opts ...grpc.CallOption) (*Page, error)
	ListTagFacets(ctx context.Context, in *ListTagFacetsRequest, opts ...grpc.CallOption) (*ListTagFacetsResponse, error)
	// v2.8.0 — resume. Where the caret was, per user per page.
	SaveReadingPosition(ctx context.Context, in *SaveReadingPositionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListReadingPositions(ctx context.Context, in *ListReadingPositionsRequest, opts ...grpc.CallOption) (*ListReadingPositionsResponse, error)
}

type pageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPageServiceClient(cc grpc.ClientConnInterface) PageServiceClient {
	return &pageServiceClient{cc}
}

func (c *pageServiceClient) CreatePage(ctx context.Context, in *CreatePageRequest, opts ...grpc.CallOption) (*Page, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Page)
	err := c.cc.Invoke(ctx, PageService_CreatePage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) GetPage(ctx context.Context, in *GetPageRequest, opts ...grpc.CallOption) (*Page, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Page)
	err := c.cc.Invoke(ctx, PageService_GetPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) ListPages(ctx context.Context, in *ListPagesRequest, opts ...grpc.CallOption) (*ListPagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPagesResponse)
	err := c.cc.Invoke(ctx, PageService_ListPages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) RenamePage(ctx context.Context, in *RenamePageRequest, opts ...grpc.CallOption) (*Page, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Page)
	err := c.cc.Invoke(ctx, PageService_RenamePage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) ReparentPage(ctx context.Context, in *ReparentPageRequest, opts ...grpc.CallOption) (*Page, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Page)
	err := c.cc.Invoke(ctx, PageService_ReparentPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) DeletePage(ctx context.Context, in *DeletePageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PageService_DeletePage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) ListBacklinks(ctx context.Context, in *ListBacklinksRequest, opts ...grpc.CallOption) (*ListBacklinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBacklinksResponse)
	err := c.cc.Invoke(ctx, PageService_ListBacklinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) ListBlocks(ctx context.Context, in *ListBlocksRequest, opts ...grpc.CallOption) (*ListBlocksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBlocksResponse)
	err := c.cc.Invoke(ctx, PageService_ListBlocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) PreviewDelete(ctx context.Context, in *PreviewDeleteRequest, opts ...grpc.CallOption) (*PreviewDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreviewDeleteResponse)
	err := c.cc.Invoke(ctx, PageService_PreviewDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) ListTrash(ctx context.Context, in *ListTrashRequest, opts ...grpc.CallOption) (*ListTrashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTrashResponse)
	err := c.cc.Invoke(ctx, PageService_ListTrash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) RestorePage(ctx context.Context, in *RestorePageRequest, opts ...grpc.CallOption) (*Page, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Page)
	err := c.cc.Invoke(ctx, PageService_RestorePage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) ListTopics(ctx context.Context, in *ListTopicsRequest, opts ...grpc.CallOption) (*ListTopicsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTopicsResponse)
	err := c.cc.Invoke(ctx, PageService_ListTopics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) SetPageTopic(ctx context.Context, in *SetPageTopicRequest, opts ...grpc.CallOption) (*Page, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Page)
	err := c.cc.Invoke(ctx, PageService_SetPageTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) AddPageTag(ctx context.Context, in *AddPageTagRequest, opts ...grpc.CallOption) (*Page, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Page)
	err := c.cc.Invoke(ctx, PageService_AddPageTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) RemovePageTag(ctx context.Context, in *RemovePageTagRequest, opts ...grpc.CallOption) (*Page, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Page)
	err := c.cc.Invoke(ctx, PageService_RemovePageTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) ListTagFacets(ctx context.Context, in *ListTagFacetsRequest, opts ...grpc.CallOption) (*ListTagFacetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTagFacetsResponse)
	err := c.cc.Invoke(ctx, PageService_ListTagFacets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) SaveReadingPosition(ctx context.Context, in *SaveReadingPositionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PageService_SaveReadingPosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) ListReadingPositions(ctx context.Context, in *ListReadingPositionsRequest, opts ...grpc.CallOption) (*ListReadingPositionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReadingPositionsResponse)
	err := c.cc.Invoke(ctx, PageService_ListReadingPositions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PageServiceServer is the server API for PageService service.
// All implementations must embed UnimplementedPageServiceServer
// for forward compatibility.
type PageServiceServer interface {
	CreatePage(context.Context, *CreatePageRequest) (*Page, error)
	GetPage(context.Context, *GetPageRequest) (*Page, error)
	ListPages(context.Context, *ListPagesRequest) (*ListPagesResponse, error)
	RenamePage(context.Context, *RenamePageRequest) (*Page, error)
	ReparentPage(context.Context, *ReparentPageRequest) (*Page, error)
	DeletePage(context.Context, *DeletePageRequest) (*emptypb.Empty, error)
	// ListBacklinks reads docs.page_links (internal/blockproj's projection
	// of collab.ops_flushed, not a page property PageService itself owns) —
	// it lives on this service purely because that table is in this
	// service's own database, not because it's page metadata like the rest
	// of this RPC set.
	ListBacklinks(context.Context, *ListBacklinksRequest) (*ListBacklinksResponse, error)
	// ListBlocks reads docs.blocks (blockproj's own projection) — same
	// reasoning as ListBacklinks: this is diagnostics-service's read path
	// onto a page's actual prose (v2.3.0), not page metadata. kind_json/
	// content_json are documentcore.BlockKind/Content's own JSON shapes,
	// passed through verbatim rather than re-modelled as proto messages —
	// the caller already imports marginal/documentcore and can unmarshal
	// them directly, and this table's payload columns are already JSONB.
	ListBlocks(context.Context, *ListBlocksRequest) (*ListBlocksResponse, error)
	// v2.6.0 — the delete saga, made observable and reversible.
	PreviewDelete(context.Context, *PreviewDeleteRequest) (*PreviewDeleteResponse, error)
	ListTrash(context.Context, *ListTrashRequest) (*ListTrashResponse, error)
	RestorePage(context.Context, *RestorePageRequest) (*Page, error)
	// v2.7.0 — classification.
	ListTopics(context.Context, *ListTopicsRequest) (*ListTopicsResponse, error)
	SetPageTopic(context.Context, *SetPageTopicRequest) (*Page, error)
	AddPageTag(context.Context, *AddPageTagRequest) (*Page, error)
	RemovePageTag(context.Context, *RemovePageTagRequest) (*Page, error)
	ListTagFacets(context.Context, *ListTagFacetsRequest) (*ListTagFacetsResponse, error)
	// v2.8.0 — resume. Where the caret was, per user per page.
	SaveReadingPosition(context.Context, *SaveReadingPositionRequest) (*emptypb.Empty, error)
	ListReadingPositions(context.Context, *ListReadingPositionsRequest) (*ListReadingPositionsResponse, error)
	mustEmbedUnimplementedPageServiceServer()
}

// UnimplementedPageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPageServiceServer struct{}

func (UnimplementedPageServiceServer) CreatePage(context.Context, *CreatePageRequest) (*Page, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePage not implemented")
}
func (UnimplementedPageServiceServer) GetPage(context.Context, *GetPageRequest) (*Page, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPage not implemented")
}
func (UnimplementedPageServiceServer) ListPages(context.Context, *ListPagesRequest) (*ListPagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPages not implemented")
}
func (UnimplementedPageServiceServer) RenamePage(context.Context, *RenamePageRequest) (*Page, error) {
	return nil, status.Error(codes.Unimplemented, "method RenamePage not implemented")
}
func (UnimplementedPageServiceServer) ReparentPage(context.Context, *ReparentPageRequest) (*Page, error) {
	return nil, status.Error(codes.Unimplemented, "method ReparentPage not implemented")
}
func (UnimplementedPageServiceServer) DeletePage(context.Context, *DeletePageRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePage not implemented")
}
func (UnimplementedPageServiceServer) ListBacklinks(context.Context, *ListBacklinksRequest) (*ListBacklinksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBacklinks not implemented")
}
func (UnimplementedPageServiceServer) ListBlocks(context.Context, *ListBlocksRequest) (*ListBlocksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBlocks not implemented")
}
func (UnimplementedPageServiceServer) PreviewDelete(context.Context, *PreviewDeleteRequest) (*PreviewDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PreviewDelete not implemented")
}
func (UnimplementedPageServiceServer) ListTrash(context.Context, *ListTrashRequest) (*ListTrashResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTrash not implemented")
}
func (UnimplementedPageServiceServer) RestorePage(context.Context, *RestorePageRequest) (*Page, error) {
	return nil, status.Error(codes.Unimplemented, "method RestorePage not implemented")
}
func (UnimplementedPageServiceServer) ListTopics(context.Context, *ListTopicsRequest) (*ListTopicsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTopics not implemented")
}
func (UnimplementedPageServiceServer) SetPageTopic(context.Context, *SetPageTopicRequest) (*Page, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPageTopic not implemented")
}
func (UnimplementedPageServiceServer) AddPageTag(context.Context, *AddPageTagRequest) (*Page, error) {
	return nil, status.Error(codes.Unimplemented, "method AddPageTag not implemented")
}
func (UnimplementedPageServiceServer) RemovePageTag(context.Context, *RemovePageTagRequest) (*Page, error) {
	return nil, status.Error(codes.Unimplemented, "method RemovePageTag not implemented")
}
func (UnimplementedPageServiceServer) ListTagFacets(context.Context, *ListTagFacetsRequest) (*ListTagFacetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTagFacets not implemented")
}
func (UnimplementedPageServiceServer) SaveReadingPosition(context.Context, *SaveReadingPositionRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveReadingPosition not implemented")
}
func (UnimplementedPageServiceServer) ListReadingPositions(context.Context, *ListReadingPositionsRequest) (*ListReadingPositionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListReadingPositions not implemented")
}
func (UnimplementedPageServiceServer) mustEmbedUnimplementedPageServiceServer() {}
func (UnimplementedPageServiceServer) testEmbeddedByValue()                     {}

// UnsafePageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PageServiceServer will
// result in compilation errors.
type UnsafePageServiceServer interface {
	mustEmbedUnimplementedPageServiceServer()
}

func RegisterPageServiceServer(s grpc.ServiceRegistrar, srv PageServiceServer) {
	// If the following call panics, it indicates UnimplementedPageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PageService_ServiceDesc, srv)
}

func _PageService_CreatePage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).CreatePage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_CreatePage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).CreatePage(ctx, req.(*CreatePageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_GetPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).GetPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_GetPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).GetPage(ctx, req.(*GetPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_ListPages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).ListPages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_ListPages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).ListPages(ctx, req.(*ListPagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_RenamePage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenamePageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).RenamePage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_RenamePage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).RenamePage(ctx, req.(*RenamePageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_ReparentPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReparentPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).ReparentPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_ReparentPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).ReparentPage(ctx, req.(*ReparentPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_DeletePage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).DeletePage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_DeletePage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).DeletePage(ctx, req.(*DeletePageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_ListBacklinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBacklinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).ListBacklinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_ListBacklinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).ListBacklinks(ctx, req.(*ListBacklinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_ListBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).ListBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_ListBlocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).ListBlocks(ctx, req.(*ListBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_PreviewDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreviewDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).PreviewDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_PreviewDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).PreviewDelete(ctx, req.(*PreviewDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_ListTrash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTrashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).ListTrash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_ListTrash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).ListTrash(ctx, req.(*ListTrashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_RestorePage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestorePageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).RestorePage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_RestorePage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).RestorePage(ctx, req.(*RestorePageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_ListTopics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTopicsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).ListTopics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_ListTopics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).ListTopics(ctx, req.(*ListTopicsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_SetPageTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPageTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).SetPageTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_SetPageTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).SetPageTopic(ctx, req.(*SetPageTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_AddPageTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPageTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).AddPageTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_AddPageTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).AddPageTag(ctx, req.(*AddPageTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_RemovePageTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePageTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).RemovePageTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_RemovePageTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).RemovePageTag(ctx, req.(*RemovePageTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_ListTagFacets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTagFacetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).ListTagFacets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_ListTagFacets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).ListTagFacets(ctx, req.(*ListTagFacetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_SaveReadingPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveReadingPositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).SaveReadingPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_SaveReadingPosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).SaveReadingPosition(ctx, req.(*SaveReadingPositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_ListReadingPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReadingPositionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).ListReadingPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_ListReadingPositions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).ListReadingPositions(ctx, req.(*ListReadingPositionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PageService_ServiceDesc is the grpc.ServiceDesc for PageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "marginal.document.v1.PageService",
	HandlerType: (*PageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePage",
			Handler:    _PageService_CreatePage_Handler,
		},
		{
			MethodName: "GetPage",
			Handler:    _PageService_GetPage_Handler,
		},
		{
			MethodName: "ListPages",
			Handler:    _PageService_ListPages_Handler,
		},
		{
			MethodName: "RenamePage",
			Handler:    _PageService_RenamePage_Handler,
		},
		{
			MethodName: "ReparentPage",
			Handler:    _PageService_ReparentPage_Handler,
		},
		{
			MethodName: "DeletePage",
			Handler:    _PageService_DeletePage_Handler,
		},
		{
			MethodName: "ListBacklinks",
			Handler:    _PageService_ListBacklinks_Handler,
		},
		{
			MethodName: "ListBlocks",
			Handler:    _PageService_ListBlocks_Handler,
		},
		{
			MethodName: "PreviewDelete",
			Handler:    _PageService_PreviewDelete_Handler,
		},
		{
			MethodName: "ListTrash",
			Handler:    _PageService_ListTrash_Handler,
		},
		{
			MethodName: "RestorePage",
			Handler:    _PageService_RestorePage_Handler,
		},
		{
			MethodName: "ListTopics",
			Handler:    _PageService_ListTopics_Handler,
		},
		{
			MethodName: "SetPageTopic",
			Handler:    _PageService_SetPageTopic_Handler,
		},
		{
			MethodName: "AddPageTag",
			Handler:    _PageService_AddPageTag_Handler,
		},
		{
			MethodName: "RemovePageTag",
			Handler:    _PageService_RemovePageTag_Handler,
		},
		{
			MethodName: "ListTagFacets",
			Handler:    _PageService_ListTagFacets_Handler,
		},
		{
			MethodName: "SaveReadingPosition",
			Handler:    _PageService_SaveReadingPosition_Handler,
		},
		{
			MethodName: "ListReadingPositions",
			Handler:    _PageService_ListReadingPositions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "document.proto",
}
