// GraphService — the gRPC contract for the real [[link]] graph
// (docs/ui-mockups/v2/index.html § 07 GRAPH, graph-algorithms.html). See
// docs/api/graph.md, which this file matches field-for-field.
//
// Read-only and parameter-light on purpose: every algorithm here
// (graphalgo) is a pure function over docs.pages/docs.page_links
// as of right now, computed fresh per request — there is no persisted
// "graph" state of its own to keep consistent, unlike PageService's own
// rows.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.0
// source: graph.proto

package documentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLinkGraphRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLinkGraphRequest) Reset() {
	*x = GetLinkGraphRequest{}
	mi := &file_graph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinkGraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkGraphRequest) ProtoMessage() {}

func (x *GetLinkGraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkGraphRequest.ProtoReflect.Descriptor instead.
func (*GetLinkGraphRequest) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{0}
}

type LinkGraph struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*GraphNode           `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*GraphEdge           `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkGraph) Reset() {
	*x = LinkGraph{}
	mi := &file_graph_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkGraph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkGraph) ProtoMessage() {}

func (x *LinkGraph) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkGraph.ProtoReflect.Descriptor instead.
func (*LinkGraph) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{1}
}

func (x *LinkGraph) GetNodes() []*GraphNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *LinkGraph) GetEdges() []*GraphEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type GraphNode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// is_root mirrors graphalgo.Orphans' own root set: a page
	// with no parent, reachable without already knowing another page's
	// title exists.
	IsRoot        bool `protobuf:"varint,3,opt,name=is_root,json=isRoot,proto3" json:"is_root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphNode) Reset() {
	*x = GraphNode{}
	mi := &file_graph_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphNode) ProtoMessage() {}

func (x *GraphNode) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphNode.ProtoReflect.Descriptor instead.
func (*GraphNode) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{2}
}

func (x *GraphNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GraphNode) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GraphNode) GetIsRoot() bool {
	if x != nil {
		return x.IsRoot
	}
	return false
}

type GraphEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromPage      string                 `protobuf:"bytes,1,opt,name=from_page,json=fromPage,proto3" json:"from_page,omitempty"`
	ToPage        string                 `protobuf:"bytes,2,opt,name=to_page,json=toPage,proto3" json:"to_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphEdge) Reset() {
	*x = GraphEdge{}
	mi := &file_graph_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphEdge) ProtoMessage() {}

func (x *GraphEdge) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphEdge.ProtoReflect.Descriptor instead.
func (*GraphEdge) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{3}
}

func (x *GraphEdge) GetFromPage() string {
	if x != nil {
		return x.FromPage
	}
	return ""
}

func (x *GraphEdge) GetToPage() string {
	if x != nil {
		return x.ToPage
	}
	return ""
}

type AnalyzeGraphRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeGraphRequest) Reset() {
	*x = AnalyzeGraphRequest{}
	mi := &file_graph_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeGraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeGraphRequest) ProtoMessage() {}

func (x *AnalyzeGraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeGraphRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeGraphRequest) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{4}
}

type GraphAnalysis struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// component_of maps every page id to its connected-component id
	// (graphalgo.Components, over the undirected projection).
	ComponentOf map[string]int32 `protobuf:"bytes,1,rep,name=component_of,json=componentOf,proto3" json:"component_of,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// orphan_components are component ids containing none of the root
	// pages — graph-algorithms.html's own "a mutually-linked pair with
	// nothing pointing in is still orphaned" argument.
	OrphanComponents []int32 `protobuf:"varint,2,rep,packed,name=orphan_components,json=orphanComponents,proto3" json:"orphan_components,omitempty"`
	// cycle is one example cycle, as an ordered, closed list of page ids
	// (first == last) — empty if the graph is acyclic.
	Cycle    []string `protobuf:"bytes,3,rep,name=cycle,proto3" json:"cycle,omitempty"`
	Diameter int32    `protobuf:"varint,4,opt,name=diameter,proto3" json:"diameter,omitempty"`
	// betti is graph-algorithms.html's own topology panel
	// (graphalgo.Betti) — see BettiNumbers' own field comments for
	// why some of these are graph facts and some are a stated modelling
	// choice (filling every triangle).
	Betti *BettiNumbers `protobuf:"bytes,5,opt,name=betti,proto3" json:"betti,omitempty"`
	// betweenness is each page's Brandes centrality over the UNDIRECTED view
	// (graphalgo.Betweenness), normalised to [0,1]. A page can have few links
	// and high betweenness — that is the interesting case, because it is a
	// bridge whose degree never warned you.
	Betweenness map[string]float64 `protobuf:"bytes,6,rep,name=betweenness,proto3" json:"betweenness,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	// modularity_by_topic is Newman's Q for the partition pages DECLARE
	// (docs.pages.topic_id). Compared against a partition the graph itself
	// implies, the gap is the finding: topics scoring much lower would mean
	// they describe something other than how pages link.
	ModularityByTopic float64 `protobuf:"fixed64,7,opt,name=modularity_by_topic,json=modularityByTopic,proto3" json:"modularity_by_topic,omitempty"`
	// modularity_by_component is Q for the connected components — the
	// emergent partition, and the honest baseline to read the above against.
	ModularityByComponent float64 `protobuf:"fixed64,8,opt,name=modularity_by_component,json=modularityByComponent,proto3" json:"modularity_by_component,omitempty"`
	// strongly_connected maps every page to its strongly connected component
	// (graphalgo.StronglyConnected, Tarjan, over the DIRECTED graph).
	//
	// A different question from component_of, which is why both are here:
	// component_of asks "can I walk between these two pages ignoring
	// direction"; this asks "can I walk there AND back following links as
	// written". A component of size > 1 is a citation loop.
	StronglyConnected map[string]int32 `protobuf:"bytes,9,rep,name=strongly_connected,json=stronglyConnected,proto3" json:"strongly_connected,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// scc_sizes are those components' sizes, largest first. All ones means no
	// citation loops anywhere — the healthy default, worth being able to state.
	SccSizes []int32 `protobuf:"varint,10,rep,packed,name=scc_sizes,json=sccSizes,proto3" json:"scc_sizes,omitempty"`
	// topological_order is a reading order in which no page comes before one it
	// links to (graphalgo.TopologicalSort, Kahn, ties broken on page id so the
	// order is stable across requests).
	//
	// PARTIAL when is_dag is false: it holds every page that could be placed
	// before the algorithm ran out of prerequisite-free nodes, and `unplaced`
	// holds the rest. That partial result is the useful half of a failure.
	TopologicalOrder []string `protobuf:"bytes,11,rep,name=topological_order,json=topologicalOrder,proto3" json:"topological_order,omitempty"`
	IsDag            bool     `protobuf:"varint,12,opt,name=is_dag,json=isDag,proto3" json:"is_dag,omitempty"`
	Unplaced         []string `protobuf:"bytes,13,rep,name=unplaced,proto3" json:"unplaced,omitempty"`
	// layers groups topological_order into dependency LEVELS — everything in
	// one level can be read in any order, or by two people at once. The number
	// of layers is the longest dependency chain in the workspace.
	Layers        []*GraphLayer `protobuf:"bytes,14,rep,name=layers,proto3" json:"layers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphAnalysis) Reset() {
	*x = GraphAnalysis{}
	mi := &file_graph_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphAnalysis) ProtoMessage() {}

func (x *GraphAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphAnalysis.ProtoReflect.Descriptor instead.
func (*GraphAnalysis) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{5}
}

func (x *GraphAnalysis) GetComponentOf() map[string]int32 {
	if x != nil {
		return x.ComponentOf
	}
	return nil
}

func (x *GraphAnalysis) GetOrphanComponents() []int32 {
	if x != nil {
		return x.OrphanComponents
	}
	return nil
}

func (x *GraphAnalysis) GetCycle() []string {
	if x != nil {
		return x.Cycle
	}
	return nil
}

func (x *GraphAnalysis) GetDiameter() int32 {
	if x != nil {
		return x.Diameter
	}
	return 0
}

func (x *GraphAnalysis) GetBetti() *BettiNumbers {
	if x != nil {
		return x.Betti
	}
	return nil
}

func (x *GraphAnalysis) GetBetweenness() map[string]float64 {
	if x != nil {
		return x.Betweenness
	}
	return nil
}

func (x *GraphAnalysis) GetModularityByTopic() float64 {
	if x != nil {
		return x.ModularityByTopic
	}
	return 0
}

func (x *GraphAnalysis) GetModularityByComponent() float64 {
	if x != nil {
		return x.ModularityByComponent
	}
	return 0
}

func (x *GraphAnalysis) GetStronglyConnected() map[string]int32 {
	if x != nil {
		return x.StronglyConnected
	}
	return nil
}

func (x *GraphAnalysis) GetSccSizes() []int32 {
	if x != nil {
		return x.SccSizes
	}
	return nil
}

func (x *GraphAnalysis) GetTopologicalOrder() []string {
	if x != nil {
		return x.TopologicalOrder
	}
	return nil
}

func (x *GraphAnalysis) GetIsDag() bool {
	if x != nil {
		return x.IsDag
	}
	return false
}

func (x *GraphAnalysis) GetUnplaced() []string {
	if x != nil {
		return x.Unplaced
	}
	return nil
}

func (x *GraphAnalysis) GetLayers() []*GraphLayer {
	if x != nil {
		return x.Layers
	}
	return nil
}

// GraphLayer exists only because proto3 has no repeated-of-repeated.
type GraphLayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageIds       []string               `protobuf:"bytes,1,rep,name=page_ids,json=pageIds,proto3" json:"page_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphLayer) Reset() {
	*x = GraphLayer{}
	mi := &file_graph_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphLayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphLayer) ProtoMessage() {}

func (x *GraphLayer) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphLayer.ProtoReflect.Descriptor instead.
func (*GraphLayer) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{6}
}

func (x *GraphLayer) GetPageIds() []string {
	if x != nil {
		return x.PageIds
	}
	return nil
}

type BettiNumbers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	B0            int32                  `protobuf:"varint,1,opt,name=b0,proto3" json:"b0,omitempty"`                             // components
	B1            int32                  `protobuf:"varint,2,opt,name=b1,proto3" json:"b1,omitempty"`                             // cycle rank of the plain graph: E - V + b0
	B1Clique      int32                  `protobuf:"varint,3,opt,name=b1_clique,json=b1Clique,proto3" json:"b1_clique,omitempty"` // b1 minus rank(boundary map ∂2) — the loops surviving after every triangle is filled
	B2            int32                  `protobuf:"varint,4,opt,name=b2,proto3" json:"b2,omitempty"`                             // chi - b0 + b1_clique, read off the Euler characteristic for free
	Chi           int32                  `protobuf:"varint,5,opt,name=chi,proto3" json:"chi,omitempty"`                           // Euler characteristic of the clique complex: V - E + F
	Triangles     int32                  `protobuf:"varint,6,opt,name=triangles,proto3" json:"triangles,omitempty"`               // |F| — how many 3-cliques were filled
	Rank2         int32                  `protobuf:"varint,7,opt,name=rank2,proto3" json:"rank2,omitempty"`                       // rank(∂2) over GF(2) — exactly the loops triangles killed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BettiNumbers) Reset() {
	*x = BettiNumbers{}
	mi := &file_graph_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BettiNumbers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BettiNumbers) ProtoMessage() {}

func (x *BettiNumbers) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BettiNumbers.ProtoReflect.Descriptor instead.
func (*BettiNumbers) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{7}
}

func (x *BettiNumbers) GetB0() int32 {
	if x != nil {
		return x.B0
	}
	return 0
}

func (x *BettiNumbers) GetB1() int32 {
	if x != nil {
		return x.B1
	}
	return 0
}

func (x *BettiNumbers) GetB1Clique() int32 {
	if x != nil {
		return x.B1Clique
	}
	return 0
}

func (x *BettiNumbers) GetB2() int32 {
	if x != nil {
		return x.B2
	}
	return 0
}

func (x *BettiNumbers) GetChi() int32 {
	if x != nil {
		return x.Chi
	}
	return 0
}

func (x *BettiNumbers) GetTriangles() int32 {
	if x != nil {
		return x.Triangles
	}
	return 0
}

func (x *BettiNumbers) GetRank2() int32 {
	if x != nil {
		return x.Rank2
	}
	return 0
}

type GraphNeighborhoodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourcePageId  string                 `protobuf:"bytes,1,opt,name=source_page_id,json=sourcePageId,proto3" json:"source_page_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphNeighborhoodRequest) Reset() {
	*x = GraphNeighborhoodRequest{}
	mi := &file_graph_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphNeighborhoodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphNeighborhoodRequest) ProtoMessage() {}

func (x *GraphNeighborhoodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphNeighborhoodRequest.ProtoReflect.Descriptor instead.
func (*GraphNeighborhoodRequest) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{8}
}

func (x *GraphNeighborhoodRequest) GetSourcePageId() string {
	if x != nil {
		return x.SourcePageId
	}
	return ""
}

type GraphNeighborhoodResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// undirected_distance: link-distance BFS from source_page_id — the
	// page-by-page "wavefront" a client animates one distance value at a
	// time. Absent from the map means unreachable.
	UndirectedDistance map[string]int32 `protobuf:"bytes,1,rep,name=undirected_distance,json=undirectedDistance,proto3" json:"undirected_distance,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// forward_reachable: directed BFS from source_page_id, outbound links
	// only — the blast radius a cascading delete starting there would take
	// with it.
	ForwardReachable map[string]int32 `protobuf:"bytes,2,rep,name=forward_reachable,json=forwardReachable,proto3" json:"forward_reachable,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// nearest is the ranked ring around source_page_id — nearest first by hop
	// distance, ties broken on page id (graphalgo.NearestNeighbours).
	//
	// Near BY LINKS, deliberately not near by meaning: /discover answers that
	// one with cosine distance over embeddings, and the gap between the two
	// answers is the finding — a page about the same thing you have never cited
	// is near by meaning and far by links.
	Nearest []*GraphNeighbour `protobuf:"bytes,3,rep,name=nearest,proto3" json:"nearest,omitempty"`
	// ring_sizes[d] is how many pages sit exactly d hops away, starting at
	// d = 0 (the source itself). The shape is the argument: a frontier that
	// stops growing is a graph that stops connecting.
	RingSizes []int32 `protobuf:"varint,4,rep,packed,name=ring_sizes,json=ringSizes,proto3" json:"ring_sizes,omitempty"`
	// reading_path is "what to read before this page, and in what order" —
	// everything that reaches it by following links FORWARD, layered so that a
	// page with no prerequisites of its own comes first, ending at the page
	// itself (graphalgo.ReadingPath).
	//
	// Deliberately NOT the shortest path, which answers "how are these two
	// connected" and already has its own field, and deliberately not "pages
	// with similar tags", because shared tags give you neighbours rather than
	// prerequisites — only the arrows carry order.
	//
	// A page nothing links to has a path of ONE step: itself. That is what
	// "start here" looks like, and it is a real answer rather than an empty one.
	ReadingPath   []*PathStep `protobuf:"bytes,5,rep,name=reading_path,json=readingPath,proto3" json:"reading_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphNeighborhoodResponse) Reset() {
	*x = GraphNeighborhoodResponse{}
	mi := &file_graph_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphNeighborhoodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphNeighborhoodResponse) ProtoMessage() {}

func (x *GraphNeighborhoodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphNeighborhoodResponse.ProtoReflect.Descriptor instead.
func (*GraphNeighborhoodResponse) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{9}
}

func (x *GraphNeighborhoodResponse) GetUndirectedDistance() map[string]int32 {
	if x != nil {
		return x.UndirectedDistance
	}
	return nil
}

func (x *GraphNeighborhoodResponse) GetForwardReachable() map[string]int32 {
	if x != nil {
		return x.ForwardReachable
	}
	return nil
}

func (x *GraphNeighborhoodResponse) GetNearest() []*GraphNeighbour {
	if x != nil {
		return x.Nearest
	}
	return nil
}

func (x *GraphNeighborhoodResponse) GetRingSizes() []int32 {
	if x != nil {
		return x.RingSizes
	}
	return nil
}

func (x *GraphNeighborhoodResponse) GetReadingPath() []*PathStep {
	if x != nil {
		return x.ReadingPath
	}
	return nil
}

type GraphNeighbour struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Hops          int32                  `protobuf:"varint,3,opt,name=hops,proto3" json:"hops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphNeighbour) Reset() {
	*x = GraphNeighbour{}
	mi := &file_graph_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphNeighbour) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphNeighbour) ProtoMessage() {}

func (x *GraphNeighbour) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphNeighbour.ProtoReflect.Descriptor instead.
func (*GraphNeighbour) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{10}
}

func (x *GraphNeighbour) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *GraphNeighbour) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GraphNeighbour) GetHops() int32 {
	if x != nil {
		return x.Hops
	}
	return 0
}

// PathStep is one page on the way to another — graphalgo.ReadingPath.
type PathStep struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	PageId string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	Title  string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// The dependency LAYER, not the distance from the target: two pages at the
	// same depth can be read in either order.
	Depth int32 `protobuf:"varint,3,opt,name=depth,proto3" json:"depth,omitempty"`
	// Always true for exactly the last step. The list is what to read UP TO the
	// page you asked about, so ending anywhere else would leave the reader
	// wondering where they were going.
	Destination   bool `protobuf:"varint,4,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathStep) Reset() {
	*x = PathStep{}
	mi := &file_graph_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathStep) ProtoMessage() {}

func (x *PathStep) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathStep.ProtoReflect.Descriptor instead.
func (*PathStep) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{11}
}

func (x *PathStep) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *PathStep) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PathStep) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *PathStep) GetDestination() bool {
	if x != nil {
		return x.Destination
	}
	return false
}

var File_graph_proto protoreflect.FileDescriptor

const file_graph_proto_rawDesc = "" +
	"\n" +
	"\vgraph.proto\x12\x14marginal.document.v1\"\x15\n" +
	"\x13GetLinkGraphRequest\"y\n" +
	"\tLinkGraph\x125\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1f.marginal.document.v1.GraphNodeR\x05nodes\x125\n" +
	"\x05edges\x18\x02 \x03(\v2\x1f.marginal.document.v1.GraphEdgeR\x05edges\"J\n" +
	"\tGraphNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x17\n" +
	"\ais_root\x18\x03 \x01(\bR\x06isRoot\"A\n" +
	"\tGraphEdge\x12\x1b\n" +
	"\tfrom_page\x18\x01 \x01(\tR\bfromPage\x12\x17\n" +
	"\ato_page\x18\x02 \x01(\tR\x06toPage\"\x15\n" +
	"\x13AnalyzeGraphRequest\"\xa9\a\n" +
	"\rGraphAnalysis\x12W\n" +
	"\fcomponent_of\x18\x01 \x03(\v24.marginal.document.v1.GraphAnalysis.ComponentOfEntryR\vcomponentOf\x12+\n" +
	"\x11orphan_components\x18\x02 \x03(\x05R\x10orphanComponents\x12\x14\n" +
	"\x05cycle\x18\x03 \x03(\tR\x05cycle\x12\x1a\n" +
	"\bdiameter\x18\x04 \x01(\x05R\bdiameter\x128\n" +
	"\x05betti\x18\x05 \x01(\v2\".marginal.document.v1.BettiNumbersR\x05betti\x12V\n" +
	"\vbetweenness\x18\x06 \x03(\v24.marginal.document.v1.GraphAnalysis.BetweennessEntryR\vbetweenness\x12.\n" +
	"\x13modularity_by_topic\x18\a \x01(\x01R\x11modularityByTopic\x126\n" +
	"\x17modularity_by_component\x18\b \x01(\x01R\x15modularityByComponent\x12i\n" +
	"\x12strongly_connected\x18\t \x03(\v2:.marginal.document.v1.GraphAnalysis.StronglyConnectedEntryR\x11stronglyConnected\x12\x1b\n" +
	"\tscc_sizes\x18\n" +
	" \x03(\x05R\bsccSizes\x12+\n" +
	"\x11topological_order\x18\v \x03(\tR\x10topologicalOrder\x12\x15\n" +
	"\x06is_dag\x18\f \x01(\bR\x05isDag\x12\x1a\n" +
	"\bunplaced\x18\r \x03(\tR\bunplaced\x128\n" +
	"\x06layers\x18\x0e \x03(\v2 .marginal.document.v1.GraphLayerR\x06layers\x1a>\n" +
	"\x10ComponentOfEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a>\n" +
	"\x10BetweennessEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1aD\n" +
	"\x16StronglyConnectedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"'\n" +
	"\n" +
	"GraphLayer\x12\x19\n" +
	"\bpage_ids\x18\x01 \x03(\tR\apageIds\"\xa1\x01\n" +
	"\fBettiNumbers\x12\x0e\n" +
	"\x02b0\x18\x01 \x01(\x05R\x02b0\x12\x0e\n" +
	"\x02b1\x18\x02 \x01(\x05R\x02b1\x12\x1b\n" +
	"\tb1_clique\x18\x03 \x01(\x05R\bb1Clique\x12\x0e\n" +
	"\x02b2\x18\x04 \x01(\x05R\x02b2\x12\x10\n" +
	"\x03chi\x18\x05 \x01(\x05R\x03chi\x12\x1c\n" +
	"\ttriangles\x18\x06 \x01(\x05R\ttriangles\x12\x14\n" +
	"\x05rank2\x18\a \x01(\x05R\x05rank2\"@\n" +
	"\x18GraphNeighborhoodRequest\x12$\n" +
	"\x0esource_page_id\x18\x01 \x01(\tR\fsourcePageId\"\xb7\x04\n" +
	"\x19GraphNeighborhoodResponse\x12x\n" +
	"\x13undirected_distance\x18\x01 \x03(\v2G.marginal.document.v1.GraphNeighborhoodResponse.UndirectedDistanceEntryR\x12undirectedDistance\x12r\n" +
	"\x11forward_reachable\x18\x02 \x03(\v2E.marginal.document.v1.GraphNeighborhoodResponse.ForwardReachableEntryR\x10forwardReachable\x12>\n" +
	"\anearest\x18\x03 \x03(\v2$.marginal.document.v1.GraphNeighbourR\anearest\x12\x1d\n" +
	"\n" +
	"ring_sizes\x18\x04 \x03(\x05R\tringSizes\x12A\n" +
	"\freading_path\x18\x05 \x03(\v2\x1e.marginal.document.v1.PathStepR\vreadingPath\x1aE\n" +
	"\x17UndirectedDistanceEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aC\n" +
	"\x15ForwardReachableEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"S\n" +
	"\x0eGraphNeighbour\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04hops\x18\x03 \x01(\x05R\x04hops\"q\n" +
	"\bPathStep\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05depth\x18\x03 \x01(\x05R\x05depth\x12 \n" +
	"\vdestination\x18\x04 \x01(\bR\vdestination2\xc0\x02\n" +
	"\fGraphService\x12Z\n" +
	"\fGetLinkGraph\x12).marginal.document.v1.GetLinkGraphRequest\x1a\x1f.marginal.document.v1.LinkGraph\x12^\n" +
	"\fAnalyzeGraph\x12).marginal.document.v1.AnalyzeGraphRequest\x1a#.marginal.document.v1.GraphAnalysis\x12t\n" +
	"\x11GraphNeighborhood\x12..marginal.document.v1.GraphNeighborhoodRequest\x1a/.marginal.document.v1.GraphNeighborhoodResponseB/Z-marginal/document-service/genproto/documentv1b\x06proto3"

var (
	file_graph_proto_rawDescOnce sync.Once
	file_graph_proto_rawDescData []byte
)

func file_graph_proto_rawDescGZIP() []byte {
	file_graph_proto_rawDescOnce.Do(func() {
		file_graph_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graph_proto_rawDesc), len(file_graph_proto_rawDesc)))
	})
	return file_graph_proto_rawDescData
}

var file_graph_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_graph_proto_goTypes = []any{
	(*GetLinkGraphRequest)(nil),       // 0: marginal.document.v1.GetLinkGraphRequest
	(*LinkGraph)(nil),                 // 1: marginal.document.v1.LinkGraph
	(*GraphNode)(nil),                 // 2: marginal.document.v1.GraphNode
	(*GraphEdge)(nil),                 // 3: marginal.document.v1.GraphEdge
	(*AnalyzeGraphRequest)(nil),       // 4: marginal.document.v1.AnalyzeGraphRequest
	(*GraphAnalysis)(nil),             // 5: marginal.document.v1.GraphAnalysis
	(*GraphLayer)(nil),                // 6: marginal.document.v1.GraphLayer
	(*BettiNumbers)(nil),              // 7: marginal.document.v1.BettiNumbers
	(*GraphNeighborhoodRequest)(nil),  // 8: marginal.document.v1.GraphNeighborhoodRequest
	(*GraphNeighborhoodResponse)(nil), // 9: marginal.document.v1.GraphNeighborhoodResponse
	(*GraphNeighbour)(nil),            // 10: marginal.document.v1.GraphNeighbour
	(*PathStep)(nil),                  // 11: marginal.document.v1.PathStep
	nil,                               // 12: marginal.document.v1.GraphAnalysis.ComponentOfEntry
	nil,                               // 13: marginal.document.v1.GraphAnalysis.BetweennessEntry
	nil,                               // 14: marginal.document.v1.GraphAnalysis.StronglyConnectedEntry
	nil,                               // 15: marginal.document.v1.GraphNeighborhoodResponse.UndirectedDistanceEntry
	nil,                               // 16: marginal.document.v1.GraphNeighborhoodResponse.ForwardReachableEntry
}
var file_graph_proto_depIdxs = []int32{
	2,  // 0: marginal.document.v1.LinkGraph.nodes:type_name -> marginal.document.v1.GraphNode
	3,  // 1: marginal.document.v1.LinkGraph.edges:type_name -> marginal.document.v1.GraphEdge
	12, // 2: marginal.document.v1.GraphAnalysis.component_of:type_name -> marginal.document.v1.GraphAnalysis.ComponentOfEntry
	7,  // 3: marginal.document.v1.GraphAnalysis.betti:type_name -> marginal.document.v1.BettiNumbers
	13, // 4: marginal.document.v1.GraphAnalysis.betweenness:type_name -> marginal.document.v1.GraphAnalysis.BetweennessEntry
	14, // 5: marginal.document.v1.GraphAnalysis.strongly_connected:type_name -> marginal.document.v1.GraphAnalysis.StronglyConnectedEntry
	6,  // 6: marginal.document.v1.GraphAnalysis.layers:type_name -> marginal.document.v1.GraphLayer
	15, // 7: marginal.document.v1.GraphNeighborhoodResponse.undirected_distance:type_name -> marginal.document.v1.GraphNeighborhoodResponse.UndirectedDistanceEntry
	16, // 8: marginal.document.v1.GraphNeighborhoodResponse.forward_reachable:type_name -> marginal.document.v1.GraphNeighborhoodResponse.ForwardReachableEntry
	10, // 9: marginal.document.v1.GraphNeighborhoodResponse.nearest:type_name -> marginal.document.v1.GraphNeighbour
	11, // 10: marginal.document.v1.GraphNeighborhoodResponse.reading_path:type_name -> marginal.document.v1.PathStep
	0,  // 11: marginal.document.v1.GraphService.GetLinkGraph:input_type -> marginal.document.v1.GetLinkGraphRequest
	4,  // 12: marginal.document.v1.GraphService.AnalyzeGraph:input_type -> marginal.document.v1.AnalyzeGraphRequest
	8,  // 13: marginal.document.v1.GraphService.GraphNeighborhood:input_type -> marginal.document.v1.GraphNeighborhoodRequest
	1,  // 14: marginal.document.v1.GraphService.GetLinkGraph:output_type -> marginal.document.v1.LinkGraph
	5,  // 15: marginal.document.v1.GraphService.AnalyzeGraph:output_type -> marginal.document.v1.GraphAnalysis
	9,  // 16: marginal.document.v1.GraphService.GraphNeighborhood:output_type -> marginal.document.v1.GraphNeighborhoodResponse
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_graph_proto_init() }
func file_graph_proto_init() {
	if File_graph_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graph_proto_rawDesc), len(file_graph_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_graph_proto_goTypes,
		DependencyIndexes: file_graph_proto_depIdxs,
		MessageInfos:      file_graph_proto_msgTypes,
	}.Build()
	File_graph_proto = out.File
	file_graph_proto_goTypes = nil
	file_graph_proto_depIdxs = nil
}
