// GraphService — the gRPC contract for the real [[link]] graph
// (docs/ui-mockups/v2/index.html § 07 GRAPH, graph-algorithms.html). See
// docs/api/graph.md, which this file matches field-for-field.
//
// Read-only and parameter-light on purpose: every algorithm here
// (graphalgo) is a pure function over docs.pages/docs.page_links
// as of right now, computed fresh per request — there is no persisted
// "graph" state of its own to keep consistent, unlike PageService's own
// rows.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.0
// source: graph.proto

package documentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GraphService_GetLinkGraph_FullMethodName      = "/marginal.document.v1.GraphService/GetLinkGraph"
	GraphService_AnalyzeGraph_FullMethodName      = "/marginal.document.v1.GraphService/AnalyzeGraph"
	GraphService_GraphNeighborhood_FullMethodName = "/marginal.document.v1.GraphService/GraphNeighborhood"
)

// GraphServiceClient is the client API for GraphService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GraphServiceClient interface {
	// GetLinkGraph is every live page (a node, even with zero links) and
	// every resolved [[link]] (an edge) — raw data for the client to
	// render (force layout, drawing), never itself an algorithm result.
	GetLinkGraph(ctx context.Context, in *GetLinkGraphRequest, opts ...grpc.CallOption) (*LinkGraph, error)
	// AnalyzeGraph runs every parameter-free algorithm once, over the whole
	// graph: connected components, orphan detection, cycle detection, and
	// diameter (graphalgo).
	AnalyzeGraph(ctx context.Context, in *AnalyzeGraphRequest, opts ...grpc.CallOption) (*GraphAnalysis, error)
	// GraphNeighborhood is the one parameterized view: BFS shortest-path
	// distances (undirected — "link distance" doesn't care which way a
	// link points) and forward reachability ("blast radius," directed —
	// outbound links only) from one chosen source page.
	GraphNeighborhood(ctx context.Context, in *GraphNeighborhoodRequest, opts ...grpc.CallOption) (*GraphNeighborhoodResponse, error)
}

type graphServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGraphServiceClient(cc grpc.ClientConnInterface) GraphServiceClient {
	return &graphServiceClient{cc}
}

func (c *graphServiceClient) GetLinkGraph(ctx context.Context, in *GetLinkGraphRequest, opts ...grpc.CallOption) (*LinkGraph, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinkGraph)
	err := c.cc.Invoke(ctx, GraphService_GetLinkGraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphServiceClient) AnalyzeGraph(ctx context.Context, in *AnalyzeGraphRequest, opts ...grpc.CallOption) (*GraphAnalysis, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GraphAnalysis)
	err := c.cc.Invoke(ctx, GraphService_AnalyzeGraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphServiceClient) GraphNeighborhood(ctx context.Context, in *GraphNeighborhoodRequest, opts ...grpc.CallOption) (*GraphNeighborhoodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GraphNeighborhoodResponse)
	err := c.cc.Invoke(ctx, GraphService_GraphNeighborhood_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GraphServiceServer is the server API for GraphService service.
// All implementations must embed UnimplementedGraphServiceServer
// for forward compatibility.
type GraphServiceServer interface {
	// GetLinkGraph is every live page (a node, even with zero links) and
	// every resolved [[link]] (an edge) — raw data for the client to
	// render (force layout, drawing), never itself an algorithm result.
	GetLinkGraph(context.Context, *GetLinkGraphRequest) (*LinkGraph, error)
	// AnalyzeGraph runs every parameter-free algorithm once, over the whole
	// graph: connected components, orphan detection, cycle detection, and
	// diameter (graphalgo).
	AnalyzeGraph(context.Context, *AnalyzeGraphRequest) (*GraphAnalysis, error)
	// GraphNeighborhood is the one parameterized view: BFS shortest-path
	// distances (undirected — "link distance" doesn't care which way a
	// link points) and forward reachability ("blast radius," directed —
	// outbound links only) from one chosen source page.
	GraphNeighborhood(context.Context, *GraphNeighborhoodRequest) (*GraphNeighborhoodResponse, error)
	mustEmbedUnimplementedGraphServiceServer()
}

// UnimplementedGraphServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGraphServiceServer struct{}

func (UnimplementedGraphServiceServer) GetLinkGraph(context.Context, *GetLinkGraphRequest) (*LinkGraph, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLinkGraph not implemented")
}
func (UnimplementedGraphServiceServer) AnalyzeGraph(context.Context, *AnalyzeGraphRequest) (*GraphAnalysis, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeGraph not implemented")
}
func (UnimplementedGraphServiceServer) GraphNeighborhood(context.Context, *GraphNeighborhoodRequest) (*GraphNeighborhoodResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GraphNeighborhood not implemented")
}
func (UnimplementedGraphServiceServer) mustEmbedUnimplementedGraphServiceServer() {}
func (UnimplementedGraphServiceServer) testEmbeddedByValue()                      {}

// UnsafeGraphServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GraphServiceServer will
// result in compilation errors.
type UnsafeGraphServiceServer interface {
	mustEmbedUnimplementedGraphServiceServer()
}

func RegisterGraphServiceServer(s grpc.ServiceRegistrar, srv GraphServiceServer) {
	// If the following call panics, it indicates UnimplementedGraphServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GraphService_ServiceDesc, srv)
}

func _GraphService_GetLinkGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLinkGraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).GetLinkGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_GetLinkGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).GetLinkGraph(ctx, req.(*GetLinkGraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphService_AnalyzeGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeGraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).AnalyzeGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_AnalyzeGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).AnalyzeGraph(ctx, req.(*AnalyzeGraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphService_GraphNeighborhood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GraphNeighborhoodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).GraphNeighborhood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_GraphNeighborhood_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).GraphNeighborhood(ctx, req.(*GraphNeighborhoodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GraphService_ServiceDesc is the grpc.ServiceDesc for GraphService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GraphService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "marginal.document.v1.GraphService",
	HandlerType: (*GraphServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLinkGraph",
			Handler:    _GraphService_GetLinkGraph_Handler,
		},
		{
			MethodName: "AnalyzeGraph",
			Handler:    _GraphService_AnalyzeGraph_Handler,
		},
		{
			MethodName: "GraphNeighborhood",
			Handler:    _GraphService_GraphNeighborhood_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "graph.proto",
}
