// GraphService — the gRPC contract for the real [[link]] graph
// (docs/ui-mockups/v2/index.html § 07 GRAPH, graph-algorithms.html). See
// docs/api/graph.md, which this file matches field-for-field.
//
// Read-only and parameter-light on purpose: every algorithm here
// (graphalgo) is a pure function over docs.pages/docs.page_links
// as of right now, computed fresh per request — there is no persisted
// "graph" state of its own to keep consistent, unlike PageService's own
// rows.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.0
// source: graph.proto

package documentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLinkGraphRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLinkGraphRequest) Reset() {
	*x = GetLinkGraphRequest{}
	mi := &file_graph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinkGraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkGraphRequest) ProtoMessage() {}

func (x *GetLinkGraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkGraphRequest.ProtoReflect.Descriptor instead.
func (*GetLinkGraphRequest) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{0}
}

type LinkGraph struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*GraphNode           `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*GraphEdge           `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkGraph) Reset() {
	*x = LinkGraph{}
	mi := &file_graph_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkGraph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkGraph) ProtoMessage() {}

func (x *LinkGraph) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkGraph.ProtoReflect.Descriptor instead.
func (*LinkGraph) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{1}
}

func (x *LinkGraph) GetNodes() []*GraphNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *LinkGraph) GetEdges() []*GraphEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type GraphNode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// is_root mirrors graphalgo.Orphans' own root set: a page
	// with no parent, reachable without already knowing another page's
	// title exists.
	IsRoot        bool `protobuf:"varint,3,opt,name=is_root,json=isRoot,proto3" json:"is_root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphNode) Reset() {
	*x = GraphNode{}
	mi := &file_graph_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphNode) ProtoMessage() {}

func (x *GraphNode) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphNode.ProtoReflect.Descriptor instead.
func (*GraphNode) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{2}
}

func (x *GraphNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GraphNode) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GraphNode) GetIsRoot() bool {
	if x != nil {
		return x.IsRoot
	}
	return false
}

type GraphEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromPage      string                 `protobuf:"bytes,1,opt,name=from_page,json=fromPage,proto3" json:"from_page,omitempty"`
	ToPage        string                 `protobuf:"bytes,2,opt,name=to_page,json=toPage,proto3" json:"to_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphEdge) Reset() {
	*x = GraphEdge{}
	mi := &file_graph_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphEdge) ProtoMessage() {}

func (x *GraphEdge) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphEdge.ProtoReflect.Descriptor instead.
func (*GraphEdge) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{3}
}

func (x *GraphEdge) GetFromPage() string {
	if x != nil {
		return x.FromPage
	}
	return ""
}

func (x *GraphEdge) GetToPage() string {
	if x != nil {
		return x.ToPage
	}
	return ""
}

type AnalyzeGraphRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeGraphRequest) Reset() {
	*x = AnalyzeGraphRequest{}
	mi := &file_graph_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeGraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeGraphRequest) ProtoMessage() {}

func (x *AnalyzeGraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeGraphRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeGraphRequest) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{4}
}

type GraphAnalysis struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// component_of maps every page id to its connected-component id
	// (graphalgo.Components, over the undirected projection).
	ComponentOf map[string]int32 `protobuf:"bytes,1,rep,name=component_of,json=componentOf,proto3" json:"component_of,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// orphan_components are component ids containing none of the root
	// pages — graph-algorithms.html's own "a mutually-linked pair with
	// nothing pointing in is still orphaned" argument.
	OrphanComponents []int32 `protobuf:"varint,2,rep,packed,name=orphan_components,json=orphanComponents,proto3" json:"orphan_components,omitempty"`
	// cycle is one example cycle, as an ordered, closed list of page ids
	// (first == last) — empty if the graph is acyclic.
	Cycle    []string `protobuf:"bytes,3,rep,name=cycle,proto3" json:"cycle,omitempty"`
	Diameter int32    `protobuf:"varint,4,opt,name=diameter,proto3" json:"diameter,omitempty"`
	// betti is graph-algorithms.html's own topology panel
	// (graphalgo.Betti) — see BettiNumbers' own field comments for
	// why some of these are graph facts and some are a stated modelling
	// choice (filling every triangle).
	Betti         *BettiNumbers `protobuf:"bytes,5,opt,name=betti,proto3" json:"betti,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphAnalysis) Reset() {
	*x = GraphAnalysis{}
	mi := &file_graph_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphAnalysis) ProtoMessage() {}

func (x *GraphAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphAnalysis.ProtoReflect.Descriptor instead.
func (*GraphAnalysis) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{5}
}

func (x *GraphAnalysis) GetComponentOf() map[string]int32 {
	if x != nil {
		return x.ComponentOf
	}
	return nil
}

func (x *GraphAnalysis) GetOrphanComponents() []int32 {
	if x != nil {
		return x.OrphanComponents
	}
	return nil
}

func (x *GraphAnalysis) GetCycle() []string {
	if x != nil {
		return x.Cycle
	}
	return nil
}

func (x *GraphAnalysis) GetDiameter() int32 {
	if x != nil {
		return x.Diameter
	}
	return 0
}

func (x *GraphAnalysis) GetBetti() *BettiNumbers {
	if x != nil {
		return x.Betti
	}
	return nil
}

type BettiNumbers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	B0            int32                  `protobuf:"varint,1,opt,name=b0,proto3" json:"b0,omitempty"`                             // components
	B1            int32                  `protobuf:"varint,2,opt,name=b1,proto3" json:"b1,omitempty"`                             // cycle rank of the plain graph: E - V + b0
	B1Clique      int32                  `protobuf:"varint,3,opt,name=b1_clique,json=b1Clique,proto3" json:"b1_clique,omitempty"` // b1 minus rank(boundary map ∂2) — the loops surviving after every triangle is filled
	B2            int32                  `protobuf:"varint,4,opt,name=b2,proto3" json:"b2,omitempty"`                             // chi - b0 + b1_clique, read off the Euler characteristic for free
	Chi           int32                  `protobuf:"varint,5,opt,name=chi,proto3" json:"chi,omitempty"`                           // Euler characteristic of the clique complex: V - E + F
	Triangles     int32                  `protobuf:"varint,6,opt,name=triangles,proto3" json:"triangles,omitempty"`               // |F| — how many 3-cliques were filled
	Rank2         int32                  `protobuf:"varint,7,opt,name=rank2,proto3" json:"rank2,omitempty"`                       // rank(∂2) over GF(2) — exactly the loops triangles killed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BettiNumbers) Reset() {
	*x = BettiNumbers{}
	mi := &file_graph_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BettiNumbers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BettiNumbers) ProtoMessage() {}

func (x *BettiNumbers) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BettiNumbers.ProtoReflect.Descriptor instead.
func (*BettiNumbers) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{6}
}

func (x *BettiNumbers) GetB0() int32 {
	if x != nil {
		return x.B0
	}
	return 0
}

func (x *BettiNumbers) GetB1() int32 {
	if x != nil {
		return x.B1
	}
	return 0
}

func (x *BettiNumbers) GetB1Clique() int32 {
	if x != nil {
		return x.B1Clique
	}
	return 0
}

func (x *BettiNumbers) GetB2() int32 {
	if x != nil {
		return x.B2
	}
	return 0
}

func (x *BettiNumbers) GetChi() int32 {
	if x != nil {
		return x.Chi
	}
	return 0
}

func (x *BettiNumbers) GetTriangles() int32 {
	if x != nil {
		return x.Triangles
	}
	return 0
}

func (x *BettiNumbers) GetRank2() int32 {
	if x != nil {
		return x.Rank2
	}
	return 0
}

type GraphNeighborhoodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourcePageId  string                 `protobuf:"bytes,1,opt,name=source_page_id,json=sourcePageId,proto3" json:"source_page_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphNeighborhoodRequest) Reset() {
	*x = GraphNeighborhoodRequest{}
	mi := &file_graph_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphNeighborhoodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphNeighborhoodRequest) ProtoMessage() {}

func (x *GraphNeighborhoodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphNeighborhoodRequest.ProtoReflect.Descriptor instead.
func (*GraphNeighborhoodRequest) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{7}
}

func (x *GraphNeighborhoodRequest) GetSourcePageId() string {
	if x != nil {
		return x.SourcePageId
	}
	return ""
}

type GraphNeighborhoodResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// undirected_distance: link-distance BFS from source_page_id — the
	// page-by-page "wavefront" a client animates one distance value at a
	// time. Absent from the map means unreachable.
	UndirectedDistance map[string]int32 `protobuf:"bytes,1,rep,name=undirected_distance,json=undirectedDistance,proto3" json:"undirected_distance,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// forward_reachable: directed BFS from source_page_id, outbound links
	// only — the blast radius a cascading delete starting there would take
	// with it.
	ForwardReachable map[string]int32 `protobuf:"bytes,2,rep,name=forward_reachable,json=forwardReachable,proto3" json:"forward_reachable,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GraphNeighborhoodResponse) Reset() {
	*x = GraphNeighborhoodResponse{}
	mi := &file_graph_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphNeighborhoodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphNeighborhoodResponse) ProtoMessage() {}

func (x *GraphNeighborhoodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphNeighborhoodResponse.ProtoReflect.Descriptor instead.
func (*GraphNeighborhoodResponse) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{8}
}

func (x *GraphNeighborhoodResponse) GetUndirectedDistance() map[string]int32 {
	if x != nil {
		return x.UndirectedDistance
	}
	return nil
}

func (x *GraphNeighborhoodResponse) GetForwardReachable() map[string]int32 {
	if x != nil {
		return x.ForwardReachable
	}
	return nil
}

var File_graph_proto protoreflect.FileDescriptor

const file_graph_proto_rawDesc = "" +
	"\n" +
	"\vgraph.proto\x12\x14marginal.document.v1\"\x15\n" +
	"\x13GetLinkGraphRequest\"y\n" +
	"\tLinkGraph\x125\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1f.marginal.document.v1.GraphNodeR\x05nodes\x125\n" +
	"\x05edges\x18\x02 \x03(\v2\x1f.marginal.document.v1.GraphEdgeR\x05edges\"J\n" +
	"\tGraphNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x17\n" +
	"\ais_root\x18\x03 \x01(\bR\x06isRoot\"A\n" +
	"\tGraphEdge\x12\x1b\n" +
	"\tfrom_page\x18\x01 \x01(\tR\bfromPage\x12\x17\n" +
	"\ato_page\x18\x02 \x01(\tR\x06toPage\"\x15\n" +
	"\x13AnalyzeGraphRequest\"\xc1\x02\n" +
	"\rGraphAnalysis\x12W\n" +
	"\fcomponent_of\x18\x01 \x03(\v24.marginal.document.v1.GraphAnalysis.ComponentOfEntryR\vcomponentOf\x12+\n" +
	"\x11orphan_components\x18\x02 \x03(\x05R\x10orphanComponents\x12\x14\n" +
	"\x05cycle\x18\x03 \x03(\tR\x05cycle\x12\x1a\n" +
	"\bdiameter\x18\x04 \x01(\x05R\bdiameter\x128\n" +
	"\x05betti\x18\x05 \x01(\v2\".marginal.document.v1.BettiNumbersR\x05betti\x1a>\n" +
	"\x10ComponentOfEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xa1\x01\n" +
	"\fBettiNumbers\x12\x0e\n" +
	"\x02b0\x18\x01 \x01(\x05R\x02b0\x12\x0e\n" +
	"\x02b1\x18\x02 \x01(\x05R\x02b1\x12\x1b\n" +
	"\tb1_clique\x18\x03 \x01(\x05R\bb1Clique\x12\x0e\n" +
	"\x02b2\x18\x04 \x01(\x05R\x02b2\x12\x10\n" +
	"\x03chi\x18\x05 \x01(\x05R\x03chi\x12\x1c\n" +
	"\ttriangles\x18\x06 \x01(\x05R\ttriangles\x12\x14\n" +
	"\x05rank2\x18\a \x01(\x05R\x05rank2\"@\n" +
	"\x18GraphNeighborhoodRequest\x12$\n" +
	"\x0esource_page_id\x18\x01 \x01(\tR\fsourcePageId\"\x95\x03\n" +
	"\x19GraphNeighborhoodResponse\x12x\n" +
	"\x13undirected_distance\x18\x01 \x03(\v2G.marginal.document.v1.GraphNeighborhoodResponse.UndirectedDistanceEntryR\x12undirectedDistance\x12r\n" +
	"\x11forward_reachable\x18\x02 \x03(\v2E.marginal.document.v1.GraphNeighborhoodResponse.ForwardReachableEntryR\x10forwardReachable\x1aE\n" +
	"\x17UndirectedDistanceEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aC\n" +
	"\x15ForwardReachableEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x012\xc0\x02\n" +
	"\fGraphService\x12Z\n" +
	"\fGetLinkGraph\x12).marginal.document.v1.GetLinkGraphRequest\x1a\x1f.marginal.document.v1.LinkGraph\x12^\n" +
	"\fAnalyzeGraph\x12).marginal.document.v1.AnalyzeGraphRequest\x1a#.marginal.document.v1.GraphAnalysis\x12t\n" +
	"\x11GraphNeighborhood\x12..marginal.document.v1.GraphNeighborhoodRequest\x1a/.marginal.document.v1.GraphNeighborhoodResponseB/Z-marginal/document-service/genproto/documentv1b\x06proto3"

var (
	file_graph_proto_rawDescOnce sync.Once
	file_graph_proto_rawDescData []byte
)

func file_graph_proto_rawDescGZIP() []byte {
	file_graph_proto_rawDescOnce.Do(func() {
		file_graph_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graph_proto_rawDesc), len(file_graph_proto_rawDesc)))
	})
	return file_graph_proto_rawDescData
}

var file_graph_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_graph_proto_goTypes = []any{
	(*GetLinkGraphRequest)(nil),       // 0: marginal.document.v1.GetLinkGraphRequest
	(*LinkGraph)(nil),                 // 1: marginal.document.v1.LinkGraph
	(*GraphNode)(nil),                 // 2: marginal.document.v1.GraphNode
	(*GraphEdge)(nil),                 // 3: marginal.document.v1.GraphEdge
	(*AnalyzeGraphRequest)(nil),       // 4: marginal.document.v1.AnalyzeGraphRequest
	(*GraphAnalysis)(nil),             // 5: marginal.document.v1.GraphAnalysis
	(*BettiNumbers)(nil),              // 6: marginal.document.v1.BettiNumbers
	(*GraphNeighborhoodRequest)(nil),  // 7: marginal.document.v1.GraphNeighborhoodRequest
	(*GraphNeighborhoodResponse)(nil), // 8: marginal.document.v1.GraphNeighborhoodResponse
	nil,                               // 9: marginal.document.v1.GraphAnalysis.ComponentOfEntry
	nil,                               // 10: marginal.document.v1.GraphNeighborhoodResponse.UndirectedDistanceEntry
	nil,                               // 11: marginal.document.v1.GraphNeighborhoodResponse.ForwardReachableEntry
}
var file_graph_proto_depIdxs = []int32{
	2,  // 0: marginal.document.v1.LinkGraph.nodes:type_name -> marginal.document.v1.GraphNode
	3,  // 1: marginal.document.v1.LinkGraph.edges:type_name -> marginal.document.v1.GraphEdge
	9,  // 2: marginal.document.v1.GraphAnalysis.component_of:type_name -> marginal.document.v1.GraphAnalysis.ComponentOfEntry
	6,  // 3: marginal.document.v1.GraphAnalysis.betti:type_name -> marginal.document.v1.BettiNumbers
	10, // 4: marginal.document.v1.GraphNeighborhoodResponse.undirected_distance:type_name -> marginal.document.v1.GraphNeighborhoodResponse.UndirectedDistanceEntry
	11, // 5: marginal.document.v1.GraphNeighborhoodResponse.forward_reachable:type_name -> marginal.document.v1.GraphNeighborhoodResponse.ForwardReachableEntry
	0,  // 6: marginal.document.v1.GraphService.GetLinkGraph:input_type -> marginal.document.v1.GetLinkGraphRequest
	4,  // 7: marginal.document.v1.GraphService.AnalyzeGraph:input_type -> marginal.document.v1.AnalyzeGraphRequest
	7,  // 8: marginal.document.v1.GraphService.GraphNeighborhood:input_type -> marginal.document.v1.GraphNeighborhoodRequest
	1,  // 9: marginal.document.v1.GraphService.GetLinkGraph:output_type -> marginal.document.v1.LinkGraph
	5,  // 10: marginal.document.v1.GraphService.AnalyzeGraph:output_type -> marginal.document.v1.GraphAnalysis
	8,  // 11: marginal.document.v1.GraphService.GraphNeighborhood:output_type -> marginal.document.v1.GraphNeighborhoodResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_graph_proto_init() }
func file_graph_proto_init() {
	if File_graph_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graph_proto_rawDesc), len(file_graph_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_graph_proto_goTypes,
		DependencyIndexes: file_graph_proto_depIdxs,
		MessageInfos:      file_graph_proto_msgTypes,
	}.Build()
	File_graph_proto = out.File
	file_graph_proto_goTypes = nil
	file_graph_proto_depIdxs = nil
}
