// SearchService — the gRPC contract for search.html: full-text search
// (docs.pages/docs.blocks' own GIN-indexed tsvector columns, Postgres
// FTS standing in for Tantivy at this repo's scope) plus BK-tree fuzzy
// title matching for "did you mean." See docs/api/search.md, which this
// file matches field-for-field.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.0
// source: search.proto

package documentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hits          []*SearchHit           `protobuf:"bytes,1,rep,name=hits,proto3" json:"hits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResponse) GetHits() []*SearchHit {
	if x != nil {
		return x.Hits
	}
	return nil
}

type SearchHit struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	PageId    string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	PageTitle string                 `protobuf:"bytes,2,opt,name=page_title,json=pageTitle,proto3" json:"page_title,omitempty"`
	// block_id/snippet are set for a hit that matched a block's own text
	// rather than (or in addition to) the page title — absent when only
	// the title matched. snippet is ts_headline's own output: the
	// matching term(s) wrapped in <b>...</b>, the reason this hit matched
	// at all (search.html's own "the snippet shows why it matched").
	BlockId       *string `protobuf:"bytes,3,opt,name=block_id,json=blockId,proto3,oneof" json:"block_id,omitempty"`
	Snippet       *string `protobuf:"bytes,4,opt,name=snippet,proto3,oneof" json:"snippet,omitempty"`
	Rank          float32 `protobuf:"fixed32,5,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHit) Reset() {
	*x = SearchHit{}
	mi := &file_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHit) ProtoMessage() {}

func (x *SearchHit) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHit.ProtoReflect.Descriptor instead.
func (*SearchHit) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchHit) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *SearchHit) GetPageTitle() string {
	if x != nil {
		return x.PageTitle
	}
	return ""
}

func (x *SearchHit) GetBlockId() string {
	if x != nil && x.BlockId != nil {
		return *x.BlockId
	}
	return ""
}

func (x *SearchHit) GetSnippet() string {
	if x != nil && x.Snippet != nil {
		return *x.Snippet
	}
	return ""
}

func (x *SearchHit) GetRank() float32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type SuggestTitlesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Query string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// max_distance bounds the BK-tree query — the same triangle-inequality
	// pruning parameter internal/bktree.Tree.Query takes directly.
	MaxDistance   int32 `protobuf:"varint,2,opt,name=max_distance,json=maxDistance,proto3" json:"max_distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestTitlesRequest) Reset() {
	*x = SuggestTitlesRequest{}
	mi := &file_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestTitlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestTitlesRequest) ProtoMessage() {}

func (x *SuggestTitlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestTitlesRequest.ProtoReflect.Descriptor instead.
func (*SuggestTitlesRequest) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{3}
}

func (x *SuggestTitlesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SuggestTitlesRequest) GetMaxDistance() int32 {
	if x != nil {
		return x.MaxDistance
	}
	return 0
}

type SuggestTitlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suggestions   []*TitleSuggestion     `protobuf:"bytes,1,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestTitlesResponse) Reset() {
	*x = SuggestTitlesResponse{}
	mi := &file_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestTitlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestTitlesResponse) ProtoMessage() {}

func (x *SuggestTitlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestTitlesResponse.ProtoReflect.Descriptor instead.
func (*SuggestTitlesResponse) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{4}
}

func (x *SuggestTitlesResponse) GetSuggestions() []*TitleSuggestion {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

type TitleSuggestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Distance      int32                  `protobuf:"varint,3,opt,name=distance,proto3" json:"distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TitleSuggestion) Reset() {
	*x = TitleSuggestion{}
	mi := &file_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TitleSuggestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TitleSuggestion) ProtoMessage() {}

func (x *TitleSuggestion) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TitleSuggestion.ProtoReflect.Descriptor instead.
func (*TitleSuggestion) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{5}
}

func (x *TitleSuggestion) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *TitleSuggestion) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TitleSuggestion) GetDistance() int32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

var File_search_proto protoreflect.FileDescriptor

const file_search_proto_rawDesc = "" +
	"\n" +
	"\fsearch.proto\x12\x14marginal.document.v1\"%\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"E\n" +
	"\x0eSearchResponse\x123\n" +
	"\x04hits\x18\x01 \x03(\v2\x1f.marginal.document.v1.SearchHitR\x04hits\"\xaf\x01\n" +
	"\tSearchHit\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12\x1d\n" +
	"\n" +
	"page_title\x18\x02 \x01(\tR\tpageTitle\x12\x1e\n" +
	"\bblock_id\x18\x03 \x01(\tH\x00R\ablockId\x88\x01\x01\x12\x1d\n" +
	"\asnippet\x18\x04 \x01(\tH\x01R\asnippet\x88\x01\x01\x12\x12\n" +
	"\x04rank\x18\x05 \x01(\x02R\x04rankB\v\n" +
	"\t_block_idB\n" +
	"\n" +
	"\b_snippet\"O\n" +
	"\x14SuggestTitlesRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12!\n" +
	"\fmax_distance\x18\x02 \x01(\x05R\vmaxDistance\"`\n" +
	"\x15SuggestTitlesResponse\x12G\n" +
	"\vsuggestions\x18\x01 \x03(\v2%.marginal.document.v1.TitleSuggestionR\vsuggestions\"\\\n" +
	"\x0fTitleSuggestion\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bdistance\x18\x03 \x01(\x05R\bdistance2\xce\x01\n" +
	"\rSearchService\x12S\n" +
	"\x06Search\x12#.marginal.document.v1.SearchRequest\x1a$.marginal.document.v1.SearchResponse\x12h\n" +
	"\rSuggestTitles\x12*.marginal.document.v1.SuggestTitlesRequest\x1a+.marginal.document.v1.SuggestTitlesResponseB/Z-marginal/document-service/genproto/documentv1b\x06proto3"

var (
	file_search_proto_rawDescOnce sync.Once
	file_search_proto_rawDescData []byte
)

func file_search_proto_rawDescGZIP() []byte {
	file_search_proto_rawDescOnce.Do(func() {
		file_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_search_proto_rawDesc), len(file_search_proto_rawDesc)))
	})
	return file_search_proto_rawDescData
}

var file_search_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_search_proto_goTypes = []any{
	(*SearchRequest)(nil),         // 0: marginal.document.v1.SearchRequest
	(*SearchResponse)(nil),        // 1: marginal.document.v1.SearchResponse
	(*SearchHit)(nil),             // 2: marginal.document.v1.SearchHit
	(*SuggestTitlesRequest)(nil),  // 3: marginal.document.v1.SuggestTitlesRequest
	(*SuggestTitlesResponse)(nil), // 4: marginal.document.v1.SuggestTitlesResponse
	(*TitleSuggestion)(nil),       // 5: marginal.document.v1.TitleSuggestion
}
var file_search_proto_depIdxs = []int32{
	2, // 0: marginal.document.v1.SearchResponse.hits:type_name -> marginal.document.v1.SearchHit
	5, // 1: marginal.document.v1.SuggestTitlesResponse.suggestions:type_name -> marginal.document.v1.TitleSuggestion
	0, // 2: marginal.document.v1.SearchService.Search:input_type -> marginal.document.v1.SearchRequest
	3, // 3: marginal.document.v1.SearchService.SuggestTitles:input_type -> marginal.document.v1.SuggestTitlesRequest
	1, // 4: marginal.document.v1.SearchService.Search:output_type -> marginal.document.v1.SearchResponse
	4, // 5: marginal.document.v1.SearchService.SuggestTitles:output_type -> marginal.document.v1.SuggestTitlesResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_search_proto_init() }
func file_search_proto_init() {
	if File_search_proto != nil {
		return
	}
	file_search_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_proto_rawDesc), len(file_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_search_proto_goTypes,
		DependencyIndexes: file_search_proto_depIdxs,
		MessageInfos:      file_search_proto_msgTypes,
	}.Build()
	File_search_proto = out.File
	file_search_proto_goTypes = nil
	file_search_proto_depIdxs = nil
}
