// SpaceService — see docs/api/spaces.md, which this file matches
// field-for-field. That doc is the source of truth for semantics; this
// file is its wire encoding.
//
// Owned by auth-service because a membership is a statement about what a
// USER may do (ADR-013 §2). document-service holds a read-model of this,
// fed by the two events below — it decides what you can SEE; this service
// decides what you can DO.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.0
// source: space.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Invitation struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SpaceId string                 `protobuf:"bytes,2,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	// Denormalised for the row that renders this: § 20 shows the space's
	// name and who sent it, and an inbox should not have to make two more
	// calls to say a sentence.
	SpaceName     string                 `protobuf:"bytes,3,opt,name=space_name,json=spaceName,proto3" json:"space_name,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	InvitedBy     string                 `protobuf:"bytes,6,opt,name=invited_by,json=invitedBy,proto3" json:"invited_by,omitempty"`
	InvitedByName string                 `protobuf:"bytes,7,opt,name=invited_by_name,json=invitedByName,proto3" json:"invited_by_name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Absent while pending. Present with `accepted` once answered — a
	// DECLINE is recorded, not deleted, so "never sent" and "refused" stay
	// distinguishable.
	RespondedAt   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=responded_at,json=respondedAt,proto3" json:"responded_at,omitempty"`
	Accepted      bool                   `protobuf:"varint,10,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invitation) Reset() {
	*x = Invitation{}
	mi := &file_space_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invitation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invitation) ProtoMessage() {}

func (x *Invitation) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invitation.ProtoReflect.Descriptor instead.
func (*Invitation) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{0}
}

func (x *Invitation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Invitation) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *Invitation) GetSpaceName() string {
	if x != nil {
		return x.SpaceName
	}
	return ""
}

func (x *Invitation) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Invitation) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Invitation) GetInvitedBy() string {
	if x != nil {
		return x.InvitedBy
	}
	return ""
}

func (x *Invitation) GetInvitedByName() string {
	if x != nil {
		return x.InvitedByName
	}
	return ""
}

func (x *Invitation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Invitation) GetRespondedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RespondedAt
	}
	return nil
}

func (x *Invitation) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type InviteMemberRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	SpaceId string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	// Somebody who already has an account here. Inviting an address with no
	// account needs email delivery and a signup that consumes a token —
	// a different feature, and § 20 depicts neither.
	UserId        string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"` // viewer | editor | admin
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteMemberRequest) Reset() {
	*x = InviteMemberRequest{}
	mi := &file_space_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteMemberRequest) ProtoMessage() {}

func (x *InviteMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteMemberRequest.ProtoReflect.Descriptor instead.
func (*InviteMemberRequest) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{1}
}

func (x *InviteMemberRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *InviteMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InviteMemberRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type RespondToInvitationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvitationId  string                 `protobuf:"bytes,1,opt,name=invitation_id,json=invitationId,proto3" json:"invitation_id,omitempty"`
	Accept        bool                   `protobuf:"varint,2,opt,name=accept,proto3" json:"accept,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondToInvitationRequest) Reset() {
	*x = RespondToInvitationRequest{}
	mi := &file_space_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondToInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondToInvitationRequest) ProtoMessage() {}

func (x *RespondToInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondToInvitationRequest.ProtoReflect.Descriptor instead.
func (*RespondToInvitationRequest) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{2}
}

func (x *RespondToInvitationRequest) GetInvitationId() string {
	if x != nil {
		return x.InvitationId
	}
	return ""
}

func (x *RespondToInvitationRequest) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

type ListInvitationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvitationsRequest) Reset() {
	*x = ListInvitationsRequest{}
	mi := &file_space_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvitationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvitationsRequest) ProtoMessage() {}

func (x *ListInvitationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvitationsRequest.ProtoReflect.Descriptor instead.
func (*ListInvitationsRequest) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{3}
}

type ListInvitationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invitations   []*Invitation          `protobuf:"bytes,1,rep,name=invitations,proto3" json:"invitations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvitationsResponse) Reset() {
	*x = ListInvitationsResponse{}
	mi := &file_space_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvitationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvitationsResponse) ProtoMessage() {}

func (x *ListInvitationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvitationsResponse.ProtoReflect.Descriptor instead.
func (*ListInvitationsResponse) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{4}
}

func (x *ListInvitationsResponse) GetInvitations() []*Invitation {
	if x != nil {
		return x.Invitations
	}
	return nil
}

type Space struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUIDv7
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The space every pre-v3.1.0 page was migrated into. It cannot be
	// deleted — doing so would orphan every page written before spaces
	// existed.
	IsDefault bool                   `protobuf:"varint,3,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	CreatedBy string                 `protobuf:"bytes,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// What the CALLER may do here — not "the space's role", which is why the
	// field is named this way. A client caching a field called `role`
	// against a space id would be caching one person's answer under a key
	// that suggests it is everyone's.
	YourRole      string `protobuf:"bytes,6,opt,name=your_role,json=yourRole,proto3" json:"your_role,omitempty"` // viewer | editor | admin
	Members       int32  `protobuf:"varint,7,opt,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Space) Reset() {
	*x = Space{}
	mi := &file_space_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Space) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Space) ProtoMessage() {}

func (x *Space) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Space.ProtoReflect.Descriptor instead.
func (*Space) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{5}
}

func (x *Space) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Space) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Space) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *Space) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Space) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Space) GetYourRole() string {
	if x != nil {
		return x.YourRole
	}
	return ""
}

func (x *Space) GetMembers() int32 {
	if x != nil {
		return x.Members
	}
	return 0
}

type Membership struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SpaceId       string                 `protobuf:"bytes,2,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	DisplayName   string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"` // joined from auth.users, for the screen
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Membership) Reset() {
	*x = Membership{}
	mi := &file_space_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Membership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Membership) ProtoMessage() {}

func (x *Membership) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Membership.ProtoReflect.Descriptor instead.
func (*Membership) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{6}
}

func (x *Membership) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Membership) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *Membership) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Membership) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Membership) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Membership) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListSpacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSpacesRequest) Reset() {
	*x = ListSpacesRequest{}
	mi := &file_space_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSpacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSpacesRequest) ProtoMessage() {}

func (x *ListSpacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSpacesRequest.ProtoReflect.Descriptor instead.
func (*ListSpacesRequest) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{7}
}

type ListSpacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spaces        []*Space               `protobuf:"bytes,1,rep,name=spaces,proto3" json:"spaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSpacesResponse) Reset() {
	*x = ListSpacesResponse{}
	mi := &file_space_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSpacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSpacesResponse) ProtoMessage() {}

func (x *ListSpacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSpacesResponse.ProtoReflect.Descriptor instead.
func (*ListSpacesResponse) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{8}
}

func (x *ListSpacesResponse) GetSpaces() []*Space {
	if x != nil {
		return x.Spaces
	}
	return nil
}

type CreateSpaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSpaceRequest) Reset() {
	*x = CreateSpaceRequest{}
	mi := &file_space_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSpaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSpaceRequest) ProtoMessage() {}

func (x *CreateSpaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSpaceRequest.ProtoReflect.Descriptor instead.
func (*CreateSpaceRequest) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{9}
}

func (x *CreateSpaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersRequest) Reset() {
	*x = ListMembersRequest{}
	mi := &file_space_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersRequest) ProtoMessage() {}

func (x *ListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersRequest.ProtoReflect.Descriptor instead.
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{10}
}

func (x *ListMembersRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

type ListMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*Membership          `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersResponse) Reset() {
	*x = ListMembersResponse{}
	mi := &file_space_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersResponse) ProtoMessage() {}

func (x *ListMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersResponse.ProtoReflect.Descriptor instead.
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{11}
}

func (x *ListMembersResponse) GetMembers() []*Membership {
	if x != nil {
		return x.Members
	}
	return nil
}

type GrantRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"` // viewer | editor | admin
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantRoleRequest) Reset() {
	*x = GrantRoleRequest{}
	mi := &file_space_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantRoleRequest) ProtoMessage() {}

func (x *GrantRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantRoleRequest.ProtoReflect.Descriptor instead.
func (*GrantRoleRequest) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{12}
}

func (x *GrantRoleRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *GrantRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GrantRoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type RevokeRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRoleRequest) Reset() {
	*x = RevokeRoleRequest{}
	mi := &file_space_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRoleRequest) ProtoMessage() {}

func (x *RevokeRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRoleRequest.ProtoReflect.Descriptor instead.
func (*RevokeRoleRequest) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{13}
}

func (x *RevokeRoleRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *RevokeRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListAllMembershipsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllMembershipsRequest) Reset() {
	*x = ListAllMembershipsRequest{}
	mi := &file_space_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllMembershipsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllMembershipsRequest) ProtoMessage() {}

func (x *ListAllMembershipsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllMembershipsRequest.ProtoReflect.Descriptor instead.
func (*ListAllMembershipsRequest) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{14}
}

type ListAllMembershipsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memberships   []*Membership          `protobuf:"bytes,1,rep,name=memberships,proto3" json:"memberships,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllMembershipsResponse) Reset() {
	*x = ListAllMembershipsResponse{}
	mi := &file_space_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllMembershipsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllMembershipsResponse) ProtoMessage() {}

func (x *ListAllMembershipsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllMembershipsResponse.ProtoReflect.Descriptor instead.
func (*ListAllMembershipsResponse) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{15}
}

func (x *ListAllMembershipsResponse) GetMemberships() []*Membership {
	if x != nil {
		return x.Memberships
	}
	return nil
}

var File_space_proto protoreflect.FileDescriptor

const file_space_proto_rawDesc = "" +
	"\n" +
	"\vspace.proto\x12\x10marginal.auth.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe0\x02\n" +
	"\n" +
	"Invitation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bspace_id\x18\x02 \x01(\tR\aspaceId\x12\x1d\n" +
	"\n" +
	"space_name\x18\x03 \x01(\tR\tspaceName\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"invited_by\x18\x06 \x01(\tR\tinvitedBy\x12&\n" +
	"\x0finvited_by_name\x18\a \x01(\tR\rinvitedByName\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fresponded_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vrespondedAt\x12\x1a\n" +
	"\baccepted\x18\n" +
	" \x01(\bR\baccepted\"]\n" +
	"\x13InviteMemberRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"Y\n" +
	"\x1aRespondToInvitationRequest\x12#\n" +
	"\rinvitation_id\x18\x01 \x01(\tR\finvitationId\x12\x16\n" +
	"\x06accept\x18\x02 \x01(\bR\x06accept\"\x18\n" +
	"\x16ListInvitationsRequest\"Y\n" +
	"\x17ListInvitationsResponse\x12>\n" +
	"\vinvitations\x18\x01 \x03(\v2\x1c.marginal.auth.v1.InvitationR\vinvitations\"\xdb\x01\n" +
	"\x05Space\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"is_default\x18\x03 \x01(\bR\tisDefault\x12\x1d\n" +
	"\n" +
	"created_by\x18\x04 \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1b\n" +
	"\tyour_role\x18\x06 \x01(\tR\byourRole\x12\x18\n" +
	"\amembers\x18\a \x01(\x05R\amembers\"\xc8\x01\n" +
	"\n" +
	"Membership\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bspace_id\x18\x02 \x01(\tR\aspaceId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x13\n" +
	"\x11ListSpacesRequest\"E\n" +
	"\x12ListSpacesResponse\x12/\n" +
	"\x06spaces\x18\x01 \x03(\v2\x17.marginal.auth.v1.SpaceR\x06spaces\"(\n" +
	"\x12CreateSpaceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"/\n" +
	"\x12ListMembersRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\"M\n" +
	"\x13ListMembersResponse\x126\n" +
	"\amembers\x18\x01 \x03(\v2\x1c.marginal.auth.v1.MembershipR\amembers\"Z\n" +
	"\x10GrantRoleRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"G\n" +
	"\x11RevokeRoleRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x1b\n" +
	"\x19ListAllMembershipsRequest\"\\\n" +
	"\x1aListAllMembershipsResponse\x12>\n" +
	"\vmemberships\x18\x01 \x03(\v2\x1c.marginal.auth.v1.MembershipR\vmemberships2\xbc\x06\n" +
	"\fSpaceService\x12W\n" +
	"\n" +
	"ListSpaces\x12#.marginal.auth.v1.ListSpacesRequest\x1a$.marginal.auth.v1.ListSpacesResponse\x12L\n" +
	"\vCreateSpace\x12$.marginal.auth.v1.CreateSpaceRequest\x1a\x17.marginal.auth.v1.Space\x12Z\n" +
	"\vListMembers\x12$.marginal.auth.v1.ListMembersRequest\x1a%.marginal.auth.v1.ListMembersResponse\x12M\n" +
	"\tGrantRole\x12\".marginal.auth.v1.GrantRoleRequest\x1a\x1c.marginal.auth.v1.Membership\x12I\n" +
	"\n" +
	"RevokeRole\x12#.marginal.auth.v1.RevokeRoleRequest\x1a\x16.google.protobuf.Empty\x12o\n" +
	"\x12ListAllMemberships\x12+.marginal.auth.v1.ListAllMembershipsRequest\x1a,.marginal.auth.v1.ListAllMembershipsResponse\x12S\n" +
	"\fInviteMember\x12%.marginal.auth.v1.InviteMemberRequest\x1a\x1c.marginal.auth.v1.Invitation\x12a\n" +
	"\x13RespondToInvitation\x12,.marginal.auth.v1.RespondToInvitationRequest\x1a\x1c.marginal.auth.v1.Invitation\x12f\n" +
	"\x0fListInvitations\x12(.marginal.auth.v1.ListInvitationsRequest\x1a).marginal.auth.v1.ListInvitationsResponseB'Z%marginal/auth-service/genproto/authv1b\x06proto3"

var (
	file_space_proto_rawDescOnce sync.Once
	file_space_proto_rawDescData []byte
)

func file_space_proto_rawDescGZIP() []byte {
	file_space_proto_rawDescOnce.Do(func() {
		file_space_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_space_proto_rawDesc), len(file_space_proto_rawDesc)))
	})
	return file_space_proto_rawDescData
}

var file_space_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_space_proto_goTypes = []any{
	(*Invitation)(nil),                 // 0: marginal.auth.v1.Invitation
	(*InviteMemberRequest)(nil),        // 1: marginal.auth.v1.InviteMemberRequest
	(*RespondToInvitationRequest)(nil), // 2: marginal.auth.v1.RespondToInvitationRequest
	(*ListInvitationsRequest)(nil),     // 3: marginal.auth.v1.ListInvitationsRequest
	(*ListInvitationsResponse)(nil),    // 4: marginal.auth.v1.ListInvitationsResponse
	(*Space)(nil),                      // 5: marginal.auth.v1.Space
	(*Membership)(nil),                 // 6: marginal.auth.v1.Membership
	(*ListSpacesRequest)(nil),          // 7: marginal.auth.v1.ListSpacesRequest
	(*ListSpacesResponse)(nil),         // 8: marginal.auth.v1.ListSpacesResponse
	(*CreateSpaceRequest)(nil),         // 9: marginal.auth.v1.CreateSpaceRequest
	(*ListMembersRequest)(nil),         // 10: marginal.auth.v1.ListMembersRequest
	(*ListMembersResponse)(nil),        // 11: marginal.auth.v1.ListMembersResponse
	(*GrantRoleRequest)(nil),           // 12: marginal.auth.v1.GrantRoleRequest
	(*RevokeRoleRequest)(nil),          // 13: marginal.auth.v1.RevokeRoleRequest
	(*ListAllMembershipsRequest)(nil),  // 14: marginal.auth.v1.ListAllMembershipsRequest
	(*ListAllMembershipsResponse)(nil), // 15: marginal.auth.v1.ListAllMembershipsResponse
	(*timestamppb.Timestamp)(nil),      // 16: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 17: google.protobuf.Empty
}
var file_space_proto_depIdxs = []int32{
	16, // 0: marginal.auth.v1.Invitation.created_at:type_name -> google.protobuf.Timestamp
	16, // 1: marginal.auth.v1.Invitation.responded_at:type_name -> google.protobuf.Timestamp
	0,  // 2: marginal.auth.v1.ListInvitationsResponse.invitations:type_name -> marginal.auth.v1.Invitation
	16, // 3: marginal.auth.v1.Space.created_at:type_name -> google.protobuf.Timestamp
	16, // 4: marginal.auth.v1.Membership.created_at:type_name -> google.protobuf.Timestamp
	5,  // 5: marginal.auth.v1.ListSpacesResponse.spaces:type_name -> marginal.auth.v1.Space
	6,  // 6: marginal.auth.v1.ListMembersResponse.members:type_name -> marginal.auth.v1.Membership
	6,  // 7: marginal.auth.v1.ListAllMembershipsResponse.memberships:type_name -> marginal.auth.v1.Membership
	7,  // 8: marginal.auth.v1.SpaceService.ListSpaces:input_type -> marginal.auth.v1.ListSpacesRequest
	9,  // 9: marginal.auth.v1.SpaceService.CreateSpace:input_type -> marginal.auth.v1.CreateSpaceRequest
	10, // 10: marginal.auth.v1.SpaceService.ListMembers:input_type -> marginal.auth.v1.ListMembersRequest
	12, // 11: marginal.auth.v1.SpaceService.GrantRole:input_type -> marginal.auth.v1.GrantRoleRequest
	13, // 12: marginal.auth.v1.SpaceService.RevokeRole:input_type -> marginal.auth.v1.RevokeRoleRequest
	14, // 13: marginal.auth.v1.SpaceService.ListAllMemberships:input_type -> marginal.auth.v1.ListAllMembershipsRequest
	1,  // 14: marginal.auth.v1.SpaceService.InviteMember:input_type -> marginal.auth.v1.InviteMemberRequest
	2,  // 15: marginal.auth.v1.SpaceService.RespondToInvitation:input_type -> marginal.auth.v1.RespondToInvitationRequest
	3,  // 16: marginal.auth.v1.SpaceService.ListInvitations:input_type -> marginal.auth.v1.ListInvitationsRequest
	8,  // 17: marginal.auth.v1.SpaceService.ListSpaces:output_type -> marginal.auth.v1.ListSpacesResponse
	5,  // 18: marginal.auth.v1.SpaceService.CreateSpace:output_type -> marginal.auth.v1.Space
	11, // 19: marginal.auth.v1.SpaceService.ListMembers:output_type -> marginal.auth.v1.ListMembersResponse
	6,  // 20: marginal.auth.v1.SpaceService.GrantRole:output_type -> marginal.auth.v1.Membership
	17, // 21: marginal.auth.v1.SpaceService.RevokeRole:output_type -> google.protobuf.Empty
	15, // 22: marginal.auth.v1.SpaceService.ListAllMemberships:output_type -> marginal.auth.v1.ListAllMembershipsResponse
	0,  // 23: marginal.auth.v1.SpaceService.InviteMember:output_type -> marginal.auth.v1.Invitation
	0,  // 24: marginal.auth.v1.SpaceService.RespondToInvitation:output_type -> marginal.auth.v1.Invitation
	4,  // 25: marginal.auth.v1.SpaceService.ListInvitations:output_type -> marginal.auth.v1.ListInvitationsResponse
	17, // [17:26] is the sub-list for method output_type
	8,  // [8:17] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_space_proto_init() }
func file_space_proto_init() {
	if File_space_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_space_proto_rawDesc), len(file_space_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_space_proto_goTypes,
		DependencyIndexes: file_space_proto_depIdxs,
		MessageInfos:      file_space_proto_msgTypes,
	}.Build()
	File_space_proto = out.File
	file_space_proto_goTypes = nil
	file_space_proto_depIdxs = nil
}
