// SpaceService — see docs/api/spaces.md, which this file matches
// field-for-field. That doc is the source of truth for semantics; this
// file is its wire encoding.
//
// Owned by auth-service because a membership is a statement about what a
// USER may do (ADR-013 §2). document-service holds a read-model of this,
// fed by the two events below — it decides what you can SEE; this service
// decides what you can DO.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.0
// source: space.proto

package authv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SpaceService_ListSpaces_FullMethodName          = "/marginal.auth.v1.SpaceService/ListSpaces"
	SpaceService_CreateSpace_FullMethodName         = "/marginal.auth.v1.SpaceService/CreateSpace"
	SpaceService_ListMembers_FullMethodName         = "/marginal.auth.v1.SpaceService/ListMembers"
	SpaceService_GrantRole_FullMethodName           = "/marginal.auth.v1.SpaceService/GrantRole"
	SpaceService_RevokeRole_FullMethodName          = "/marginal.auth.v1.SpaceService/RevokeRole"
	SpaceService_ListAllMemberships_FullMethodName  = "/marginal.auth.v1.SpaceService/ListAllMemberships"
	SpaceService_InviteMember_FullMethodName        = "/marginal.auth.v1.SpaceService/InviteMember"
	SpaceService_RespondToInvitation_FullMethodName = "/marginal.auth.v1.SpaceService/RespondToInvitation"
	SpaceService_ListInvitations_FullMethodName     = "/marginal.auth.v1.SpaceService/ListInvitations"
)

// SpaceServiceClient is the client API for SpaceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpaceServiceClient interface {
	// Every space the CALLER is in, with the caller's own role in each.
	// Never every space that exists: that is an admin question, and
	// answering it here would leak the existence of spaces you are not in
	// — space names are chosen by people and often say what a team is doing.
	ListSpaces(ctx context.Context, in *ListSpacesRequest, opts ...grpc.CallOption) (*ListSpacesResponse, error)
	CreateSpace(ctx context.Context, in *CreateSpaceRequest, opts ...grpc.CallOption) (*Space, error)
	// The three below need the caller to be an ADMIN of space_id. A space
	// the caller is not in answers NOT_FOUND rather than PERMISSION_DENIED:
	// 403 on a resource you cannot see confirms it exists, and is only safe
	// once "it exists" is already known to you (docs/api/spaces.md §3).
	ListMembers(ctx context.Context, in *ListMembersRequest, opts ...grpc.CallOption) (*ListMembersResponse, error)
	GrantRole(ctx context.Context, in *GrantRoleRequest, opts ...grpc.CallOption) (*Membership, error)
	RevokeRole(ctx context.Context, in *RevokeRoleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// The whole membership set, for document-service's periodic reconcile
	// against this source of truth (DATA_MODEL.md § docs.space_members).
	// An event bus with no redelivery needs a floor under how wrong its
	// projection can get. Not a user-facing call.
	ListAllMemberships(ctx context.Context, in *ListAllMembershipsRequest, opts ...grpc.CallOption) (*ListAllMembershipsResponse, error)
	// Invitations (v3.3.0, ADR-013's now-decided flow; docs/api/spaces.md §5).
	//
	// An invitation is NOT a membership: it lives in its own table, and
	// accepting one is what performs the grant. That split is deliberate —
	// a membership carrying an "accepted" flag would put the invitation on
	// the hot path of every role check in the system.
	InviteMember(ctx context.Context, in *InviteMemberRequest, opts ...grpc.CallOption) (*Invitation, error)
	RespondToInvitation(ctx context.Context, in *RespondToInvitationRequest, opts ...grpc.CallOption) (*Invitation, error)
	// The caller's own pending invitations. Scoped by their token, never by
	// a parameter — a user_id argument here would be somebody else's inbox.
	ListInvitations(ctx context.Context, in *ListInvitationsRequest, opts ...grpc.CallOption) (*ListInvitationsResponse, error)
}

type spaceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSpaceServiceClient(cc grpc.ClientConnInterface) SpaceServiceClient {
	return &spaceServiceClient{cc}
}

func (c *spaceServiceClient) ListSpaces(ctx context.Context, in *ListSpacesRequest, opts ...grpc.CallOption) (*ListSpacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSpacesResponse)
	err := c.cc.Invoke(ctx, SpaceService_ListSpaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceServiceClient) CreateSpace(ctx context.Context, in *CreateSpaceRequest, opts ...grpc.CallOption) (*Space, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Space)
	err := c.cc.Invoke(ctx, SpaceService_CreateSpace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceServiceClient) ListMembers(ctx context.Context, in *ListMembersRequest, opts ...grpc.CallOption) (*ListMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMembersResponse)
	err := c.cc.Invoke(ctx, SpaceService_ListMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceServiceClient) GrantRole(ctx context.Context, in *GrantRoleRequest, opts ...grpc.CallOption) (*Membership, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Membership)
	err := c.cc.Invoke(ctx, SpaceService_GrantRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceServiceClient) RevokeRole(ctx context.Context, in *RevokeRoleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SpaceService_RevokeRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceServiceClient) ListAllMemberships(ctx context.Context, in *ListAllMembershipsRequest, opts ...grpc.CallOption) (*ListAllMembershipsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAllMembershipsResponse)
	err := c.cc.Invoke(ctx, SpaceService_ListAllMemberships_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceServiceClient) InviteMember(ctx context.Context, in *InviteMemberRequest, opts ...grpc.CallOption) (*Invitation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Invitation)
	err := c.cc.Invoke(ctx, SpaceService_InviteMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceServiceClient) RespondToInvitation(ctx context.Context, in *RespondToInvitationRequest, opts ...grpc.CallOption) (*Invitation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Invitation)
	err := c.cc.Invoke(ctx, SpaceService_RespondToInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceServiceClient) ListInvitations(ctx context.Context, in *ListInvitationsRequest, opts ...grpc.CallOption) (*ListInvitationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInvitationsResponse)
	err := c.cc.Invoke(ctx, SpaceService_ListInvitations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpaceServiceServer is the server API for SpaceService service.
// All implementations must embed UnimplementedSpaceServiceServer
// for forward compatibility.
type SpaceServiceServer interface {
	// Every space the CALLER is in, with the caller's own role in each.
	// Never every space that exists: that is an admin question, and
	// answering it here would leak the existence of spaces you are not in
	// — space names are chosen by people and often say what a team is doing.
	ListSpaces(context.Context, *ListSpacesRequest) (*ListSpacesResponse, error)
	CreateSpace(context.Context, *CreateSpaceRequest) (*Space, error)
	// The three below need the caller to be an ADMIN of space_id. A space
	// the caller is not in answers NOT_FOUND rather than PERMISSION_DENIED:
	// 403 on a resource you cannot see confirms it exists, and is only safe
	// once "it exists" is already known to you (docs/api/spaces.md §3).
	ListMembers(context.Context, *ListMembersRequest) (*ListMembersResponse, error)
	GrantRole(context.Context, *GrantRoleRequest) (*Membership, error)
	RevokeRole(context.Context, *RevokeRoleRequest) (*emptypb.Empty, error)
	// The whole membership set, for document-service's periodic reconcile
	// against this source of truth (DATA_MODEL.md § docs.space_members).
	// An event bus with no redelivery needs a floor under how wrong its
	// projection can get. Not a user-facing call.
	ListAllMemberships(context.Context, *ListAllMembershipsRequest) (*ListAllMembershipsResponse, error)
	// Invitations (v3.3.0, ADR-013's now-decided flow; docs/api/spaces.md §5).
	//
	// An invitation is NOT a membership: it lives in its own table, and
	// accepting one is what performs the grant. That split is deliberate —
	// a membership carrying an "accepted" flag would put the invitation on
	// the hot path of every role check in the system.
	InviteMember(context.Context, *InviteMemberRequest) (*Invitation, error)
	RespondToInvitation(context.Context, *RespondToInvitationRequest) (*Invitation, error)
	// The caller's own pending invitations. Scoped by their token, never by
	// a parameter — a user_id argument here would be somebody else's inbox.
	ListInvitations(context.Context, *ListInvitationsRequest) (*ListInvitationsResponse, error)
	mustEmbedUnimplementedSpaceServiceServer()
}

// UnimplementedSpaceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpaceServiceServer struct{}

func (UnimplementedSpaceServiceServer) ListSpaces(context.Context, *ListSpacesRequest) (*ListSpacesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSpaces not implemented")
}
func (UnimplementedSpaceServiceServer) CreateSpace(context.Context, *CreateSpaceRequest) (*Space, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSpace not implemented")
}
func (UnimplementedSpaceServiceServer) ListMembers(context.Context, *ListMembersRequest) (*ListMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMembers not implemented")
}
func (UnimplementedSpaceServiceServer) GrantRole(context.Context, *GrantRoleRequest) (*Membership, error) {
	return nil, status.Error(codes.Unimplemented, "method GrantRole not implemented")
}
func (UnimplementedSpaceServiceServer) RevokeRole(context.Context, *RevokeRoleRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeRole not implemented")
}
func (UnimplementedSpaceServiceServer) ListAllMemberships(context.Context, *ListAllMembershipsRequest) (*ListAllMembershipsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAllMemberships not implemented")
}
func (UnimplementedSpaceServiceServer) InviteMember(context.Context, *InviteMemberRequest) (*Invitation, error) {
	return nil, status.Error(codes.Unimplemented, "method InviteMember not implemented")
}
func (UnimplementedSpaceServiceServer) RespondToInvitation(context.Context, *RespondToInvitationRequest) (*Invitation, error) {
	return nil, status.Error(codes.Unimplemented, "method RespondToInvitation not implemented")
}
func (UnimplementedSpaceServiceServer) ListInvitations(context.Context, *ListInvitationsRequest) (*ListInvitationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInvitations not implemented")
}
func (UnimplementedSpaceServiceServer) mustEmbedUnimplementedSpaceServiceServer() {}
func (UnimplementedSpaceServiceServer) testEmbeddedByValue()                      {}

// UnsafeSpaceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpaceServiceServer will
// result in compilation errors.
type UnsafeSpaceServiceServer interface {
	mustEmbedUnimplementedSpaceServiceServer()
}

func RegisterSpaceServiceServer(s grpc.ServiceRegistrar, srv SpaceServiceServer) {
	// If the following call panics, it indicates UnimplementedSpaceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpaceService_ServiceDesc, srv)
}

func _SpaceService_ListSpaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSpacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceServiceServer).ListSpaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpaceService_ListSpaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceServiceServer).ListSpaces(ctx, req.(*ListSpacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceService_CreateSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSpaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceServiceServer).CreateSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpaceService_CreateSpace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceServiceServer).CreateSpace(ctx, req.(*CreateSpaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceService_ListMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceServiceServer).ListMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpaceService_ListMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceServiceServer).ListMembers(ctx, req.(*ListMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceService_GrantRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceServiceServer).GrantRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpaceService_GrantRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceServiceServer).GrantRole(ctx, req.(*GrantRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceService_RevokeRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceServiceServer).RevokeRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpaceService_RevokeRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceServiceServer).RevokeRole(ctx, req.(*RevokeRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceService_ListAllMemberships_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAllMembershipsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceServiceServer).ListAllMemberships(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpaceService_ListAllMemberships_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceServiceServer).ListAllMemberships(ctx, req.(*ListAllMembershipsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceService_InviteMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceServiceServer).InviteMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpaceService_InviteMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceServiceServer).InviteMember(ctx, req.(*InviteMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceService_RespondToInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RespondToInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceServiceServer).RespondToInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpaceService_RespondToInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceServiceServer).RespondToInvitation(ctx, req.(*RespondToInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceService_ListInvitations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInvitationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceServiceServer).ListInvitations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpaceService_ListInvitations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceServiceServer).ListInvitations(ctx, req.(*ListInvitationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SpaceService_ServiceDesc is the grpc.ServiceDesc for SpaceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpaceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "marginal.auth.v1.SpaceService",
	HandlerType: (*SpaceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSpaces",
			Handler:    _SpaceService_ListSpaces_Handler,
		},
		{
			MethodName: "CreateSpace",
			Handler:    _SpaceService_CreateSpace_Handler,
		},
		{
			MethodName: "ListMembers",
			Handler:    _SpaceService_ListMembers_Handler,
		},
		{
			MethodName: "GrantRole",
			Handler:    _SpaceService_GrantRole_Handler,
		},
		{
			MethodName: "RevokeRole",
			Handler:    _SpaceService_RevokeRole_Handler,
		},
		{
			MethodName: "ListAllMemberships",
			Handler:    _SpaceService_ListAllMemberships_Handler,
		},
		{
			MethodName: "InviteMember",
			Handler:    _SpaceService_InviteMember_Handler,
		},
		{
			MethodName: "RespondToInvitation",
			Handler:    _SpaceService_RespondToInvitation_Handler,
		},
		{
			MethodName: "ListInvitations",
			Handler:    _SpaceService_ListInvitations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "space.proto",
}
