// SpaceService — see docs/api/spaces.md, which this file matches
// field-for-field. That doc is the source of truth for semantics; this
// file is its wire encoding.
//
// Owned by auth-service because a membership is a statement about what a
// USER may do (ADR-013 §2). document-service holds a read-model of this,
// fed by the two events below — it decides what you can SEE; this service
// decides what you can DO.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.0
// source: space.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Space struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUIDv7
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The space every pre-v3.1.0 page was migrated into. It cannot be
	// deleted — doing so would orphan every page written before spaces
	// existed.
	IsDefault bool                   `protobuf:"varint,3,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	CreatedBy string                 `protobuf:"bytes,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// What the CALLER may do here — not "the space's role", which is why the
	// field is named this way. A client caching a field called `role`
	// against a space id would be caching one person's answer under a key
	// that suggests it is everyone's.
	YourRole      string `protobuf:"bytes,6,opt,name=your_role,json=yourRole,proto3" json:"your_role,omitempty"` // viewer | editor | admin
	Members       int32  `protobuf:"varint,7,opt,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Space) Reset() {
	*x = Space{}
	mi := &file_space_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Space) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Space) ProtoMessage() {}

func (x *Space) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Space.ProtoReflect.Descriptor instead.
func (*Space) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{0}
}

func (x *Space) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Space) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Space) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *Space) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Space) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Space) GetYourRole() string {
	if x != nil {
		return x.YourRole
	}
	return ""
}

func (x *Space) GetMembers() int32 {
	if x != nil {
		return x.Members
	}
	return 0
}

type Membership struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SpaceId       string                 `protobuf:"bytes,2,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	DisplayName   string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"` // joined from auth.users, for the screen
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Membership) Reset() {
	*x = Membership{}
	mi := &file_space_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Membership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Membership) ProtoMessage() {}

func (x *Membership) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Membership.ProtoReflect.Descriptor instead.
func (*Membership) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{1}
}

func (x *Membership) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Membership) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *Membership) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Membership) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Membership) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Membership) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListSpacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSpacesRequest) Reset() {
	*x = ListSpacesRequest{}
	mi := &file_space_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSpacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSpacesRequest) ProtoMessage() {}

func (x *ListSpacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSpacesRequest.ProtoReflect.Descriptor instead.
func (*ListSpacesRequest) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{2}
}

type ListSpacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spaces        []*Space               `protobuf:"bytes,1,rep,name=spaces,proto3" json:"spaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSpacesResponse) Reset() {
	*x = ListSpacesResponse{}
	mi := &file_space_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSpacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSpacesResponse) ProtoMessage() {}

func (x *ListSpacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSpacesResponse.ProtoReflect.Descriptor instead.
func (*ListSpacesResponse) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{3}
}

func (x *ListSpacesResponse) GetSpaces() []*Space {
	if x != nil {
		return x.Spaces
	}
	return nil
}

type CreateSpaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSpaceRequest) Reset() {
	*x = CreateSpaceRequest{}
	mi := &file_space_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSpaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSpaceRequest) ProtoMessage() {}

func (x *CreateSpaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSpaceRequest.ProtoReflect.Descriptor instead.
func (*CreateSpaceRequest) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSpaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersRequest) Reset() {
	*x = ListMembersRequest{}
	mi := &file_space_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersRequest) ProtoMessage() {}

func (x *ListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersRequest.ProtoReflect.Descriptor instead.
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{5}
}

func (x *ListMembersRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

type ListMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*Membership          `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersResponse) Reset() {
	*x = ListMembersResponse{}
	mi := &file_space_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersResponse) ProtoMessage() {}

func (x *ListMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersResponse.ProtoReflect.Descriptor instead.
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{6}
}

func (x *ListMembersResponse) GetMembers() []*Membership {
	if x != nil {
		return x.Members
	}
	return nil
}

type GrantRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"` // viewer | editor | admin
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantRoleRequest) Reset() {
	*x = GrantRoleRequest{}
	mi := &file_space_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantRoleRequest) ProtoMessage() {}

func (x *GrantRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantRoleRequest.ProtoReflect.Descriptor instead.
func (*GrantRoleRequest) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{7}
}

func (x *GrantRoleRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *GrantRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GrantRoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type RevokeRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRoleRequest) Reset() {
	*x = RevokeRoleRequest{}
	mi := &file_space_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRoleRequest) ProtoMessage() {}

func (x *RevokeRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRoleRequest.ProtoReflect.Descriptor instead.
func (*RevokeRoleRequest) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{8}
}

func (x *RevokeRoleRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *RevokeRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListAllMembershipsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllMembershipsRequest) Reset() {
	*x = ListAllMembershipsRequest{}
	mi := &file_space_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllMembershipsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllMembershipsRequest) ProtoMessage() {}

func (x *ListAllMembershipsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllMembershipsRequest.ProtoReflect.Descriptor instead.
func (*ListAllMembershipsRequest) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{9}
}

type ListAllMembershipsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memberships   []*Membership          `protobuf:"bytes,1,rep,name=memberships,proto3" json:"memberships,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllMembershipsResponse) Reset() {
	*x = ListAllMembershipsResponse{}
	mi := &file_space_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllMembershipsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllMembershipsResponse) ProtoMessage() {}

func (x *ListAllMembershipsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllMembershipsResponse.ProtoReflect.Descriptor instead.
func (*ListAllMembershipsResponse) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{10}
}

func (x *ListAllMembershipsResponse) GetMemberships() []*Membership {
	if x != nil {
		return x.Memberships
	}
	return nil
}

var File_space_proto protoreflect.FileDescriptor

const file_space_proto_rawDesc = "" +
	"\n" +
	"\vspace.proto\x12\x10marginal.auth.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdb\x01\n" +
	"\x05Space\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"is_default\x18\x03 \x01(\bR\tisDefault\x12\x1d\n" +
	"\n" +
	"created_by\x18\x04 \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1b\n" +
	"\tyour_role\x18\x06 \x01(\tR\byourRole\x12\x18\n" +
	"\amembers\x18\a \x01(\x05R\amembers\"\xc8\x01\n" +
	"\n" +
	"Membership\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bspace_id\x18\x02 \x01(\tR\aspaceId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x13\n" +
	"\x11ListSpacesRequest\"E\n" +
	"\x12ListSpacesResponse\x12/\n" +
	"\x06spaces\x18\x01 \x03(\v2\x17.marginal.auth.v1.SpaceR\x06spaces\"(\n" +
	"\x12CreateSpaceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"/\n" +
	"\x12ListMembersRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\"M\n" +
	"\x13ListMembersResponse\x126\n" +
	"\amembers\x18\x01 \x03(\v2\x1c.marginal.auth.v1.MembershipR\amembers\"Z\n" +
	"\x10GrantRoleRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"G\n" +
	"\x11RevokeRoleRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x1b\n" +
	"\x19ListAllMembershipsRequest\"\\\n" +
	"\x1aListAllMembershipsResponse\x12>\n" +
	"\vmemberships\x18\x01 \x03(\v2\x1c.marginal.auth.v1.MembershipR\vmemberships2\x9c\x04\n" +
	"\fSpaceService\x12W\n" +
	"\n" +
	"ListSpaces\x12#.marginal.auth.v1.ListSpacesRequest\x1a$.marginal.auth.v1.ListSpacesResponse\x12L\n" +
	"\vCreateSpace\x12$.marginal.auth.v1.CreateSpaceRequest\x1a\x17.marginal.auth.v1.Space\x12Z\n" +
	"\vListMembers\x12$.marginal.auth.v1.ListMembersRequest\x1a%.marginal.auth.v1.ListMembersResponse\x12M\n" +
	"\tGrantRole\x12\".marginal.auth.v1.GrantRoleRequest\x1a\x1c.marginal.auth.v1.Membership\x12I\n" +
	"\n" +
	"RevokeRole\x12#.marginal.auth.v1.RevokeRoleRequest\x1a\x16.google.protobuf.Empty\x12o\n" +
	"\x12ListAllMemberships\x12+.marginal.auth.v1.ListAllMembershipsRequest\x1a,.marginal.auth.v1.ListAllMembershipsResponseB'Z%marginal/auth-service/genproto/authv1b\x06proto3"

var (
	file_space_proto_rawDescOnce sync.Once
	file_space_proto_rawDescData []byte
)

func file_space_proto_rawDescGZIP() []byte {
	file_space_proto_rawDescOnce.Do(func() {
		file_space_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_space_proto_rawDesc), len(file_space_proto_rawDesc)))
	})
	return file_space_proto_rawDescData
}

var file_space_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_space_proto_goTypes = []any{
	(*Space)(nil),                      // 0: marginal.auth.v1.Space
	(*Membership)(nil),                 // 1: marginal.auth.v1.Membership
	(*ListSpacesRequest)(nil),          // 2: marginal.auth.v1.ListSpacesRequest
	(*ListSpacesResponse)(nil),         // 3: marginal.auth.v1.ListSpacesResponse
	(*CreateSpaceRequest)(nil),         // 4: marginal.auth.v1.CreateSpaceRequest
	(*ListMembersRequest)(nil),         // 5: marginal.auth.v1.ListMembersRequest
	(*ListMembersResponse)(nil),        // 6: marginal.auth.v1.ListMembersResponse
	(*GrantRoleRequest)(nil),           // 7: marginal.auth.v1.GrantRoleRequest
	(*RevokeRoleRequest)(nil),          // 8: marginal.auth.v1.RevokeRoleRequest
	(*ListAllMembershipsRequest)(nil),  // 9: marginal.auth.v1.ListAllMembershipsRequest
	(*ListAllMembershipsResponse)(nil), // 10: marginal.auth.v1.ListAllMembershipsResponse
	(*timestamppb.Timestamp)(nil),      // 11: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 12: google.protobuf.Empty
}
var file_space_proto_depIdxs = []int32{
	11, // 0: marginal.auth.v1.Space.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: marginal.auth.v1.Membership.created_at:type_name -> google.protobuf.Timestamp
	0,  // 2: marginal.auth.v1.ListSpacesResponse.spaces:type_name -> marginal.auth.v1.Space
	1,  // 3: marginal.auth.v1.ListMembersResponse.members:type_name -> marginal.auth.v1.Membership
	1,  // 4: marginal.auth.v1.ListAllMembershipsResponse.memberships:type_name -> marginal.auth.v1.Membership
	2,  // 5: marginal.auth.v1.SpaceService.ListSpaces:input_type -> marginal.auth.v1.ListSpacesRequest
	4,  // 6: marginal.auth.v1.SpaceService.CreateSpace:input_type -> marginal.auth.v1.CreateSpaceRequest
	5,  // 7: marginal.auth.v1.SpaceService.ListMembers:input_type -> marginal.auth.v1.ListMembersRequest
	7,  // 8: marginal.auth.v1.SpaceService.GrantRole:input_type -> marginal.auth.v1.GrantRoleRequest
	8,  // 9: marginal.auth.v1.SpaceService.RevokeRole:input_type -> marginal.auth.v1.RevokeRoleRequest
	9,  // 10: marginal.auth.v1.SpaceService.ListAllMemberships:input_type -> marginal.auth.v1.ListAllMembershipsRequest
	3,  // 11: marginal.auth.v1.SpaceService.ListSpaces:output_type -> marginal.auth.v1.ListSpacesResponse
	0,  // 12: marginal.auth.v1.SpaceService.CreateSpace:output_type -> marginal.auth.v1.Space
	6,  // 13: marginal.auth.v1.SpaceService.ListMembers:output_type -> marginal.auth.v1.ListMembersResponse
	1,  // 14: marginal.auth.v1.SpaceService.GrantRole:output_type -> marginal.auth.v1.Membership
	12, // 15: marginal.auth.v1.SpaceService.RevokeRole:output_type -> google.protobuf.Empty
	10, // 16: marginal.auth.v1.SpaceService.ListAllMemberships:output_type -> marginal.auth.v1.ListAllMembershipsResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_space_proto_init() }
func file_space_proto_init() {
	if File_space_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_space_proto_rawDesc), len(file_space_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_space_proto_goTypes,
		DependencyIndexes: file_space_proto_depIdxs,
		MessageInfos:      file_space_proto_msgTypes,
	}.Build()
	File_space_proto = out.File
	file_space_proto_goTypes = nil
	file_space_proto_depIdxs = nil
}
