// Package sortkey generates fractional-index sort keys: opaque,
// lexicographically-ordered strings such that a page or block can be
// reordered by writing ONE row, never by renumbering its siblings
// (DATA_MODEL.md §4's docs.pages.sort_key). Order by the string ascending;
// never parse it — docs/api/pages.md is explicit that sort_key is opaque.
package sortkey

import (
	"errors"
	"strings"
)

// alphabet is the digit set, in sort order — must match Go's byte-wise
// string comparison exactly (ASCII '0'-'9' < 'a'-'z' already holds, so a
// plain string compare on generated keys is a correct sort key compare).
const alphabet = "0123456789abcdefghijklmnopqrstuvwxyz"

const base = len(alphabet)

// ErrNoRoom is returned when there is no key strictly between prev and
// next left to generate — see the package doc comment on Between for when
// this can happen and how to recover.
var ErrNoRoom = errors.New("sortkey: no room between the given keys")

func digitValue(c byte) int { return strings.IndexByte(alphabet, c) }
func digitChar(v int) byte  { return alphabet[v] }

// Between returns a key that sorts strictly between prev and next.
//
// Invariants:
//  1. prev == "" means "no lower bound" (the result is the new first key).
//  2. next == "" means "no upper bound" (the result is the new last key).
//  3. Between("", "") — an empty sequence — returns a mid-alphabet key,
//     deliberately not an alphabet extreme, so there's room to insert
//     before or after it later.
//  4. The result R always satisfies prev < R < next (as plain string
//     comparison), for any prev, next this function successfully returns
//     for.
//  5. prev and next must themselves have been generated by this function
//     (or be "") — see ErrNoRoom.
//
// ErrNoRoom: this scheme's minimum representable value is a run of the
// alphabet's minimum digit ('0'), which nothing can sort below — extending
// a string that already matches another one exactly (as far as the other
// one goes) only ever produces something LARGER, never smaller. Between
// returns ErrNoRoom exactly when next consists entirely of the alphabet
// minimum from position 0 up to (and including) its last digit — e.g.
// Between("", "0") or Between("a", "a0") — and there is nothing left
// between prev and it. If it fires, the caller needs to rebalance:
// regenerate evenly-spaced keys for the affected sibling set in one
// transaction. A known, accepted limitation of every simple
// fractional-indexing scheme, not specific to this one.
func Between(prev, next string) (string, error) {
	if prev != "" && next != "" && prev >= next {
		return "", errors.New("sortkey: prev must sort strictly before next")
	}
	return between(prev, next)
}

// between compares prev and next position by position. At each position,
// a missing digit is treated as 0 for prev (there's nothing lower to
// anchor to) and as `base` for next (there's no upper limit past its end).
//
// The moment the two digits differ by more than 1, their midpoint is a
// valid single result — done.
//
// A difference of exactly 1 means prev's digit here is already strictly
// below next's, so the rest of the result no longer needs to respect next
// at all (`nextOpen` latches true and stays there). It does NOT mean the
// result is already greater than prev, though: if prev has more digits
// after this position (e.g. prev = "zi", matched at its first digit 'z'),
// the placed digit only TIES prev so far — the loop must keep going,
// unconstrained by next, until it out-compares whatever remains of prev.
// Only when prev is exhausted at this exact position is stopping safe
// immediately: a string extending an exhausted prev's matched prefix is
// always greater than prev, by the ordinary "prefix is less than any of
// its extensions" rule.
//
// A tie (equal digits, real or prev-defaulted) continues to the next
// position. The one case that can't be resolved: we reach the exact end
// of next (it had real digits, and every one of them tied) without ever
// having crossed below it via a diff-of-1 — that means the result so far
// equals next exactly, and nothing extends a string into something less
// than itself. That's ErrNoRoom. Reaching the end of an next that was
// empty from the very start (never had a real digit to tie against) is a
// different, always-fine case — handled by the default-open comparison
// below, not this one.
func between(prev, next string) (string, error) {
	var result []byte
	nextOpen := false
	for i := 0; ; i++ {
		prevHasDigit := i < len(prev)
		pDigit := 0
		if prevHasDigit {
			pDigit = digitValue(prev[i])
		}

		nextHasDigit := !nextOpen && i < len(next)
		if !nextHasDigit && !nextOpen && len(next) > 0 {
			return "", ErrNoRoom
		}
		nDigit := base
		if nextHasDigit {
			nDigit = digitValue(next[i])
		}

		switch {
		case nDigit-pDigit > 1:
			mid := pDigit + (nDigit-pDigit)/2
			result = append(result, digitChar(mid))
			return string(result), nil

		case nDigit-pDigit == 1:
			result = append(result, digitChar(pDigit))
			if !prevHasDigit {
				// prev is exhausted here — anything from here on already
				// exceeds prev (a longer string extending a matched
				// prefix is greater), and we've already secured < next.
				result = append(result, digitChar(base/2))
				return string(result), nil
			}
			// prev has more digits after this position; we've matched
			// prev's digit exactly and secured < next, but still need to
			// out-compare whatever prev has next. Keep going,
			// unconstrained by next from here on.
			nextOpen = true

		case !prevHasDigit && !nextHasDigit:
			// Both open from the start (Between("", "")).
			result = append(result, digitChar(base/2))
			return string(result), nil

		default: // tie: equal digits at this position
			result = append(result, digitChar(pDigit))
		}
	}
}
